### ISSUE TITLE
path_prefix does not match case-insensitve 

### ISSUE THREAD

**Issue by jca02266** [embulk/embulk#1021]
For example, following config.yml does not work on Windows. Because the prefix "SAMPLE_" does not match case-inseinsitive.

```
in:
  type: file
  path_prefix: WORK/CSV/SAMPLE_
```

This is quick hack. But, it should be specified a config parameter `file_name_prefix_ignore_case`.
How do you think about it?

```
diff --git a/embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java b/embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java
index 4e1cbfe7..4f2a0072 100644
--- a/embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java
+++ b/embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java
@@ -42,6 +42,10 @@ public class LocalFileInputPlugin implements FileInputPlugin {
         @ConfigDefault("null")
         Optional<String> getLastPath();
 
+        @Config("file_name_prefix_ignore_case")
+        @ConfigDefault("false")
+        boolean getFileNamePrefixIgnoreCase();
+
         @Config("follow_symlinks")
         @ConfigDefault("false")
         boolean getFollowSymlinks();
@@ -103,6 +107,13 @@ public class LocalFileInputPlugin implements FileInputPlugin {
             int taskCount,
             List<TaskReport> successTaskReports) {}
 
+    boolean pathStartsWith(PluginTask task, Path path, String prefix) {
+        String pathName = path.getFileName().toString();
+
+        boolean ignoreCase = task.getFileNamePrefixIgnoreCase();
+        return pathName.regionMatches(ignoreCase, 0, prefix, 0, prefix.length());
+    }
+
     public List<String> listFiles(PluginTask task) {
         Path pathPrefix = Paths.get(task.getPathPrefix()).normalize();
         final Path directory;
@@ -143,7 +154,7 @@ public class LocalFileInputPlugin implements FileInputPlugin {
                                 parent = CURRENT_DIR;
                             }
                             if (parent.equals(directory)) {
-                                if (path.getFileName().toString().startsWith(fileNamePrefix)) {
+                                if (pathStartsWith(task, path, fileNamePrefix)) {
                                     return FileVisitResult.CONTINUE;
                                 } else {
                                     return FileVisitResult.SKIP_SUBTREE;
@@ -175,7 +186,7 @@ public class LocalFileInputPlugin implements FileInputPlugin {
                                 parent = CURRENT_DIR;
                             }
                             if (parent.equals(directory)) {
-                                if (path.getFileName().toString().startsWith(fileNamePrefix)) {
+                                if (pathStartsWith(task, path, fileNamePrefix)) {
                                     builder.add(path.toString());
                                     return FileVisitResult.CONTINUE;
                                 }

```

**Comment by dmikurube** [comment]
@jca02266 Can you describe 1) for what files (on Windows) didn't the config.yml above work, 2) how did you work around?

The feature may be "nice to have", but I don't believe Embulk "should" implement it. I'm wondering if we could make decisions whether it's worth implementing in the core, or just workaround sounds enough.

**Comment by jca02266** [comment]
"PS>" is powershell's prompt.

```powershell
PS> mkdir work
(snip)
PS> cd work
PS> embulk example ./try1
2018-06-14 18:44:03.106 +0900: Embulk v0.9.7
(snip)
PS> ls try1
(snip)
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       2018/06/14     18:44                csv
-a----       2018/06/14     18:44             92 seed.yml
PS> embulk guess .\try1\seed.yml -o config.yml
(snip)
Created 'config.yml' file.
```

This is normal.

```
PS> embulk preview config.yml
(snip)
+---------+--------------+-------------------------+-------------------------+----------------------------+
| id:long | account:long |          time:timestamp |      purchase:timestamp |             comment:string |
+---------+--------------+-------------------------+-------------------------+----------------------------+
|       1 |       32,864 | 2015-01-27 19:23:49 UTC | 2015-01-27 00:00:00 UTC |                     embulk |
|       2 |       14,824 | 2015-01-27 19:01:23 UTC | 2015-01-27 00:00:00 UTC |               embulk jruby |
|       3 |       27,559 | 2015-01-28 02:20:02 UTC | 2015-01-28 00:00:00 UTC | Embulk "csv" parser plugin |
|       4 |       11,270 | 2015-01-29 11:54:36 UTC | 2015-01-29 00:00:00 UTC |                            |
+---------+--------------+-------------------------+-------------------------+----------------------------+
```

If I rename the directory try1 to TRY1, Embulk works as expected.

```powershell
PS> cmd /c "ren try1 TRY1"
PS> ls
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       2018/06/14     18:44                TRY1
-a----       2018/06/14     18:45            607 config.yml

PS> embulk preview config.yml
(snip)
+---------+--------------+-------------------------+-------------------------+----------------------------+
| id:long | account:long |          time:timestamp |      purchase:timestamp |             comment:string |
+---------+--------------+-------------------------+-------------------------+----------------------------+
|       1 |       32,864 | 2015-01-27 19:23:49 UTC | 2015-01-27 00:00:00 UTC |                     embulk |
|       2 |       14,824 | 2015-01-27 19:01:23 UTC | 2015-01-27 00:00:00 UTC |               embulk jruby |
|       3 |       27,559 | 2015-01-28 02:20:02 UTC | 2015-01-28 00:00:00 UTC | Embulk "csv" parser plugin |
|       4 |       11,270 | 2015-01-29 11:54:36 UTC | 2015-01-29 00:00:00 UTC |                            |
+---------+--------------+-------------------------+-------------------------+----------------------------+
```

But, I rename a file sample_01.csv.gz to SAMPLE_01.csv.gz, Embulk cause exception.

```powershell
PS> mv .\try1\csv\sample_01.csv.gz .\try1\csv\SAMPLE_01.csv.gz
PS> embulk preview config.yml
2018-06-14 18:52:46.263 +0900: Embulk v0.9.7
2018-06-14 18:52:48.507 +0900 [WARN] (main): DEPRECATION: JRuby org.jruby.embed.ScriptingContainer is directly injected.
2018-06-14 18:52:55.945 +0900 [INFO] (main): Gem's home and path are set by default: "C:\Users\Koji\.embulk\lib\gems"
2018-06-14 18:52:59.553 +0900 [INFO] (main): Started Embulk v0.9.7
2018-06-14 18:52:59.705 +0900 [INFO] (0001:preview): Listing local files at directory 'C:\Users\Koji\work\try1\csv' filtering filename by prefix 'sample_'
2018-06-14 18:52:59.715 +0900 [INFO] (0001:preview): "follow_symlinks" is set false. Note that symbolic links to directories are skipped.
2018-06-14 18:52:59.727 +0900 [INFO] (0001:preview): Loading files []
2018-06-14 18:52:59.763 +0900 [INFO] (0001:preview): Try to read 32,768 bytes from input source
org.embulk.exec.NoSampleException: No input files to read sample data
        at org.embulk.exec.SamplingParserPlugin$1.run(SamplingParserPlugin.java:49)
        at org.embulk.spi.FileInputRunner$RunnerControl$1$1.run(FileInputRunner.java:112)
        at org.embulk.exec.SamplingParserPlugin.transaction(SamplingParserPlugin.java:147)
        at org.embulk.spi.FileInputRunner$RunnerControl$1.run(FileInputRunner.java:107)
        at org.embulk.spi.util.Decoders$RecursiveControl.transaction(Decoders.java:68)
        at org.embulk.spi.util.Decoders.transaction(Decoders.java:29)
        at org.embulk.spi.FileInputRunner$RunnerControl.run(FileInputRunner.java:105)
        at org.embulk.standards.LocalFileInputPlugin.resume(LocalFileInputPlugin.java:81)
        at org.embulk.standards.LocalFileInputPlugin.transaction(LocalFileInputPlugin.java:72)
        at org.embulk.spi.FileInputRunner.transaction(FileInputRunner.java:62)
        at org.embulk.exec.SamplingParserPlugin.runFileInputSampling(SamplingParserPlugin.java:46)
        at org.embulk.exec.PreviewExecutor.doPreview(PreviewExecutor.java:99)
        at org.embulk.exec.PreviewExecutor.access$000(PreviewExecutor.java:29)
        at org.embulk.exec.PreviewExecutor$1.run(PreviewExecutor.java:73)
        at org.embulk.exec.PreviewExecutor$1.run(PreviewExecutor.java:70)
        at org.embulk.spi.Exec.doWith(Exec.java:22)
        at org.embulk.exec.PreviewExecutor.preview(PreviewExecutor.java:70)
        at org.embulk.EmbulkEmbed.preview(EmbulkEmbed.java:151)
        at org.embulk.EmbulkRunner.previewInternal(EmbulkRunner.java:215)
        at org.embulk.EmbulkRunner.preview(EmbulkRunner.java:107)
        at org.embulk.cli.EmbulkRun.runSubcommand(EmbulkRun.java:433)
        at org.embulk.cli.EmbulkRun.run(EmbulkRun.java:91)
        at org.embulk.cli.Main.main(Main.java:26)

Error: No input files to read sample data
PS>
```

Embulk treats directory name as case-insensitive, but filename prefix is not so.
IMHO, it is non-consistency behavior.

And, I have no workaround for that.

**Comment by dmikurube** [comment]
@jca02266 Why didn't you change the `config.yml` to `SAMPLE_` while you say "I have no workaround for that."?

If config's `sample_` does not work for the file `sample_01.csv`, that needs to be fixed.
If config's `SAMPLE_` does not work for the file `SAMPLE_01.csv`, that needs to be fixed, too.
But if config's `sample_` does not work for the file `SAMPLE_`, that's not trivial.
It may be inconsistent with the directory name's behavior, but to me, it does not sound worth adding a new configuration.

**Comment by jca02266** [comment]
OK, I did not write about the trouble that I faced.

I made a config.yml. At first, the prefix was "sample_".
Input file, sample_001.csv, sample_002.csv were generated by a program.

Embulk has been worked for a long time. However, the program to generate the input file was redesigned.
The new program generates file prefixed "Sample_" and embulk did not work. (I didn't know what happened for a while)

Of course, I rewrote the prefix to "Sample_" in the config.yml, But, I sometimes must load old file prefixed "sample_", too. Then I must rewrite config.yml again.

This is new patch. It is not necessary an extra parameter.

```
diff --git a/embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java b/embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java
index 4e1cbfe7..f9adda8f 100644
--- a/embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java
+++ b/embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java
@@ -6,10 +6,12 @@ import java.io.File;
 import java.io.FileInputStream;
 import java.io.IOException;
 import java.io.InputStream;
+import java.nio.file.FileSystems;
 import java.nio.file.FileVisitOption;
 import java.nio.file.FileVisitResult;
 import java.nio.file.Files;
 import java.nio.file.Path;
+import java.nio.file.PathMatcher;
 import java.nio.file.Paths;
 import java.nio.file.SimpleFileVisitor;
 import java.nio.file.attribute.BasicFileAttributes;
@@ -103,17 +105,44 @@ public class LocalFileInputPlugin implements FileInputPlugin {
             int taskCount,
             List<TaskReport> successTaskReports) {}
 
+    String escapeGlobPattern(String filenamePrefix) {
+        StringBuilder sb = new StringBuilder();
+        final int len = filenamePrefix.length();
+        for (int i = 0; i < len; i++) {
+            char c = filenamePrefix.charAt(i);
+            switch (c) {
+                case '*':
+                case '?':
+                case '{':
+                case '}':
+                case '[':
+                case ']':
+                case '\\':
+                    sb.append('\\');
+                    break;
+                default:
+                    break;
+            }
+            sb.append(c);
+        }
+        return sb.toString();
+    }
+
     public List<String> listFiles(PluginTask task) {
         Path pathPrefix = Paths.get(task.getPathPrefix()).normalize();
         final Path directory;
         final String fileNamePrefix;
+        final PathMatcher pathMatcher;
         if (Files.isDirectory(pathPrefix)) {
             directory = pathPrefix;
             fileNamePrefix = "";
+            pathMatcher = null;
         } else {
             fileNamePrefix = pathPrefix.getFileName().toString();
             Path d = pathPrefix.getParent();
             directory = (d == null ? CURRENT_DIR : d);
+
+            pathMatcher = FileSystems.getDefault().getPathMatcher("glob:" + escapeGlobPattern(fileNamePrefix) + "*");
         }
 
         final ImmutableList.Builder<String> builder = ImmutableList.builder();
@@ -143,7 +172,7 @@ public class LocalFileInputPlugin implements FileInputPlugin {
                                 parent = CURRENT_DIR;
                             }
                             if (parent.equals(directory)) {
-                                if (path.getFileName().toString().startsWith(fileNamePrefix)) {
+                                if (pathMatcher == null || pathMatcher.matches(path.getFileName())) {
                                     return FileVisitResult.CONTINUE;
                                 } else {
                                     return FileVisitResult.SKIP_SUBTREE;
@@ -175,7 +204,7 @@ public class LocalFileInputPlugin implements FileInputPlugin {
                                 parent = CURRENT_DIR;
                             }
                             if (parent.equals(directory)) {
-                                if (path.getFileName().toString().startsWith(fileNamePrefix)) {
+                                if (pathMatcher == null || pathMatcher.matches(path.getFileName())) {
                                     builder.add(path.toString());
                                     return FileVisitResult.CONTINUE;
                                 }
```

**Comment by dmikurube** [comment]
@jca02266 Thanks for the details of your problem, and a new patch. I understood your problem, but it honestly sounds like a problem on your side. Just for the problem, I basically don't think Embulk "should" be fixed.

On the other hand, the patch of yours looks worth applying because it is trying well to follow the operating system's default behavior, not to implement case-insensitivity by Embulk itself. That sounds like a better behavior than the existing although we need to confirm, check, and test whether this is safe enough to apply as-is, or this needs some more fix. Sorry that it may need some more time.

We can create a PR based on your patch with some modification, or you're welcome to create a PR (in that case, we may ask you to follow review-and-fix cycles). What do you think?

(Or, if you'd like to leave your named Git commit and to defer later modifications on us, we're fine to make an initial empty PR, and you can push your commit there.)

**Comment by jca02266** [comment]
Thanks for your time! I will create a PR later.
