### ISSUE TITLE
illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by diegotejadav** [embulk/embulk#1032]
I'm on Mac OSX High Sierra 10.13.6.
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)

I'm trying Embulk, and I'm having the next error messages when running ```embulk guess   ./try1/seed.yml -o config.yml``` command as shown in the [Running Example](https://github.com/embulk/embulk#running-example):

**Error message:**
```sh
2018-07-23 11:13:07.717 -0500: Embulk v0.9.7
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$2 (file:/Users/diegotejadav/.embulk/bin/embulk) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.NoClassDefFoundError: javax/annotation/PostConstruct
	at org.embulk.guice.LifeCycleMethods.addLifeCycleMethods(LifeCycleMethods.java:65)
	at org.embulk.guice.LifeCycleMethods.<init>(LifeCycleMethods.java:39)
	at org.embulk.guice.LifeCycleMethodsMap.get(LifeCycleMethodsMap.java:33)
	at org.embulk.guice.LifeCycleModule.isLifeCycleClass(LifeCycleModule.java:105)
	at org.embulk.guice.LifeCycleModule.access$000(LifeCycleModule.java:41)
	at org.embulk.guice.LifeCycleModule$1$1.afterInjection(LifeCycleModule.java:73)
	at com.google.inject.internal.MembersInjectorImpl.notifyListeners(MembersInjectorImpl.java:119)
	at com.google.inject.internal.MembersInjectorImpl.injectAndNotify(MembersInjectorImpl.java:111)
	at com.google.inject.internal.Initializer$InjectableReference.get(Initializer.java:174)
	at com.google.inject.internal.Initializer.injectAll(Initializer.java:108)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:174)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:110)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at org.embulk.guice.Bootstrap.start(Bootstrap.java:143)
	at org.embulk.guice.Bootstrap.build(Bootstrap.java:110)
	at org.embulk.guice.Bootstrap.initialize(Bootstrap.java:100)
	at org.embulk.EmbulkEmbed$Bootstrap.build(EmbulkEmbed.java:98)
	at org.embulk.EmbulkEmbed$Bootstrap.initialize(EmbulkEmbed.java:78)
	at org.embulk.EmbulkSetup.setup(EmbulkSetup.java:32)
	at org.embulk.cli.EmbulkRun.runSubcommand(EmbulkRun.java:418)
	at org.embulk.cli.EmbulkRun.run(EmbulkRun.java:91)
	at org.embulk.cli.Main.main(Main.java:26)
Caused by: java.lang.ClassNotFoundException: javax.annotation.PostConstruct
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 22 more

```

**Comment by diegotejadav** [comment]
I'm sorry, I haven't had read this "Java 9 is not supported in any version for the time being".
I'll try installing that version of Java.
Thanks anyway!
