### ISSUE TITLE
[Bug Report] Error: org.embulk.config.ConfigException: Couldn't delete local file

### ISSUE THREAD

**Issue by kulmam92** [embulk/embulk#1051]
Issue Type: Bug Report
-----------------------

* Write the following environmental information.
  * OS version - windows 10
  * Java version - jdk 8
  * Embulk version - 0.9.31
  * Your Embulk configuration (YAML)
  ```yaml
  in:
    type: sqlserver
    driver_path: C:\Util\drivers\mssql-jdbc-7.0.0.jre8.jar
    host: localhost
    port: 1433
    integratedSecurity: true
    database: mydatabase
    query:
      SELECT top 10
            [my_IDENTITY]
            ,[ZONE]
        FROM [dbo].[mytab]
      where [my_IDENTITY] >= :my_IDENTITY
    use_raw_query_with_incremental: true
    incremental_columns:
      - my_IDENTITY
    incremental: true
    last_record: [1]
  out:
    type: azure_blob_storage
    account_name: XXXXXXXXXXX
    account_key: XXXXXXXXXXXX
    container: XXXXXXXXXXX
    path_prefix: my-csv-
    file_ext: csv
    formatter:
      type: csv
      header_line: false
  ```

  * Plugin versions - embulk-output-azure_blob_storage (0.1.5)
  * Write all what you did, e.g. your commands executed
  * Write what you expected and observed actually

When I run this on linux it works but it fails with below error when I run in windows
```Error: org.embulk.config.ConfigException: Couldn't delete local file c:\tmp\my-csv-000.00.csv8596539147105778010.tmp```

```java
org.embulk.exec.PartialExecutionException: org.embulk.config.ConfigException: Couldn't delete local file c:\tmp\my-csv-000.00.csv8596539147105778010.tmp
        at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(BulkLoader.java:339)
        at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:565)
        at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:34)
        at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:352)
        at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:349)
        at org.embulk.spi.Exec.doWith(Exec.java:22)
        at org.embulk.exec.BulkLoader.run(BulkLoader.java:349)
        at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:161)
        at org.embulk.EmbulkRunner.runInternal(EmbulkRunner.java:292)
        at org.embulk.EmbulkRunner.run(EmbulkRunner.java:156)
        at org.embulk.cli.EmbulkRun.runSubcommand(EmbulkRun.java:436)
        at org.embulk.cli.EmbulkRun.run(EmbulkRun.java:91)
        at org.embulk.cli.Main.main(Main.java:26)
Caused by: org.embulk.config.ConfigException: Couldn't delete local file c:\tmp\my-csv-000.00.csv8596539147105778010.tmp
        at org.embulk.output.azure_blob_storage.AzureBlobStorageFileOutputPlugin$AzureFileOutput$1.call(AzureBlobStorageFileOutputPlugin.java:227)
        at org.embulk.output.azure_blob_storage.AzureBlobStorageFileOutputPlugin$AzureFileOutput$1.call(AzureBlobStorageFileOutputPlugin.java:216)
        at org.embulk.spi.util.RetryExecutor.run(RetryExecutor.java:81)
        at org.embulk.spi.util.RetryExecutor.runInterruptible(RetryExecutor.java:62)
        at org.embulk.output.azure_blob_storage.AzureBlobStorageFileOutputPlugin$AzureFileOutput.uploadFile(AzureBlobStorageFileOutputPlugin.java:216)
        at org.embulk.output.azure_blob_storage.AzureBlobStorageFileOutputPlugin$AzureFileOutput.finish(AzureBlobStorageFileOutputPlugin.java:205)
        at org.embulk.spi.util.FileOutputOutputStream.close(FileOutputOutputStream.java:94)
        at sun.nio.cs.StreamEncoder.implClose(Unknown Source)
        at sun.nio.cs.StreamEncoder.close(Unknown Source)
        at java.io.OutputStreamWriter.close(Unknown Source)
        at java.io.BufferedWriter.close(Unknown Source)
        at org.embulk.spi.util.LineEncoder.finish(LineEncoder.java:90)
        at org.embulk.standards.CsvFormatterPlugin$1.finish(CsvFormatterPlugin.java:194)
        at org.embulk.spi.FileOutputRunner$DelegateTransactionalPageOutput.finish(FileOutputRunner.java:154)
        at org.embulk.exec.LocalExecutorPlugin$ScatterTransactionalPageOutput.finish(LocalExecutorPlugin.java:447)
        at org.embulk.spi.PageBuilder.finish(PageBuilder.java:228)
        at org.embulk.input.jdbc.AbstractJdbcInputPlugin.run(AbstractJdbcInputPlugin.java:493)
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.runInputTask(LocalExecutorPlugin.java:271)
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.access$000(LocalExecutorPlugin.java:196)
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor$1.call(LocalExecutorPlugin.java:235)
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor$1.call(LocalExecutorPlugin.java:232)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
        Suppressed: org.embulk.config.ConfigException: Couldn't delete local file c:\tmp\my-csv-001.00.csv9196116221386038964.tmp
                at org.embulk.output.azure_blob_storage.AzureBlobStorageFileOutputPlugin$AzureFileOutput$1.call(AzureBlobStorageFileOutputPlugin.java:227)
                at org.embulk.output.azure_blob_storage.AzureBlobStorageFileOutputPlugin$AzureFileOutput$1.call(AzureBlobStorageFileOutputPlugin.java:216)
                at org.embulk.spi.util.RetryExecutor.run(RetryExecutor.java:81)
                at org.embulk.spi.util.RetryExecutor.runInterruptible(RetryExecutor.java:62)
                at org.embulk.output.azure_blob_storage.AzureBlobStorageFileOutputPlugin$AzureFileOutput.uploadFile(AzureBlobStorageFileOutputPlugin.java:216)
                at org.embulk.output.azure_blob_storage.AzureBlobStorageFileOutputPlugin$AzureFileOutput.finish(AzureBlobStorageFileOutputPlugin.java:205)
                at org.embulk.spi.util.FileOutputOutputStream.close(FileOutputOutputStream.java:94)
                at sun.nio.cs.StreamEncoder.implClose(Unknown Source)
                at sun.nio.cs.StreamEncoder.close(Unknown Source)
                at java.io.OutputStreamWriter.close(Unknown Source)
                at java.io.BufferedWriter.close(Unknown Source)
                at org.embulk.spi.util.LineEncoder.close(LineEncoder.java:103)
                at org.embulk.standards.CsvFormatterPlugin$1.close(CsvFormatterPlugin.java:198)
                at org.embulk.spi.FileOutputRunner$DelegateTransactionalPageOutput.close(FileOutputRunner.java:159)
                at org.embulk.spi.CloseResource.close(CloseResource.java:25)
                at org.embulk.exec.LocalExecutorPlugin$ScatterTransactionalPageOutput.close(LocalExecutorPlugin.java:455)
                at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.runInputTask(LocalExecutorPlugin.java:283)
                ... 7 more
```

It looks like this is caused by the windows path when deleting temp file.

Java and Windows - error: illegal escape character
https://stackoverflow.com/questions/12889275/java-and-windows-error-illegal-escape-character

**Comment by sakama** [comment]
Hi, I'm an author of [embulk-output-azure_blob_storage](https://github.com/embulk/embulk-output-azure_blob_storage/).
This might be a plugin's matter, not an Embulk's problem.
I'll take a look at plugin implementation.

Thanks.

**Comment by kulmam92** [comment]
@sakama That's right.
Thank you.

**Comment by dmikurube** [comment]
@kulmam92 Let me close on the embulk/embulk side. Please file plugin's issue in plugin's repository next time.
