### ISSUE TITLE
Support Java 9+

### ISSUE THREAD

**Issue by kamatama41** [embulk/embulk#1064]

**Comment by kamatama41** [comment]
`embulk run` with OpenJDK 9.0.4 causes the following error in my environment.

```
2018-11-20 14:51:00.941 +0900: Embulk v0.9.10-SNAPSHOT
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at org.apache.bval.jsr303.ConfigurationImpl.parseValidationXml(ConfigurationImpl.java:268)
	at org.apache.bval.jsr303.ConfigurationImpl.prepare(ConfigurationImpl.java:258)
	at org.apache.bval.jsr303.ConfigurationImpl.doPrivBuildValidatorFactory(ConfigurationImpl.java:248)
	at org.apache.bval.jsr303.util.SecureActions$5.run(SecureActions.java:131)
	at org.apache.bval.jsr303.util.SecureActions$5.run(SecureActions.java:129)
	at org.apache.bval.jsr303.ConfigurationImpl.run(ConfigurationImpl.java:337)
	at org.apache.bval.jsr303.ConfigurationImpl.buildValidatorFactory(ConfigurationImpl.java:244)
	at org.embulk.config.ModelManager.<init>(ModelManager.java:24)
	at org.embulk.EmbulkEmbed.newSystemConfigLoader(EmbulkEmbed.java:236)
	at org.embulk.EmbulkEmbed$Bootstrap.<init>(EmbulkEmbed.java:94)
	at org.embulk.EmbulkSetup.setup(EmbulkSetup.java:29)
	at org.embulk.cli.EmbulkRun.runSubcommand(EmbulkRun.java:418)
	at org.embulk.cli.EmbulkRun.run(EmbulkRun.java:91)
	at org.embulk.cli.Main.main(Main.java:26)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 14 more

```

**Comment by dmikurube** [comment]
How did you run which version?
https://github.com/embulk/embulk/issues/976
https://github.com/embulk/embulk/pull/1049

**Comment by kamatama41** [comment]
Ah, sorry I ran the main class directly from Gradle and I didn't know the workaround. will close 🙇
