### ISSUE TITLE
not supporting java version 12

### ISSUE THREAD

**Issue by whitesiroi** [embulk/embulk#1168]
Issue Type: Bug Report
-----------------------

* Write the following environmental information.
  * OS version: macOS High Sierra 10.13.6

  * Java version:
$ java -version
java version "12.0.2" 2019-07-16
Java(TM) SE Runtime Environment (build 12.0.2+10)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.2+10, mixed mode, sharing)

  * Embulk version: 
Embulk v0.9.17

Getting error when trying to run the example on the [main page](https://github.com/embulk/embulk):

```
artem@machine:~/mdpr-vagrant/projects/mdpr_admin (master)$ embulk example ./try1
[WARN] Unrecognized Java version: java full version "12.0.2+10"

Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option AggressiveOpts; support was removed in 12.0
2019-08-01 18:44:04.240 +0900: Embulk v0.9.17
Creating ./try1 directory...
  Creating ./try1/
  Creating ./try1/csv/
  Creating ./try1/csv/sample_01.csv.gz
  Creating ./try1/seed.yml

Run following subcommands to try embulk:

   1. embulk guess ./try1/seed.yml -o config.yml
   2. embulk preview config.yml
   3. embulk run config.yml

artem@machine:~/mdpr-vagrant/projects/mdpr_admin (master)$ embulk guess   ./try1/seed.yml -o config.yml
[WARN] Unrecognized Java version: java full version "12.0.2+10"

Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option AggressiveOpts; support was removed in 12.0
2019-08-01 18:44:07.368 +0900: Embulk v0.9.17
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$2 (file:/Users/artem/.embulk/bin/embulk) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2019-08-01 18:44:08.334 +0900 [WARN] (main): DEPRECATION: JRuby org.jruby.embed.ScriptingContainer is directly injected.
unsupported Java version "12", defaulting to 1.7
2019-08-01 18:44:11.393 +0900 [INFO] (main): Gem's home and path are set by default: "/Users/artem/.embulk/lib/gems"
2019-08-01 18:44:12.680 +0900 [INFO] (main): Started Embulk v0.9.17
2019-08-01 18:44:12.791 +0900 [INFO] (0001:guess): Listing local files at directory '/Users/artem/mdpr-vagrant/projects/mdpr_admin/./try1/csv' filtering filename by prefix 'sample_'
2019-08-01 18:44:12.793 +0900 [INFO] (0001:guess): "follow_symlinks" is set false. Note that symbolic links to directories are skipped.
2019-08-01 18:44:12.796 +0900 [INFO] (0001:guess): Loading files [/Users/artem/mdpr-vagrant/projects/mdpr_admin/./try1/csv/sample_01.csv.gz]
2019-08-01 18:44:12.819 +0900 [INFO] (0001:guess): Try to read 32,768 bytes from input source
2019-08-01 18:44:13.012 +0900 [INFO] (0001:guess): Loaded plugin embulk (0.9.17)
2019-08-01 18:44:13.059 +0900 [INFO] (0001:guess): Loaded plugin embulk (0.9.17)
2019-08-01 18:44:13.108 +0900 [INFO] (0001:guess): Loaded plugin embulk (0.9.17)
2019-08-01 18:44:13.149 +0900 [INFO] (0001:guess): Loaded plugin embulk (0.9.17)
in:
  type: file
  path_prefix: /Users/artem/mdpr-vagrant/projects/mdpr_admin/./try1/csv/sample_
  decoders:
  - {type: gzip}
  parser:
    charset: UTF-8
    newline: LF
    type: csv
    delimiter: ','
    quote: '"'
    escape: '"'
    null_string: 'NULL'
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: id, type: long}
    - {name: account, type: long}
    - {name: time, type: timestamp, format: '%Y-%m-%d %H:%M:%S'}
    - {name: purchase, type: timestamp, format: '%Y%m%d'}
    - {name: comment, type: string}
out: {type: stdout}

Created 'config.yml' file.
artem@machine:~/mdpr-vagrant/projects/mdpr_admin (master)$ embulk preview config.yml
[WARN] Unrecognized Java version: java full version "12.0.2+10"

Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option AggressiveOpts; support was removed in 12.0
2019-08-01 18:44:20.376 +0900: Embulk v0.9.17
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$2 (file:/Users/artem/.embulk/bin/embulk) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2019-08-01 18:44:21.392 +0900 [WARN] (main): DEPRECATION: JRuby org.jruby.embed.ScriptingContainer is directly injected.
unsupported Java version "12", defaulting to 1.7
2019-08-01 18:44:24.463 +0900 [INFO] (main): Gem's home and path are set by default: "/Users/artem/.embulk/lib/gems"
2019-08-01 18:44:25.721 +0900 [INFO] (main): Started Embulk v0.9.17
2019-08-01 18:44:25.834 +0900 [INFO] (0001:preview): Listing local files at directory '/Users/artem/mdpr-vagrant/projects/mdpr_admin/./try1/csv' filtering filename by prefix 'sample_'
2019-08-01 18:44:25.836 +0900 [INFO] (0001:preview): "follow_symlinks" is set false. Note that symbolic links to directories are skipped.
2019-08-01 18:44:25.838 +0900 [INFO] (0001:preview): Loading files [/Users/artem/mdpr-vagrant/projects/mdpr_admin/./try1/csv/sample_01.csv.gz]
2019-08-01 18:44:25.852 +0900 [INFO] (0001:preview): Try to read 32,768 bytes from input source
+---------+--------------+-------------------------+-------------------------+----------------------------+
| id:long | account:long |          time:timestamp |      purchase:timestamp |             comment:string |
+---------+--------------+-------------------------+-------------------------+----------------------------+
|       1 |       32,864 | 2015-01-27 19:23:49 UTC | 2015-01-27 00:00:00 UTC |                     embulk |
|       2 |       14,824 | 2015-01-27 19:01:23 UTC | 2015-01-27 00:00:00 UTC |               embulk jruby |
|       3 |       27,559 | 2015-01-28 02:20:02 UTC | 2015-01-28 00:00:00 UTC | Embulk "csv" parser plugin |
|       4 |       11,270 | 2015-01-29 11:54:36 UTC | 2015-01-29 00:00:00 UTC |                            |
+---------+--------------+-------------------------+-------------------------+----------------------------+
artem@machine:~/mdpr-vagrant/projects/mdpr_admin (master)$ embulk run     config.yml
[WARN] Unrecognized Java version: java full version "12.0.2+10"

Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option AggressiveOpts; support was removed in 12.0
Java HotSpot(TM) 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
2019-08-01 18:44:29.626 +0900: Embulk v0.9.17
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at org.apache.bval.jsr303.ConfigurationImpl.parseValidationXml(ConfigurationImpl.java:268)
	at org.apache.bval.jsr303.ConfigurationImpl.prepare(ConfigurationImpl.java:258)
	at org.apache.bval.jsr303.ConfigurationImpl.doPrivBuildValidatorFactory(ConfigurationImpl.java:248)
	at org.apache.bval.jsr303.util.SecureActions$5.run(SecureActions.java:131)
	at org.apache.bval.jsr303.util.SecureActions$5.run(SecureActions.java:129)
	at org.apache.bval.jsr303.ConfigurationImpl.run(ConfigurationImpl.java:337)
	at org.apache.bval.jsr303.ConfigurationImpl.buildValidatorFactory(ConfigurationImpl.java:244)
	at org.embulk.config.ModelManager.<init>(ModelManager.java:24)
	at org.embulk.EmbulkEmbed.newSystemConfigLoader(EmbulkEmbed.java:35)
	at org.embulk.EmbulkEmbed$Bootstrap.<init>(EmbulkEmbed.java:48)
	at org.embulk.EmbulkSetup.setup(EmbulkSetup.java:29)
	at org.embulk.cli.EmbulkRun.runSubcommand(EmbulkRun.java:415)
	at org.embulk.cli.EmbulkRun.run(EmbulkRun.java:90)
	at org.embulk.cli.Main.main(Main.java:64)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 14 more
artem@machine:~/mdpr-vagrant/projects/mdpr_admin (master)$
```

**Comment by hiroyuki-sato** [comment]
Hello, @whitesiroi 
As [README said](https://github.com/embulk/embulk#linux--mac--bsd), You need to use Java8 for Embulk v9, Java 12 doesn't support yet.
> Embulk v0.9 series runs on Java 8

**Comment by whitesiroi** [comment]
@hiroyuki-sato thank you
