### ISSUE TITLE
`Unexpected end of ZLIB input stream` when Preview 

### ISSUE THREAD

**Issue by xuantuan58** [embulk/embulk#1169]
When Preview my Gzipped CSV file Embulk throws an exception (Note: My CSV file has many columns and data on each row)
```
2019-08-07 02:37:15.466 +0700 [INFO] (0001:preview): Try to read 32,768 bytes from input source
java.lang.RuntimeException: java.io.EOFException: Unexpected end of ZLIB input stream
        at org.embulk.spi.util.InputStreamFileInput.poll(InputStreamFileInput.java:160)
        at org.embulk.spi.util.FileInputInputStream.nextBuffer(FileInputInputStream.java:80)
        at org.embulk.spi.util.FileInputInputStream.read(FileInputInputStream.java:48)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.io.BufferedReader.readLine(BufferedReader.java:324)
        at java.io.BufferedReader.readLine(BufferedReader.java:389)
        at org.embulk.spi.util.LineDecoder.poll(LineDecoder.java:90)
        at org.embulk.standards.CsvTokenizer.nextLine(CsvTokenizer.java:140)
        at org.embulk.standards.CsvTokenizer.nextRecord(CsvTokenizer.java:126)
        at org.embulk.standards.CsvTokenizer.nextRecord(CsvTokenizer.java:117)
        at org.embulk.standards.CsvParserPlugin.run(CsvParserPlugin.java:346)
        at org.embulk.spi.FileInputRunner.run(FileInputRunner.java:140)
        at org.embulk.exec.PreviewExecutor$2$1.run(PreviewExecutor.java:131)
        at org.embulk.spi.util.Filters$RecursiveControl.transaction(Filters.java:84)
        at org.embulk.spi.util.Filters.transaction(Filters.java:42)
        at org.embulk.exec.PreviewExecutor$2.run(PreviewExecutor.java:121)
        at org.embulk.spi.FileInputRunner$RunnerControl$1$1.run(FileInputRunner.java:112)
        at org.embulk.standards.CsvParserPlugin.transaction(CsvParserPlugin.java:226)
        at org.embulk.spi.FileInputRunner$RunnerControl$1.run(FileInputRunner.java:107)
        at org.embulk.spi.util.Decoders$RecursiveControl.transaction(Decoders.java:68)
        at org.embulk.spi.util.Decoders$RecursiveControl$1.run(Decoders.java:64)
        at org.embulk.standards.GzipFileDecoderPlugin.transaction(GzipFileDecoderPlugin.java:25)
        at org.embulk.spi.util.Decoders$RecursiveControl.transaction(Decoders.java:60)
        at org.embulk.spi.util.Decoders.transaction(Decoders.java:29)
        at org.embulk.spi.FileInputRunner$RunnerControl.run(FileInputRunner.java:105)
        at org.embulk.exec.BufferFileInputPlugin.transaction(BufferFileInputPlugin.java:21)
        at org.embulk.spi.FileInputRunner.transaction(FileInputRunner.java:62)
        at org.embulk.exec.PreviewExecutor.doPreview(PreviewExecutor.java:119)
        at org.embulk.exec.PreviewExecutor.doPreview(PreviewExecutor.java:105)
        at org.embulk.exec.PreviewExecutor.access$000(PreviewExecutor.java:30)
        at org.embulk.exec.PreviewExecutor$1.run(PreviewExecutor.java:74)
        at org.embulk.exec.PreviewExecutor$1.run(PreviewExecutor.java:71)
        at org.embulk.spi.Exec.doWith(Exec.java:22)
        at org.embulk.exec.PreviewExecutor.preview(PreviewExecutor.java:71)
        at org.embulk.EmbulkEmbed.preview(EmbulkEmbed.java:168)
        at org.embulk.EmbulkRunner.previewInternal(EmbulkRunner.java:215)
        at org.embulk.EmbulkRunner.preview(EmbulkRunner.java:107)
        at org.embulk.cli.EmbulkRun.runSubcommand(EmbulkRun.java:430)
        at org.embulk.cli.EmbulkRun.run(EmbulkRun.java:90)
        at org.embulk.cli.Main.main(Main.java:64)
Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
        at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)
        at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
        at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
        at org.embulk.spi.util.InputStreamFileInput.poll(InputStreamFileInput.java:151)
        ... 43 more
```
Note: the `embulk guess` command works fine, the `embulk run` command also works fine.

* I was run the Embulk on a Mac Pro version `10.13.6`
* Java version: 1.8
* Embulk version: 0.9.17
* the yml config file as:
```yaml
in:
  type: file
  path_prefix: data.csv.gz
  decoders:
  - {type: gzip}
  parser:
    type: csv
    charset: UTF-8
    newline: LF
    delimiter: ','
    quote: '"'
    escape: '"'
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: column_0, type: long}
    - {name: column_1, type: string}
    - {name: column_2, type: string}
    - {name: column_3, type: string}
    - {name: column_4, type: string}
    - {name: column_5, type: string}
    - {name: column_6, type: string}
    - {name: column_7, type: string}
    - {name: column_8, type: string}
    - {name: column_9, type: string}
    - {name: column_10, type: string}
    - {name: column_11, type: string}
    - {name: column_12, type: string}
    - {name: column_13, type: string}
    - {name: column_14, type: string}
    - {name: column_15, type: string}
    - {name: column_16, type: string}
    - {name: column_17, type: string}
    - {name: column_18, type: string}
    - {name: column_19, type: string}
    - {name: column_20, type: string}
    - {name: column_21, type: string}
    - {name: column_22, type: string}
...
```

I was running the embulk preview command `embulk preview config.yml` then the error occurred.
If I extract the data and run Preview it works.

**Comment by sakama** [comment]
Why don't you increase the value of `preview_sample_buffer_bytes`?
```
exec:
  preview_sample_buffer_bytes: 65536 # 64KB
```
https://www.embulk.org/docs/built-in.html#preview-executor

Embulk preview tries to read 32KB as a default. I suppose your data exceeded this limitation.
