### ISSUE TITLE
embulk gem install -l option behavior in 0.8.39 and 0.9.18

### ISSUE THREAD

**Issue by hiroyuki-sato** [embulk/embulk#1177]
Just sharing my knowledge for future support.
I found the difference `embulk gem -l` behavior in 0.8.39 and 0.9.18

I'll close this in a few days.

### 0.8.39

```	
% gem install -l embulk-output-bigquery-0.6.0.gem
2019-08-27 22:02:17.523 +0900: Embulk v0.8.39

********************************** INFORMATION **********************************
  Join us! Embulk-announce mailing list is up for IMPORTANT annoucement such as
    compatibility-breaking changes and key feature updates.
  https://groups.google.com/forum/#!forum/embulk-announce
*********************************************************************************


Gem plugin path is: /Users/user/.embulk/jruby/2.3.0

Successfully installed embulk-output-bigquery-0.6.0
1 gem installed	
```

### 0.9.18

```
embulk --version
embulk 0.9.18

embulk gem install -l embulk-output-bigquery-0.6.0.gem
Exception in thread "main" java.lang.IllegalArgumentException: Log level embulk-output-bigquery-0.6.0.gem is invalid. Available levels are error, warn, info, debug and trace.
	at org.embulk.cli.CliLogbackConfigurator.chooseLevel(CliLogbackConfigurator.java:150)
	at org.embulk.cli.CliLogbackConfigurator.configureLogger(CliLogbackConfigurator.java:115)
	at org.embulk.cli.CliLogbackConfigurator.configure(CliLogbackConfigurator.java:24)
	at org.embulk.cli.Main.main(Main.java:59)
```	

### Workaround

Use long option

```
embulk gem install --local embulk-output-bigquery-0.6.0.gem
```

### Environment

* OS: macOS 10.14.5
* Java: 1.8.0_192
* Embulk 0.8.39 and 0.9.18

**Comment by dmikurube** [comment]
Ah, `-l` might be consumed by Embulk, not passed to `gem`. It's considered to be a bug.

**Comment by hiroyuki-sato** [comment]
Thanks! I'll keep this issue as open.
