### ISSUE TITLE
Error: InputPlugin 'snowflake' is not found.

### ISSUE THREAD

**Issue by hhmahmood** [embulk/embulk#1209]
I am using snowflake-jdbc-3.8.0.jar driver and embulk-input-jdbc to pull data from snowflake. Its totally working fine as an output but when I use it as an input I gets the following error.

```
`org.embulk.config.ConfigException: InputPlugin 'snowflake' is not found.
org.jruby.proxy.org.embulk.config.ConfigException$Proxy1: Unknown input plugin 'snowflake'. embulk/input/snowflake.rb is not installed. Run 'embulk gem search -rd embulk-input' command to find plugins.
	at org.embulk.plugin.PluginManager.buildPluginNotFoundException(PluginManager.java:75)
	at org.embulk.plugin.PluginManager.newPluginWithoutWrapper(PluginManager.java:61)
	at org.embulk.plugin.PluginManager.newPlugin(PluginManager.java:28)
	at org.embulk.spi.ExecSession.newPlugin(ExecSession.java:162)
	at org.embulk.spi.Exec.newPlugin(Exec.java:67)
	at org.embulk.exec.BulkLoader$ProcessPluginSet.<init>(BulkLoader.java:427)
	at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:502)
	at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:35)
	at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:353)
	at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:350)
	at org.embulk.spi.Exec.doWith(Exec.java:22)
	at org.embulk.exec.BulkLoader.run(BulkLoader.java:350)
	at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:205)
	at org.embulk.EmbulkRunner.runInternal(EmbulkRunner.java:292)
	at org.embulk.EmbulkRunner.run(EmbulkRunner.java:156)
	at org.embulk.cli.EmbulkRun.runSubcommand(EmbulkRun.java:433)
	at org.embulk.cli.EmbulkRun.run(EmbulkRun.java:90)
	at org.embulk.cli.Main.main(Main.java:64)
	Suppressed: org.embulk.plugin.PluginSourceNotMatchException
		at org.embulk.plugin.InjectedPluginSource.newPlugin(InjectedPluginSource.java:53)
		at org.embulk.plugin.PluginManager.newPluginWithoutWrapper(PluginManager.java:49)
		... 16 more
	Suppressed: org.embulk.plugin.PluginSourceNotMatchException
		at org.embulk.plugin.maven.MavenPluginSource.newPlugin(MavenPluginSource.java:68)
		at org.embulk.plugin.PluginManager.newPluginWithoutWrapper(PluginManager.java:49)
		... 16 more
	Suppressed: org.embulk.plugin.PluginSourceNotMatchException: org.jruby.embed.InvokeFailedException: org.jruby.proxy.org.embulk.config.ConfigException$Proxy1: Unknown input plugin 'snowflake'. embulk/input/snowflake.rb is not installed. Run 'embulk gem search -rd embulk-input' command to find plugins.
		at org.embulk.jruby.JRubyPluginSource.newPlugin(JRubyPluginSource.java:63)
		at org.embulk.plugin.PluginManager.newPluginWithoutWrapper(PluginManager.java:56)
		... 16 more
	Caused by: org.jruby.embed.InvokeFailedException: org.jruby.proxy.org.embulk.config.ConfigException$Proxy1: Unknown input plugin 'snowflake'. embulk/input/snowflake.rb is not installed. Run 'embulk gem search -rd embulk-input' command to find plugins.
		at org.jruby.embed.internal.EmbedRubyObjectAdapterImpl.call(EmbedRubyObjectAdapterImpl.java:322)
		at org.jruby.embed.internal.EmbedRubyObjectAdapterImpl.callMethod(EmbedRubyObjectAdapterImpl.java:159)
		at org.jruby.embed.ScriptingContainer.callMethod(ScriptingContainer.java:1459)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.embulk.jruby.ScriptingContainerDelegateImpl.callMethod(ScriptingContainerDelegateImpl.java:634)
		at org.embulk.jruby.LazyScriptingContainerDelegate.callMethod(LazyScriptingContainerDelegate.java:129)
		at org.embulk.jruby.JRubyPluginSource.newPlugin(JRubyPluginSource.java:61)
		... 17 more
	Caused by: org.jruby.proxy.org.embulk.config.ConfigException$Proxy1: Unknown input plugin 'snowflake'. embulk/input/snowflake.rb is not installed. Run 'embulk gem search -rd embulk-input' command to find plugins.
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
		at org.jruby.javasupport.proxy.JavaProxyConstructor.newInstanceImpl(JavaProxyConstructor.java:119)
		at org.jruby.javasupport.proxy.JavaProxyConstructor.newInstance(JavaProxyConstructor.java:205)
		at org.jruby.javasupport.Java$JCreateMethod.call(Java.java:618)
		at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
		at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:739)
		at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:278)
		at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:79)
		at org.jruby.java.proxies.ConcreteJavaProxy$InitializeMethod.call(ConcreteJavaProxy.java:48)
		at org.jruby.ir.runtime.IRRuntimeHelpers.instanceSuper(IRRuntimeHelpers.java:984)
		at org.jruby.ir.instructions.InstanceSuperInstr.interpret(InstanceSuperInstr.java:69)
		at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:360)
		at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:74)
		at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
		at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)
		at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)
		at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:328)
		at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:165)
		at org.jruby.RubyClass.newInstance(RubyClass.java:1001)
		at org.jruby.RubyClass$INVOKER$i$newInstance.call(RubyClass$INVOKER$i$newInstance.gen)
		at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
		at org.jruby.java.proxies.ConcreteJavaProxy$NewMethod.call(ConcreteJavaProxy.java:158)
		at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:318)
		at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:155)
		at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
		at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:74)
		at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
		at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)
		at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)
		at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
		at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:318)
		at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:155)
		at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
		at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:74)
		at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:90)
		at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:214)
		at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:200)
		at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:208)
		at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)
		at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:183)
		at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:324)
		at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:74)
		at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:109)
		at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:95)
		at org.jruby.RubyClass.finvoke(RubyClass.java:522)
		at org.jruby.RubyBasicObject.send19(RubyBasicObject.java:1684)
		at org.jruby.RubyBasicObject$INVOKER$i$send19.call(RubyBasicObject$INVOKER$i$send19.gen)
		at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:278)
		at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:79)
		at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:432)
		at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:360)
		at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:74)
		at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:109)
		at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:95)
		at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:174)
		at org.jruby.RubyClass.finvoke(RubyClass.java:899)
		at org.jruby.runtime.Helpers.invoke(Helpers.java:430)
		at org.jruby.embed.internal.EmbedRubyObjectAdapterImpl.callEachType(EmbedRubyObjectAdapterImpl.java:356)
		at org.jruby.embed.internal.EmbedRubyObjectAdapterImpl.call(EmbedRubyObjectAdapterImpl.java:309)
		... 26 more

Error: InputPlugin 'snowflake' is not found.
org.jruby.proxy.org.embulk.config.ConfigException$Proxy1: Unknown input plugin 'snowflake'. embulk/input/snowflake.rb is not installed. Run 'embulk gem search -rd embulk-input' command to find plugins.
Traceback (most recent call last):
  File "/Users/h.mahmood/Repositories/dwh-raw-loader/airflow/scripts/dwh_raw_loader/load_snowflake_to_vertica.py", line 146, in <module>
    vertica_to_snowflake(**vars(args))
  File "/Users/h.mahmood/Repositories/dwh-raw-loader/airflow/scripts/dwh_raw_loader/load_snowflake_to_vertica.py", line 23, in vertica_to_snowflake
    embulk.run(job_cfg, job_id, runner_mode=runner)
  File "/Users/h.mahmood/Repositories/dwh-raw-loader/airflow/scripts/dwh_raw_loader/embulk.py", line 216, in run
    task_id = start_task(job_cfg, job_id, runner_mode)
  File "/Users/h.mahmood/Repositories/dwh-raw-loader/airflow/scripts/dwh_raw_loader/embulk.py", line 193, in start_task
    task_id = run_on_local(job_cfg, job_id, **runner_params)
  File "/Users/h.mahmood/Repositories/dwh-raw-loader/airflow/scripts/dwh_raw_loader/embulk.py", line 170, in run_on_local
    raise RuntimeError('Embulk process failed')
RuntimeError: Embulk process failed

Process finished with exit code 1
` 
```
Snowflake input plugin for embulk is not available yet. I don't know what I am doing wrong as it should work as an input if its working as an output using the combination of snowflake-jdbc driver and embulk-input-jdbc.

Help would be really appreciated.

**Comment by hiroyuki-sato** [comment]
Hello, @hhmahmood 

You need to read this notification carefully before writing your question.
For example

* Do not file a request like "support a new input/output/filter" here.
  * That's not for here.
  * Embulk is plugin-based. Such inputs/outputs/filters are to be implemented as plugins, not in the core.
  * It is recommended for you to search for existing plugins at first.
    * See: http://www.embulk.org/plugins/
  * If you cannot find existing plugins, it's a good chance for you to create a new plugin by yourself. :)

Probably, you need to change input type, use `jdbc` instead of `snowflake`.
https://github.com/embulk/embulk-input-jdbc/tree/master/embulk-input-jdbc#example

If you need to ask about `embulk-input-jdbc`, file a new issue on [`embulk-input-jdbc`](https://github.com/embulk/embulk-input-jdbc)
You need to write your configuration and environment with your question.

**Comment by hhmahmood** [comment]
@hiroyuki-sato thank you very much, it worked by setting `jdbc` instead of `snowflake`
