### ISSUE TITLE
Sometime error: output plugin bigquery not found

### ISSUE THREAD

**Issue by dungdt2** [embulk/embulk#1214]
Sometime, when I run 1 embulk command,  our system has error: Error: OutputPlugin 'bigquery' is not found, but when I re-try this command, every thing is ok.
I'm absolutely sure that this plugin has installed.

System Information
--------------------------------

* AWS EC2
* Embulk lastest version
* Java 8

Issue Type: Bug Report
-----------------------
3.
LoadError: load error: openssl/pkcs12 -- java.lang.NullPointerException: Inflater has been closed
  require at org/jruby/RubyKernel.java:955
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
   <main> at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:41
  require at org/jruby/RubyKernel.java:955
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
   <main> at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/openssl.rb:1
  require at org/jruby/RubyKernel.java:955
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
   <main> at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/openssl.rb:1
  require at org/jruby/RubyKernel.java:955
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
   <main> at /home/production/.embulk/lib/gems/gems/jwt-2.2.1/lib/jwt/signature.rb:1
  require at org/jruby/RubyKernel.java:955
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
   <main> at /home/production/.embulk/lib/gems/gems/jwt-2.2.1/lib/jwt/signature.rb:4
  require at org/jruby/RubyKernel.java:955
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
   <main> at /home/production/.embulk/lib/gems/gems/jwt-2.2.1/lib/jwt/decode.rb:1
  require at org/jruby/RubyKernel.java:955
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
   <main> at /home/production/.embulk/lib/gems/gems/jwt-2.2.1/lib/jwt/decode.rb:5
  require at org/jruby/RubyKernel.java:955
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
   <main> at /home/production/.embulk/lib/gems/gems/jwt-2.2.1/lib/jwt.rb:1
  require at org/jruby/RubyKernel.java:955
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
   <main> at /home/production/.embulk/lib/gems/gems/jwt-2.2.1/lib/jwt.rb:5
  require at org/jruby/RubyKernel.java:955
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
   <main> at /home/production/.embulk/lib/gems/gems/signet-0.11.0/lib/signet/oauth_2/client.rb:1
  require at org/jruby/RubyKernel.java:955
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
   <main> at /home/production/.embulk/lib/gems/gems/signet-0.11.0/lib/signet/oauth_2/client.rb:21
  require at org/jruby/RubyKernel.java:955
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
   <main> at /home/production/.embulk/lib/gems/gems/googleauth-0.9.0/lib/googleauth/signet.rb:1
  require at org/jruby/RubyKernel.java:955
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
   <main> at /home/production/.embulk/lib/gems/gems/googleauth-0.9.0/lib/googleauth/signet.rb:30
  require at org/jruby/RubyKernel.java:955
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55
   <main> at /home/production/.embulk/lib/gems/gems/googleauth-0.9.0/lib/googleauth/compute_engine.rb:1
  require at org/jruby/RubyKernel.java:955
   (root) at /home/production/.embulk/lib/gems/gems/googleauth-0.9.0/lib/googleauth/compute_engine.rb:31
   <main> at /home/production/.embulk/lib/gems/gems/googleauth-0.9.0/lib/googleauth/application_default.rb:1
  require at org/jruby/RubyKernel.java:955
  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:133
   (root) at /home/production/.embulk/lib/gems/gems/googleauth-0.9.0/lib/googleauth/application_default.rb:30
   (root) at /home/production/.embulk/lib/gems/gems/googleauth-0.9.0/lib/googleauth.rb:1
   (root) at /home/production/.embulk/lib/gems/gems/googleauth-0.9.0/lib/googleauth.rb:30
   (root) at /home/production/.embulk/lib/gems/gems/google-api-client-0.32.1/lib/google/apis/core/base_service.rb:1
   (root) at /home/production/.embulk/lib/gems/gems/google-api-client-0.32.1/lib/google/apis/core/base_service.rb:23
   (root) at /home/production/.embulk/lib/gems/gems/google-api-client-0.32.1/generated/google/apis/bigquery_v2/service.rb:1
org.embulk.config.ConfigException: OutputPlugin 'bigquery' is not found.
(LoadError) load error: openssl/pkcs12 -- java.lang.NullPointerException: Inflater has been closed
        at org.embulk.plugin.PluginManager.buildPluginNotFoundException(PluginManager.java:75)
        at org.embulk.plugin.PluginManager.newPluginWithoutWrapper(PluginManager.java:61)
        at org.embulk.plugin.PluginManager.newPlugin(PluginManager.java:28)
        at org.embulk.spi.ExecSession.newPlugin(ExecSession.java:162)
        at org.embulk.spi.Exec.newPlugin(Exec.java:67)
        at org.embulk.exec.BulkLoader$ProcessPluginSet.<init>(BulkLoader.java:428)
        at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:502)
        at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:35)
        at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:353)
        at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:350)
        at org.embulk.spi.Exec.doWith(Exec.java:22)
        at org.embulk.exec.BulkLoader.run(BulkLoader.java:350)
        at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:205)
        at org.embulk.EmbulkRunner.runInternal(EmbulkRunner.java:292)
        at org.embulk.EmbulkRunner.run(EmbulkRunner.java:156)
        at org.embulk.cli.EmbulkRun.runSubcommand(EmbulkRun.java:433)
        at org.embulk.cli.EmbulkRun.run(EmbulkRun.java:90)
        at org.embulk.cli.Main.main(Main.java:64)
        Suppressed: org.embulk.plugin.PluginSourceNotMatchException
                at org.embulk.plugin.InjectedPluginSource.newPlugin(InjectedPluginSource.java:53)
                at org.embulk.plugin.PluginManager.newPluginWithoutWrapper(PluginManager.java:49)
                ... 16 more
        Suppressed: org.embulk.plugin.PluginSourceNotMatchException
                at org.embulk.plugin.maven.MavenPluginSource.newPlugin(MavenPluginSource.java:68)
                at org.embulk.plugin.PluginManager.newPluginWithoutWrapper(PluginManager.java:49)
                ... 16 more
        Suppressed: org.embulk.plugin.PluginSourceNotMatchException: org.jruby.embed.InvokeFailedException: (LoadError) load error: openssl/pkcs12 -- java.lang.NullPointerException: Inflater has been closed
                at org.embulk.jruby.JRubyPluginSource.newPlugin(JRubyPluginSource.java:63)
                at org.embulk.plugin.PluginManager.newPluginWithoutWrapper(PluginManager.java:56)
                ... 16 more
        Caused by: org.jruby.embed.InvokeFailedException: (LoadError) load error: openssl/pkcs12 -- java.lang.NullPointerException: Inflater has been closed
                at org.jruby.embed.internal.EmbedRubyObjectAdapterImpl.call(EmbedRubyObjectAdapterImpl.java:320)
                at org.jruby.embed.internal.EmbedRubyObjectAdapterImpl.callMethod(EmbedRubyObjectAdapterImpl.java:159)
                at org.jruby.embed.ScriptingContainer.callMethod(ScriptingContainer.java:1459)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at org.embulk.jruby.ScriptingContainerDelegateImpl.callMethod(ScriptingContainerDelegateImpl.java:634)
                at org.embulk.jruby.LazyScriptingContainerDelegate.callMethod(LazyScriptingContainerDelegate.java:129)
                at org.embulk.jruby.JRubyPluginSource.newPlugin(JRubyPluginSource.java:61)
                ... 17 more
        Caused by: org.jruby.exceptions.RaiseException: (LoadError) load error: openssl/pkcs12 -- java.lang.NullPointerException: Inflater has been closed
                at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:955)
                at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.rubygems.core_ext.kernel_require.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55)
                at RUBY.<main>(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/jopenssl/load.rb:41)
                at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:955)
                at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.rubygems.core_ext.kernel_require.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55)
                at RUBY.<main>(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/openssl.rb:1)
                at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:955)
                at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.rubygems.core_ext.kernel_require.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55)
                at RUBY.<main>(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/openssl.rb:1)
                at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:955)
                at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.rubygems.core_ext.kernel_require.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55)
                at RUBY.<main>(/home/production/.embulk/lib/gems/gems/jwt-2.2.1/lib/jwt/signature.rb:1)
                at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:955)
                at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.rubygems.core_ext.kernel_require.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55)
                at RUBY.<main>(/home/production/.embulk/lib/gems/gems/jwt-2.2.1/lib/jwt/signature.rb:4)
                at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:955)
                at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.rubygems.core_ext.kernel_require.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55)
                at RUBY.<main>(/home/production/.embulk/lib/gems/gems/jwt-2.2.1/lib/jwt/decode.rb:1)
                at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:955)
                at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.rubygems.core_ext.kernel_require.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55)
                at RUBY.<main>(/home/production/.embulk/lib/gems/gems/jwt-2.2.1/lib/jwt/decode.rb:5)
                at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:955)
                at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.rubygems.core_ext.kernel_require.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55)
                at RUBY.<main>(/home/production/.embulk/lib/gems/gems/jwt-2.2.1/lib/jwt.rb:1)
                at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:955)
                at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.rubygems.core_ext.kernel_require.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55)
                at RUBY.<main>(/home/production/.embulk/lib/gems/gems/jwt-2.2.1/lib/jwt.rb:5)
                at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:955)
                at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.rubygems.core_ext.kernel_require.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55)
                at RUBY.<main>(/home/production/.embulk/lib/gems/gems/signet-0.11.0/lib/signet/oauth_2/client.rb:1)
                at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:955)
                at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.rubygems.core_ext.kernel_require.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55)
                at RUBY.<main>(/home/production/.embulk/lib/gems/gems/signet-0.11.0/lib/signet/oauth_2/client.rb:21)
                at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:955)
                at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.rubygems.core_ext.kernel_require.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55)
                at RUBY.<main>(/home/production/.embulk/lib/gems/gems/googleauth-0.9.0/lib/googleauth/signet.rb:1)
                at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:955)
                at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.rubygems.core_ext.kernel_require.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55)
                at RUBY.<main>(/home/production/.embulk/lib/gems/gems/googleauth-0.9.0/lib/googleauth/signet.rb:30)
                at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:955)
                at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.rubygems.core_ext.kernel_require.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55)
                at RUBY.<main>(/home/production/.embulk/lib/gems/gems/googleauth-0.9.0/lib/googleauth/compute_engine.rb:1)
                at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:955)
                at RUBY.(root)(/home/production/.embulk/lib/gems/gems/googleauth-0.9.0/lib/googleauth/compute_engine.rb:31)
                at RUBY.<main>(/home/production/.embulk/lib/gems/gems/googleauth-0.9.0/lib/googleauth/application_default.rb:1)
                at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:955)
                at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.rubygems.core_ext.kernel_require.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:133)
                at RUBY.(root)(/home/production/.embulk/lib/gems/gems/googleauth-0.9.0/lib/googleauth/application_default.rb:30)
                at RUBY.(root)(/home/production/.embulk/lib/gems/gems/googleauth-0.9.0/lib/googleauth.rb:1)
                at RUBY.(root)(/home/production/.embulk/lib/gems/gems/googleauth-0.9.0/lib/googleauth.rb:30)
                at RUBY.(root)(/home/production/.embulk/lib/gems/gems/google-api-client-0.32.1/lib/google/apis/core/base_service.rb:1)
                at RUBY.(root)(/home/production/.embulk/lib/gems/gems/google-api-client-0.32.1/lib/google/apis/core/base_service.rb:23)
                at RUBY.(root)(/home/production/.embulk/lib/gems/gems/google-api-client-0.32.1/generated/google/apis/bigquery_v2/service.rb:1)

Error: OutputPlugin 'bigquery' is not found.
(LoadError) load error: openssl/pkcs12 -- java.lang.NullPointerException: Inflater has been closed

load error: org/yaml/snakeyaml/1.18/snakeyaml-1.18 -- java.lang.NullPointerException: Inflater has been closed (LoadError)

**Comment by hiroyuki-sato** [comment]
Hello, @dungdt2 

It seems that this issue similar to #1148
What OS do you use on ECS2?
Could you tell us your Embulk and Java version? (ex. 0.9.22)

I've never heard a similar issue in the AWS environment yet.

**Comment by dungdt2** [comment]
> Hello, @dungdt2
> 
> It seems that this issue similar to #1148
> What OS do you use on ECS2?
> Could you tell us your Embulk and Java version? (ex. 0.9.22)
> 
> I've never heard a similar issue in the AWS environment yet.
@hiroyuki-sato , 
Thanks for your reply.
In my system, Embulk version: 0.9.21
Java version: 
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
 OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)

**Comment by hiroyuki-sato** [comment]
Hello, @dungdt2 

Thank you for your reply.
I don't know how to reproduce it. So, I don't know the root cause yet.
Please let me know if you find any information about the reproducing step.

By the way, Can you quote [stack trace](https://github.com/embulk/embulk/issues/1214#issue-538251013) using [Quoting code](https://help.github.com/en/github/writing-on-github/basic-writing-and-formatting-syntax#quoting-code) style?

**Comment by hiroyuki-sato** [comment]
Recently, I received similar reports.
I'm not sure whether the root cause is the same or not.

I requested to install the latest `jruby-openssl` about the 2nd case.

* [case1](https://twitter.com/hiroysato/status/1237745198337150976?s=20)
* [case2](https://twitter.com/hiroysato/status/1246026896585789441?s=20)
