### ISSUE TITLE
"LEAK: ByteBuf.release() was not called before it's garbage-collected." solved by changing src code

### ISSUE THREAD

**Issue by inggilove** [embulk/embulk#1218]
"LEAK: ByteBuf.release() was not called before it's garbage-collected." is shown
on every trial of elasticsearch output.
Even if change the output 'null', the result is same.
After about 5 million data has inserted, embulk stop and killed. ( Out of memory )

Issue Type: Bug Report
-----------------------
  * OS version : CentOS Linux release 7.7.1908 (Core)
  * Java version : openjdk version "1.8.0_232"
  * Embulk version : Embulk v0.9.22
  * Your Embulk configuration (YAML) : config.yml
```
in:
  type: file
  path_prefix: /data/201912
 decoders:
 - {type: gzip}
  parser:
    default_timezone: 'Asia/Seoul'
    charset: UTF-8
    newline: CRLF
    type: csv
    delimiter: ','
    quote: '"'
    escape: '"'
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: createdat, type: timestamp, format: '%Y-%m-%d %H:%M:%S.%N %z'}
    - {name: url, type: string}
    - {name: referer, type: string}
    - {name: useragent, type: string}
out:
  type: elasticsearch
  index: t_201912
  index_type: _doc
  bulk_actions: 100
  nodes:
  - {host: 1.1.1.1, port: 9200}
```

  * Plugin versions : 
           embulk-input-postgresql (0.10.1)
           embulk-output-command (0.1.4)
           embulk-output-elasticsearch (0.4.7)
* Write all what you did, e.g. your commands executed
            $ embulk -J-Dio.netty.leakDetection.level=advanced run config.yml

* Log
`
2020-01-07 10:51:56.343 +0900 [ERROR] (0025:task-0002): LEAK: ByteBuf.release() was not called before it's garbage-collected. See http://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 0
Created at:
        io.netty.util.ResourceLeakDetector.track(ResourceLeakDetector.java:229)
        io.netty.buffer.PooledByteBufAllocator.newHeapBuffer(PooledByteBufAllocator.java:286)
        io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:158)
        io.netty.buffer.AbstractByteBufAllocator.heapBuffer(AbstractByteBufAllocator.java:149)
        io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:107)
        org.embulk.deps.buffer.PooledBufferAllocatorImpl.allocate(PooledBufferAllocatorImpl.java:26)
        org.embulk.spi.PageBuilder.newBuffer(PageBuilder.java:46)
        org.embulk.spi.PageBuilder.flush(PageBuilder.java:221)
        org.embulk.spi.PageBuilder.addRecord(PageBuilder.java:198)
        org.embulk.standards.CsvParserPlugin.run(CsvParserPlugin.java:368)
        org.embulk.spi.FileInputRunner.run(FileInputRunner.java:140)
        org.embulk.spi.util.Executors.process(Executors.java:62)
        org.embulk.spi.util.Executors.process(Executors.java:38)
        org.embulk.exec.LocalExecutorPlugin$DirectExecutor$1.call(LocalExecutorPlugin.java:170)
        org.embulk.exec.LocalExecutorPlugin$DirectExecutor$1.call(LocalExecutorPlugin.java:167)
        java.util.concurrent.FutureTask.run(FutureTask.java:266)
        java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        java.lang.Thread.run(Thread.java:748)
`

**Comment by hiroyuki-sato** [comment]
Hello, @inggilove 

Have you ever tried the following JVM option? I suppose this option militates your issue.

I can't know how to reproduce `LEAK: ByteBuf.release()`(Another user also reports it too. ex. #516) yet. But I think that error doesn't stop embulk immediately.

```
embulk -J-Xmx5g run config.yml
```

**Comment by inggilove** [comment]
Thanks, 
I tried your recommended options ( -Xmx5g ), but failed.
because the size of data is bigger, the memory leak was accumulated slowly and embulk stopped with OutOfMemory before the end .
Maybe it could success if I increase the bigger and bigger size ( 5g > 20g ?? )
But the data grows bigger (12 million ~ 1 billion ), I want to remove the leak..

**Comment by inggilove** [comment]
I found the solution in this case.

In case of csv input and elasticsearch output,
memory leak can be handled in some change of PageBuilder.java.

src/main/java/org/embulk/spi/PageBuilder.java
private void doFlush() {
  if (buffer != null && count > 0) {
     ...
     buffer.release(); // added.
     buffer = null;
     ....
  }

But, side effect..
in another case of postgresql input and elasticsearch output,
it cannot be hadled and another error as below...
Where can be the best position of netty buffer release() ? .. 

```
org.embulk.deps.buffer.PooledBufferAllocatorImpl$BufferDoubleReleasedException: A Buffer detected double release() calls. The buffer has already been released at:
        at org.embulk.deps.buffer.PooledBufferAllocatorImpl$BufferBasedOnNettyByteBuf.release(PooledBufferAllocatorImpl.java:41)
        at org.embulk.spi.Page.release(Page.java:68)
        at org.embulk.exec.LocalExecutorPlugin$ScatterTransactionalPageOutput$OutputWorker.add(LocalExecutorPlugin.java:325)
        at org.embulk.exec.LocalExecutorPlugin$ScatterTransactionalPageOutput.add(LocalExecutorPlugin.java:433)
        at org.embulk.spi.PageBuilder.doFlush(PageBuilder.java:223)
        at org.embulk.spi.PageBuilder.flush(PageBuilder.java:228)
        at org.embulk.spi.PageBuilder.addRecord(PageBuilder.java:200)
        at org.embulk.input.jdbc.AbstractJdbcInputPlugin.fetch(AbstractJdbcInputPlugin.java:602)
        at org.embulk.input.jdbc.AbstractJdbcInputPlugin.run(AbstractJdbcInputPlugin.java:497)
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.runInputTask(LocalExecutorPlugin.java:269)
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.access$100(LocalExecutorPlugin.java:194)
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor$1.call(LocalExecutorPlugin.java:233)
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor$1.call(LocalExecutorPlugin.java:230)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.Throwable
        at org.embulk.deps.buffer.PooledBufferAllocatorImpl$BufferBasedOnNettyByteBuf.release(PooledBufferAllocatorImpl.java:46)
        at org.embulk.spi.PageBuilder.doFlush(PageBuilder.java:217)
        ... 12 more
```

**Comment by dmikurube** [comment]
Thanks for filing the issue and investigating, @inggilove.

Yeah, it has been a long-lived problem, but we couldn't have solved it because:
* We haven't had any reproduction. (We received some reports, but we're not seeing this in our environments constantly.)
* It looks depending on plugins as you found.

The problem looks to be lying on an (implicit) contract between the core and the plugins. Sorry that we're still not sure what is the best resolution.

**Comment by dmikurube** [comment]
Once we have concrete steps to reproduce it easily and constantly, it helps us to fix it sooner. Setting up any new server is not very easy, though.

If you have such steps to reproduce, please let us know!

**Comment by inggilove** [comment]
Hmm, 
I tried to reproduce it with the small sample data, 
but the case of either csv or postgresql to elasticsearch doesn't show the LEAK,

Over about 20,000 rows, LEAK is shown. ( 8gb 4 core VM server and embulk default JVM option )

**Comment by hiroyuki-sato** [comment]
Hello, @inggilove 

Thank you for investigating this issue.
Does your 20,000 data, *always*  show LEAK message?
If so, I can try your data in my environment.

**Comment by shroman** [comment]
The problem could be in `embulk-input-jdbc`. https://github.com/embulk/embulk-input-jdbc/blob/master/embulk-input-jdbc/src/main/java/org/embulk/input/jdbc/AbstractJdbcInputPlugin.java#L510 only calls `finish()` that flushes but not releases the buffer. Can you please check? @inggilove 
@dmikurube WDYT?

**Comment by hiroyuki-sato** [comment]
@calorie made leak reproduce config [memory_leak.yml](https://github.com/calorie/embulk-repro/blob/main/embulk/memory_leak.yml) Thanks.
It requires five million data and elasticsearch output.

ref: [twitter](https://twitter.com/calorie001/status/1357229898742439938?s=20)

**Comment by case-k-git** [comment]
Hi
I have a question about this issue

I have got under the error when I try to transfer large amount of data (1.6 billion) from sqlserver to BigQuery. 

I am not sure if this error is related to this post but I found same error in this post as a side effect.
https://github.com/embulk/embulk/issues/1218#issuecomment-571446610

 so  I  am just wandering if under the error is related this issue . 
is this memory leak issue has already been solved? 

thank you

- OS version : Ubuntu 18.04.1

- Java version : 1.8.0_111

- Embulk version : Embulk v0.9.23

- Your Embulk configuration (YAML) : config.yml

```
in:
  type: sqlserver
  host: {{env.DBBACKBORN_HOST}}
  port: {{env.DBBACKBORN_PORT}}
  user: {{env.DBBACKBORN_USER}}
  password: {{env.DBBACKBORN_PASSWORD}}
  database: {{env.DBBACKBORN_DATABASE}}
  query: |
    SELECT * FROM {{env.IMPORT_TABLE_NAME}} WITH(NOLOCK)
out:
  type: bigquery
  project: {{env.GCP_PROJECT_ID}}
  dataset: '{{env.DBBACKBORN_DATABASE}}'
  table: '{{env.IMPORT_TABLE_NAME}}'
  mode: replace
  auth_method: json_key
  json_keyfile:
    content: |
        {{ env.GCP_CREDENTIAL }}
  gcs_bucket: '{{env.GCP_BUCKET_NAME}}'
  auto_create_dataset: true
  with_rehearsal: false
  auto_create_gcs_bucket: false
  open_timeout_sec: 1800
  send_timeout_sec: 1800
  read_timeout_sec: 1800
  retries: 5
  compression: NONE
  source_format: NEWLINE_DELIMITED_JSON
  job_status_max_polling_time: 36000
  default_timezone: "Asia/Tokyo"
```
- Error Message

```
org.embulk.deps.buffer.PooledBufferAllocatorImpl$BufferDoubleReleasedException: A Buffer detected double release() calls. The buffer has already been released at:
	at org.embulk.deps.buffer.PooledBufferAllocatorImpl$BufferBasedOnNettyByteBuf.release(PooledBufferAllocatorImpl.java:40)
	at org.embulk.spi.Page.release(Page.java:68)
	at org.embulk.exec.LocalExecutorPlugin$ScatterTransactionalPageOutput$OutputWorker.call(LocalExecutorPlugin.java:360)
	at org.embulk.exec.LocalExecutorPlugin$ScatterTransactionalPageOutput$OutputWorker.call(LocalExecutorPlugin.java:291)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Throwable
	at org.embulk.deps.buffer.PooledBufferAllocatorImpl$BufferBasedOnNettyByteBuf.release(PooledBufferAllocatorImpl.java:45)
	at org.embulk.spi.PageReader.close(PageReader.java:151)
	at sun.reflect.GeneratedMethodAccessor32.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:438)
	at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:302)
	at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:36)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:125)
	at uri_3a_classloader_3a_.gems.embulk_minus_0_dot_9_dot_23_minus_java.lib.embulk.page.invokeOther7:close(uri:classloader:/gems/embulk-0.9.23-java/lib/embulk/page.rb:25)
	at uri_3a_classloader_3a_.gems.embulk_minus_0_dot_9_dot_23_minus_java.lib.embulk.page.RUBY$method$each$0(uri:classloader:/gems/embulk-0.9.23-java/lib/embulk/page.rb:25)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:90)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:128)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:135)
	at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:142)
	at var.lib.embulk.vendor.bundle.jruby.$2_dot_3_dot_0.gems.embulk_minus_output_minus_bigquery_minus_0_dot_6_dot_4.lib.embulk.output.bigquery.file_writer.invokeOther19:each(/var/lib/embulk/vendor/bundle/jruby/2.3.0/gems/embulk-output-bigquery-0.6.4/lib/embulk/output/bigquery/file_writer.rb:102)
	at var.lib.embulk.vendor.bundle.jruby.$2_dot_3_dot_0.gems.embulk_minus_output_minus_bigquery_minus_0_dot_6_dot_4.lib.embulk.output.bigquery.file_writer.RUBY$method$add$0(/var/lib/embulk/vendor/bundle/jruby/2.3.0/gems/embulk-output-bigquery-0.6.4/lib/embulk/output/bigquery/file_writer.rb:102)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:103)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:163)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:153)
	at var.lib.embulk.vendor.bundle.jruby.$2_dot_3_dot_0.gems.embulk_minus_output_minus_bigquery_minus_0_dot_6_dot_4.lib.embulk.output.bigquery.invokeOther4:add(/var/lib/embulk/vendor/bundle/jruby/2.3.0/gems/embulk-output-bigquery-0.6.4/lib/embulk/output/bigquery.rb:477)
	at var.lib.embulk.vendor.bundle.jruby.$2_dot_3_dot_0.gems.embulk_minus_output_minus_bigquery_minus_0_dot_6_dot_4.lib.embulk.output.bigquery.RUBY$method$add$0(/var/lib/embulk/vendor/bundle/jruby/2.3.0/gems/embulk-output-bigquery-0.6.4/lib/embulk/output/bigquery.rb:477)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:103)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:163)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:200)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:153)
	at uri_3a_classloader_3a_.gems.embulk_minus_0_dot_9_dot_23_minus_java.lib.embulk.output_plugin.invokeOther3:add(uri:classloader:/gems/embulk-0.9.23-java/lib/embulk/output_plugin.rb:114)
	at uri_3a_classloader_3a_.gems.embulk_minus_0_dot_9_dot_23_minus_java.lib.embulk.output_plugin.RUBY$method$add$0(uri:classloader:/gems/embulk-0.9.23-java/lib/embulk/output_plugin.rb:114)
	at uri_3a_classloader_3a_.gems.embulk_minus_0_dot_9_dot_23_minus_java.lib.embulk.output_plugin.RUBY$method$add$0$__VARARGS__(uri:classloader:/gems/embulk-0.9.23-java/lib/embulk/output_plugin.rb)
	at org.jruby.internal.runtime.methods.CompiledIRMethod.call(CompiledIRMethod.java:77)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:93)
	at Embulk$$OutputPlugin$$JavaAdapter$$OutputAdapter_331657608.add(Embulk$$OutputPlugin$$JavaAdapter$$OutputAdapter_331657608.gen:13)
	at org.embulk.exec.LocalExecutorPlugin$ScatterTransactionalPageOutput$OutputWorker.call(LocalExecutorPlugin.java:351)
```

**Comment by hiroyuki-sato** [comment]
Hello, @case-k-git 

Could you try 

```yaml
out: 
  type: "null"
```

It long term issue, but We can't reproduce in minimize environment.

**Comment by case-k-git** [comment]
@hiroyuki-sato 

Hi

Thank you for helping me in twitter.
https://twitter.com/csk_pos/status/1418400742801481729

Buffer detected double release()  has been solved by increasing enough storage capacity.
I have pasted error logs and how it solved 
https://github.com/embulk/embulk-output-bigquery/issues/138

thank you so much !
