### ISSUE TITLE
LocalFileInputPlugin can not access Windows short file name

### ISSUE THREAD

**Issue by hito4t** [embulk/embulk#1233]
Environment:
* Windows 7 (64bit)
* Java 8
* Embulk 0.9.20

When a windows file has a long name (ex. `long_long_name`), it also has a short name (ex. `LONG_L~1`)

If `path_prefix` in YAML is written in the short name style, `LocalFileInputPlugin` will throw `FileNotFoundException`.

<pre>
    Caused by: java.io.UncheckedIOException: java.io.FileNotFoundException: Directory not found: "C:\test\LONG_L~1" for "C:\test\LONG_L~1\sub"
      at org.embulk.standards.LocalFileInputPlugin.getRealCasePathOfDirectoryNoFollowLinks(LocalFileInputPlugin.java:389)
      at org.embulk.standards.LocalFileInputPlugin.listFiles(LocalFileInputPlugin.java:163)
      at org.embulk.standards.LocalFileInputPlugin.transaction(LocalFileInputPlugin.java:66)
      at org.embulk.spi.FileInputRunner.transaction(FileInputRunner.java:62)
      at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:507)
</pre>

I think it is usually no problem, but some tests needs a workaround because `TestingEmbulk#createTempFile` returns a path as the short name style.

**Comment by hito4t** [comment]
`Path#toRealPath` converts short file names to long file names.
