### ISSUE TITLE
ClassCastException occurs when copying a file from AWS S3 to bigquery

### ISSUE THREAD

**Issue by usrdev1** [embulk/embulk#1378]
Issue Type: Bug Report
-----------------------

* Write the following environmental information.
  * OS version: (Docker image)debian:9
  * Java version: openjdk version "1.8.0_275"
  * Embulk version: embulk 0.9.23
  * Your Embulk configuration (YAML):

  ```yaml
  in:
    type: s3
    bucket: XXX
    path_prefix: XXX.tsv
    access_key_id: 'XXX'
    secret_access_key: 'XXX'
    parser:
      charset: UTF-8
      newline: LF
      type: csv
      delimiter: '	'
      quote: '"'
      escape: '"'
      trim_if_not_quoted: false
      skip_header_lines: 1
      allow_extra_columns: false
      allow_optional_columns: false
      default_timezone: Asia/Tokyo
      columns:
      - {name: date, type: string} 
      - {name: property_id, type: long}
      - {name: property_name, type: string}

  out:
    type: bigquery
    mode: append
    auth_method: service_account
    json_keyfile: XXX
    project: XXX
    dataset: XXX
    location: asia-northeast1
    time_partitioning:
      type: DAY
      field: date
    table: XXX
    allow_quoted_newlines: 1
    column_options:
      - {name: date, type: DATE}
  ```

  * Plugin versions:
embulk-input-s3 (0.5.1 java)
embulk-output-bigquery (0.6.4)

* Write all what you did, e.g. your commands executed:
The job scheduler ran the below command:
> digdag run $WORKFLOW_FILENAME --rerun --params-file $PARAMETER_FILENAME

* Write what you expected and observed actually:
This workflow was running normally on a daily basis by the job scheduler,
however since 2021/1/21 it fails to run with the below error without any code change at our end.
Could you be able to check if this error would come from Embulk libraries
,and explain in detail what "DataSource specified is not org.embulk.config.DataSourceImpl." means and how to resolve it?

  ```
  java.lang.RuntimeException: java.lang.ClassCastException: DataSource specified is not org.embulk.config.DataSourceImpl.
    at org.embulk.EmbulkRunner.runInternal(EmbulkRunner.java:316)
    at org.embulk.EmbulkRunner.run(EmbulkRunner.java:155)
    at org.embulk.cli.EmbulkRun.runSubcommand(EmbulkRun.java:431)
    at org.embulk.cli.EmbulkRun.run(EmbulkRun.java:90)
    at org.embulk.cli.Main.main(Main.java:64)
  Caused by: java.lang.ClassCastException: DataSource specified is not org.embulk.config.DataSourceImpl.
    at org.embulk.util.config.Compat.callGetObjectNodeAndRebuildIfAvailable(Compat.java:136)
    at org.embulk.util.config.Compat.rebuildObjectNode(Compat.java:94)
    at org.embulk.util.config.TaskMapper.map(TaskMapper.java:73)
    at org.embulk.input.s3.AbstractS3FileInputPlugin.resume(AbstractS3FileInputPlugin.java:162)
    at org.embulk.input.s3.AbstractS3FileInputPlugin.transaction(AbstractS3FileInputPlugin.java:153)
    at org.embulk.spi.FileInputRunner.transaction(FileInputRunner.java:62)
    at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:507)
    at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:35)
    at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:353)
    at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:350)
    at org.embulk.spi.Exec.doWith(Exec.java:22)
    at org.embulk.exec.BulkLoader.run(BulkLoader.java:350)
    at org.embulk.EmbulkEmbed.runResumable(EmbulkEmbed.java:268)
    at org.embulk.EmbulkRunner.runInternal(EmbulkRunner.java:287)
    ... 4 more

  Error: java.lang.ClassCastException: DataSource specified is not org.embulk.config.DataSourceImpl.
  ```

**Comment by dmikurube** [comment]
I believe `embulk-input-s3:0.5.2` solved this problem.

Jfyi, it's nice if it would be reported for `embulk-input-s3` seeing the stacktrace.

**Comment by usrdev1** [comment]
Thanks for the prompt feedback!
Had a quick test with 0.5.2 and have confirmed that the error is gone 👍

_Success. Task state is saved at XXX_

**Comment by dmikurube** [comment]
Let me close this issue.
