### ISSUE TITLE
Expand the default sample_buffer_bytes (32KB)

### ISSUE THREAD

**Issue by momotarogrp** [embulk/embulk#1379]
Expand the default sample_buffer_bytes (32KB)

In recent years, the amount of data handled has increased along with the generalization of json, and it is not uncommon to handle entire contents.
There is no size limit in the json specification, and the entire content can sometimes be contained in a single String.
Therefore, if you operate without being aware of the existence of sample_buffer_bytes, errors will occur not because of the sample_buffer_bytes problem, but because of the analysis of half-finished data in the next analysis phase, and the investigation of the cause will sometimes be very difficult and cause confusion. This can be very difficult and confusing. (Just like me...)
So, I propose to change the default values as follows

  sample_buffer_bytes: 1048576
  guess_sample_buffer_bytes: 1048576
  preview_sample_buffer_bytes: 1048576

I think it's better to be too big and have problems with resource expansion than too small and not work.

I think guess needs some modes.
line: number of lines. (Maybe fix this issue: #471)

-------------
Error content (it is difficult to recognize the sample_buffer_bytes problem from the following)

Translated with www.DeepL.com/Translator (free version)
org.embulk.spi.DataException: Failed to parse JSON: -
        at org.embulk.standards.JsonParserPlugin.run(JsonParserPlugin.java:177)
        at org.embulk.spi.FileInputRunner.run(FileInputRunner.java:140)
        at org.embulk.exec.PreviewExecutor$2$1.run(PreviewExecutor.java:122)
        at org.embulk.spi.util.Filters$RecursiveControl.transaction(Filters.java:84)
        at org.embulk.exec.PreviewExecutor$2.run(PreviewExecutor.java:112)
        at org.embulk.spi.FileInputRunner$RunnerControl$1$1.run(FileInputRunner.java:112)
        at org.embulk.standards.JsonParserPlugin.transaction(JsonParserPlugin.java:102)
        at org.embulk.spi.FileInputRunner$RunnerControl$1.run(FileInputRunner.java:107)
        at org.embulk.spi.util.Decoders$RecursiveControl.transaction(Decoders.java:68)
        at org.embulk.spi.util.Decoders.transaction(Decoders.java:29)
        at org.embulk.spi.FileInputRunner$RunnerControl.run(FileInputRunner.java:105)
        at org.embulk.exec.BufferFileInputPlugin.transaction(BufferFileInputPlugin.java:21)
        at org.embulk.spi.FileInputRunner.transaction(FileInputRunner.java:62)
        at org.embulk.exec.PreviewExecutor.doPreview(PreviewExecutor.java:110)
        at org.embulk.exec.PreviewExecutor.doPreview(PreviewExecutor.java:96)
        at org.embulk.exec.PreviewExecutor.access$000(PreviewExecutor.java:28)
        at org.embulk.exec.PreviewExecutor$1.run(PreviewExecutor.java:65)
        at org.embulk.exec.PreviewExecutor$1.run(PreviewExecutor.java:62)
        at org.embulk.spi.Exec.doWith(Exec.java:22)
        at org.embulk.exec.PreviewExecutor.preview(PreviewExecutor.java:62)
        at org.embulk.EmbulkEmbed.preview(EmbulkEmbed.java:231)
        at org.embulk.EmbulkRunner.previewInternal(EmbulkRunner.java:214)
        at org.embulk.EmbulkRunner.preview(EmbulkRunner.java:106)
        at org.embulk.cli.EmbulkRun.runSubcommand(EmbulkRun.java:428)
        at org.embulk.cli.EmbulkRun.run(EmbulkRun.java:90)
        at org.embulk.cli.Main.main(Main.java:64)
Caused by: org.embulk.spi.json.JsonParseException: Failed to parse JSON: in
        at org.embulk.spi.json.JsonParser$AbstractParseContext.next(JsonParser.java:144)
        at org.embulk.standards.JsonParserPlugin.run(JsonParserPlugin.java:135)
        ... 26 more
Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected end-of-input in VALUE_STRING
 at [Source: org.embulk.spi.util.FileInputInputStream@62735b13; line: 47, column: 3728]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1581)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:533)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF(ParserMinimalBase.java:470)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF(ParserMinimalBase.java:466)
        at com.fasterxml.jackson.core.base.ParserBase.loadMoreGuaranteed(ParserBase.java:459)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishString2(UTF8StreamJsonParser.java:2434)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._finishAndReturnString(UTF8StreamJsonParser.java:2414)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.getText(UTF8StreamJsonParser.java:285)
        at org.embulk.spi.json.JsonParser$AbstractParseContext.jsonTokenToValue(JsonParser.java:172)
        at org.embulk.spi.json.JsonParser$AbstractParseContext.jsonTokenToValue(JsonParser.java:221)
        at org.embulk.spi.json.JsonParser$AbstractParseContext.jsonTokenToValue(JsonParser.java:186)
        at org.embulk.spi.json.JsonParser$AbstractParseContext.jsonTokenToValue(JsonParser.java:221)
        at org.embulk.spi.json.JsonParser$AbstractParseContext.next(JsonParser.java:142)
        ... 27 more

Error: Failed to parse JSON: -

**Comment by dmikurube** [comment]
Thanks for filing it as an issue. However, It is not an easy decision to increase its default value. Please let us have some time to consider about it.

For instance, if users are reading just a local file, incrasing the default value does ot have any serious impact. But for another example, some users read files from S3. AWS charges for a size of S3 read. Updating the default value can affect such users silently.

**Comment by dmikurube** [comment]
For another guess mode with number of lines, I have to say it's difficult by nature of Embulk's architecture. In Embulk, File Input Plugins just handle byte streams, and Parser Plugins take care of structures in the byte stream (including newlines). The defined plugin interface does not allow feedbacks from a Parser Plugin to a File Input Plugin. It's limitation, but Embulk has achieved its simplicity by the architecture and limitation.

We have received such a request some times so far, but it's a big change in the entire ecosysytem, not just a quick fix. We'll keep your proposal to be considered in next big updates (v2.0?), but please expect that it won't happen soon.

**Comment by dmikurube** [comment]
I thought that the situation could be relatively better with #1414, but as a problem's found, it's reverted in #1449.

We'll revisit this in the last minute during `v0.10.*.`
