### ISSUE TITLE
org.embulk.exec.PartialExecutionException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.eclipse.jetty.io.EofException

### ISSUE THREAD

**Issue by adrianovieira** [embulk/embulk#1455]
If your issue is not following the template, the maintainer may close the issue without notifications.

Issue Type: Bug Report
-----------------------

* Write the following environmental information.
  * OS version: fedora-34
  * Java version: 
     ```
     openjdk version "1.8.0_282"
     OpenJDK Runtime Environment (Zulu 8.52.0.23-CA-linux64) (build 1.8.0_282-b08)
     OpenJDK 64-Bit Server VM (Zulu 8.52.0.23-CA-linux64) (build 25.282-b08, mixed mode)
     ```
  * Embulk version: `Embulk v0.9.23`
  * Your Embulk configuration (YAML)
    ```yaml
    in:
      type: postgresql
      host: <IP>
      user: embulk
      password: s3cr3t-password
      database: migration
      table: test
      incremental: true
      incremental_columns: [year,month,day]
      last_record: [0,0,0]
    out:
      type: stdout

    filters:
      - type: column
        add_columns:
          - {name: '@timestamp', src: timestamp}
        drop_columns:
          - {name: timestamp}

    out:
      type: elasticsearch
      use_ssl: true
      auth_method: basic
      user: <user_name>
      password: <user_password>
      mode: insert
      nodes:
        - {host: elasticsearch-lab01.local, port: 9200}
      index: migration-tests-embulk-t10051826
      index_type: embulk
    ```
  * Plugin versions
* Write all what you did, e.g. your commands executed

```
curl -u elastic https://elasticsearch-lab01.local:9200/_cat/nodes/\?pretty
  
Enter host password for user 'elastic':
<IP1> 77 98 34 5.40 4.98 4.54 cdhilmrstw * elasticsearch-lab01.local
<IP2> 52 99 16 2.87 2.89 2.54 cdhilmrstw - elasticsearch-lab02.local
<IP3> 21 94 12 1.45 1.15 0.93 cdhilmrstw - elasticsearch-lab03.local
```

```
embulk run migration-tests.yml
```

* Write what you expected and observed actually

We expected to get all data injected on elasticsearch.

- observed actually:

```
2021-05-10 18:54:29.710 -0300 [INFO] (0001:transaction): SQL: SET search_path TO "public"
2021-05-10 18:54:29.723 -0300 [INFO] (0001:transaction): Using JDBC Driver PostgreSQL 9.4 JDBC4.1 (build 1205)
2021-05-10 18:54:29.795 -0300 [INFO] (0001:transaction): Using local thread executor with max_threads=16 / output tasks 8 = input tasks 1 * 8
2021-05-10 18:54:29.811 -0300 [INFO] (0001:transaction): Logging initialized @3625ms
org.embulk.exec.PartialExecutionException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.eclipse.jetty.io.EofException
	at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(BulkLoader.java:340)
	at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:566)
	at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:35)
	at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:353)
	at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:350)
	at org.embulk.spi.Exec.doWith(Exec.java:22)
	at org.embulk.exec.BulkLoader.run(BulkLoader.java:350)
	at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:242)
	at org.embulk.EmbulkRunner.runInternal(EmbulkRunner.java:291)
	at org.embulk.EmbulkRunner.run(EmbulkRunner.java:155)
	at org.embulk.cli.EmbulkRun.runSubcommand(EmbulkRun.java:431)
	at org.embulk.cli.EmbulkRun.run(EmbulkRun.java:90)
	at org.embulk.cli.Main.main(Main.java:64)
	Suppressed: java.lang.NullPointerException
		at org.embulk.exec.BulkLoader.doCleanup(BulkLoader.java:463)
		at org.embulk.exec.BulkLoader$3.run(BulkLoader.java:397)
		at org.embulk.exec.BulkLoader$3.run(BulkLoader.java:394)
		at org.embulk.spi.Exec.doWith(Exec.java:22)
		at org.embulk.exec.BulkLoader.cleanup(BulkLoader.java:394)
		at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:245)
		... 5 more
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.eclipse.jetty.io.EofException
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at org.embulk.util.retryhelper.jetty92.Jetty92RetryHelper.requestWithRetry(Jetty92RetryHelper.java:164)
	at org.embulk.output.elasticsearch.ElasticsearchHttpClient.sendRequest(ElasticsearchHttpClient.java:322)
	at org.embulk.output.elasticsearch.ElasticsearchHttpClient.sendRequest(ElasticsearchHttpClient.java:313)
	at org.embulk.output.elasticsearch.ElasticsearchHttpClient.getEsVersion(ElasticsearchHttpClient.java:166)
	at org.embulk.output.elasticsearch.ElasticsearchOutputPluginDelegate.validateOutputTask(ElasticsearchOutputPluginDelegate.java:208)
	at org.embulk.output.elasticsearch.ElasticsearchOutputPluginDelegate.validateOutputTask(ElasticsearchOutputPluginDelegate.java:28)
	at org.embulk.base.restclient.RestClientOutputPluginBaseUnsafe.transaction(RestClientOutputPluginBaseUnsafe.java:42)
	at org.embulk.base.restclient.RestClientOutputPluginBase.transaction(RestClientOutputPluginBase.java:56)
	at org.embulk.exec.BulkLoader$4$1$1.transaction(BulkLoader.java:521)
	at org.embulk.exec.LocalExecutorPlugin.transaction(LocalExecutorPlugin.java:50)
	at org.embulk.exec.BulkLoader$4$1.run(BulkLoader.java:516)
	at org.embulk.spi.util.Filters$RecursiveControl.transaction(Filters.java:84)
	at org.embulk.spi.util.Filters$RecursiveControl$1.run(Filters.java:80)
	at org.embulk.filter.column.ColumnFilterPlugin.transaction(ColumnFilterPlugin.java:81)
	at org.embulk.spi.util.Filters$RecursiveControl.transaction(Filters.java:76)
	at org.embulk.spi.util.Filters.transaction(Filters.java:42)
	at org.embulk.exec.BulkLoader$4.run(BulkLoader.java:511)
	at org.embulk.input.jdbc.AbstractJdbcInputPlugin.transaction(AbstractJdbcInputPlugin.java:224)
	at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:507)
	... 11 more
Caused by: java.util.concurrent.ExecutionException: org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.client.util.InputStreamResponseListener.get(InputStreamResponseListener.java:228)
	at org.embulk.util.retryhelper.jetty92.StringJetty92ResponseEntityReader.getResponse(StringJetty92ResponseEntityReader.java:31)
	at org.embulk.util.retryhelper.jetty92.Jetty92RetryHelper$1.call(Jetty92RetryHelper.java:107)
	at org.embulk.spi.util.RetryExecutor.run(RetryExecutor.java:81)
	at org.embulk.spi.util.RetryExecutor.runInterruptible(RetryExecutor.java:62)
	at org.embulk.util.retryhelper.jetty92.Jetty92RetryHelper.requestWithRetry(Jetty92RetryHelper.java:95)
	... 29 more
Caused by: org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:192)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.flush(SslConnection.java:765)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:408)
	at org.eclipse.jetty.io.WriteFlusher.completeWrite(WriteFlusher.java:364)
	at org.eclipse.jetty.io.ssl.SslConnection$1.run(SslConnection.java:97)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Pipe quebrado
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:470)
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:170)
	... 7 more

Error: java.lang.RuntimeException: java.util.concurrent.ExecutionException: org.eclipse.jetty.io.EofException
```

**Comment by dmikurube** [comment]
It seems like an error of the `elasticsearch` plugin. Please move there: https://github.com/embulk/embulk-output-elasticsearch/issues

(I know that plugin is not maintained very actively, but at least this is not the right place.)
