### ISSUE TITLE
Example test failure on macOS 13 with latest JDK 8

### ISSUE THREAD

**Issue by p-linnane** [embulk/embulk#1546]
Issue Type: Bug Report
-----------------------

* Write the following environmental information.
  * OS version: macOS 13 x86_64
  * Java version: openjdk@8 1.8.0+362
  * Embulk version: v.0.9.24
  * Your Embulk configuration (YAML): N/A
  * Plugin versions: N/A
* Write all what you did, e.g. your commands executed
  * Performing regression testing for the newest JDK 8 in Homebrew. embulk is the only failing dependent, and only failing on macOS 13. We use the `embulk example` test to verify functionality.

* Write what you expected and observed actually
  * Expected the test would complete successfully like it does on other macOS versions and Linux.
  * Relevant GitHub Actions run: https://github.com/Homebrew/homebrew-core/actions/runs/3977849956/jobs/6819316022#step:10:133

**Comment by hiroyuki-sato** [comment]
Hello, @p-linnane 

Thank you for reporting this issue.

I suppose this error relates to JRuby 9.1.15.0 (or JDK 1.8) on macOS 13.
(Not embulk itself)
I'll investigate this error (But I don't have a test environment yet.)

I copied this error.

And the Embulk team doesn't maintain a Homebrew formula of Embulk.

```
==> FAILED
Full test embulk output
  ==> Testing embulk
  ==> /usr/local/Cellar/embulk/0.9.24/bin/embulk example ./try1
  Picked up _JAVA_OPTIONS: -Duser.home=/Users/brew/Library/Caches/Homebrew/java_cache -Djava.io.tmpdir=/private/tmp
  2023-01-22 04:06:07.095 +0000: Embulk v0.9.24
  Creating ./try1 directory...
    Creating ./try1/
    Creating ./try1/csv/
    Creating ./try1/csv/sample_01.csv.gz
    Creating ./try1/seed.yml
  Run following subcommands to try embulk:
     1. embulk guess ./try1/seed.yml -o config.yml
     2. embulk preview config.yml
     3. embulk run config.yml
  ==> /usr/local/Cellar/embulk/0.9.24/bin/embulk guess ./try1/seed.yml -o config.yml
    Timeout::Error: execution expired
  /usr/local/Homebrew/Library/Homebrew/formula.rb:2489:in `gets'
  /usr/local/Homebrew/Library/Homebrew/formula.rb:2489:in `block in system'
  /usr/local/Homebrew/Library/Homebrew/formula.rb:2462:in `open'
  /usr/local/Homebrew/Library/Homebrew/formula.rb:2462:in `system'
  /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/embulk.rb:30:in `block in <class:Embulk>'
  /usr/local/Homebrew/Library/Homebrew/formula.rb:2301:in `block (3 levels) in run_test'
  /usr/local/Homebrew/Library/Homebrew/utils.rb:605:in `with_env'
  /usr/local/Homebrew/Library/Homebrew/formula.rb:2300:in `block (2 levels) in run_test'
  /usr/local/Homebrew/Library/Homebrew/formula.rb:968:in `with_logging'
  /usr/local/Homebrew/Library/Homebrew/formula.rb:2299:in `block in run_test'
  /usr/local/Homebrew/Library/Homebrew/mktemp.rb:77:in `block in run'
  /usr/local/Homebrew/Library/Homebrew/mktemp.rb:77:in `chdir'
  /usr/local/Homebrew/Library/Homebrew/mktemp.rb:77:in `run'
  /usr/local/Homebrew/Library/Homebrew/formula.rb:2577:in `mktemp'
  /usr/local/Homebrew/Library/Homebrew/formula.rb:2293:in `run_test'
  /usr/local/Homebrew/Library/Homebrew/test.rb:45:in `block in <main>'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
  /usr/local/Homebrew/Library/Homebrew/test.rb:50:in `<main>'
```

**Comment by p-linnane** [comment]
Thank you for your response. Please let me know if I can help test.

**Comment by hiroyuki-sato** [comment]
Hello, @p-linnane 

Could you try zulu8 instead of openjdk.

It worked fine on my environment.

M1 mac

```
  uname -a
Darwin palolovalley.local 22.3.0 Darwin Kernel Version 22.3.0: Thu Jan  5 20:49:43 PST 2023; root:xnu-8792.81.2~2/RELEASE_ARM64_T8103 arm64
```

macOS 13

```
sw_vers
ProductName:		macOS
ProductVersion:		13.2
BuildVersion:		22D49
```

zulu java 1.8.0_362

```
java -version
openjdk version "1.8.0_362"
OpenJDK Runtime Environment (Zulu 8.68.0.21-CA-macos-aarch64) (build 1.8.0_362-b09)
OpenJDK 64-Bit Server VM (Zulu 8.68.0.21-CA-macos-aarch64) (build 25.362-b09, mixed mode)
```

embulk 0.9.24

```
embulk --version
embulk 0.9.24
```

try embulk example

```
% embulk example hoge
2023-02-04 12:42:45.612 +0900: Embulk v0.9.24
Creating hoge directory...
  Creating hoge/
  Creating hoge/csv/
  Creating hoge/csv/sample_01.csv.gz
  Creating hoge/seed.yml

Run following subcommands to try embulk:

   1. embulk guess hoge/seed.yml -o config.yml
   2. embulk preview config.yml
   3. embulk run config.yml

% embulk guess hoge/seed.yml -o config.yml
2023-02-04 12:42:51.530 +0900: Embulk v0.9.24
2023-02-04 12:42:51.977 +0900 [WARN] (main): DEPRECATION: JRuby org.jruby.embed.ScriptingContainer is directly injected.
2023-02-04 12:42:52.758 +0900 [INFO] (main): Gem's home and path are set by default: "/Users/hsato/.embulk/lib/gems"
2023-02-04 12:42:53.109 +0900 [INFO] (main): Started Embulk v0.9.24
2023-02-04 12:42:53.250 +0900 [INFO] (0001:guess): Listing local files at directory '/private/tmp/hoge/csv' filtering filename by prefix 'sample_'
2023-02-04 12:42:53.250 +0900 [INFO] (0001:guess): "follow_symlinks" is set false. Note that symbolic links to directories are skipped.
2023-02-04 12:42:53.251 +0900 [INFO] (0001:guess): Loading files [/private/tmp/hoge/csv/sample_01.csv.gz]
2023-02-04 12:42:53.259 +0900 [INFO] (0001:guess): Try to read 32,768 bytes from input source
2023-02-04 12:42:53.287 +0900 [INFO] (0001:guess): Loaded plugin embulk (0.9.24)
2023-02-04 12:42:53.295 +0900 [INFO] (0001:guess): Loaded plugin embulk (0.9.24)
2023-02-04 12:42:53.302 +0900 [INFO] (0001:guess): Loaded plugin embulk (0.9.24)
2023-02-04 12:42:53.305 +0900 [INFO] (0001:guess): Loaded plugin embulk (0.9.24)
in:
  type: file
  path_prefix: /private/tmp/hoge/csv/sample_
  decoders:
  - {type: gzip}
  parser:
    charset: UTF-8
    newline: LF
    type: csv
    delimiter: ','
    quote: '"'
    escape: '"'
    null_string: 'NULL'
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: id, type: long}
    - {name: account, type: long}
    - {name: time, type: timestamp, format: '%Y-%m-%d %H:%M:%S'}
    - {name: purchase, type: timestamp, format: '%Y%m%d'}
    - {name: comment, type: string}
out: {type: stdout}

Created 'config.yml' file.
% embulk run config.yml
% embulk run config.yml
2023-02-04 12:43:11.074 +0900: Embulk v0.9.24
2023-02-04 12:43:11.603 +0900 [WARN] (main): DEPRECATION: JRuby org.jruby.embed.ScriptingContainer is directly injected.
2023-02-04 12:43:12.721 +0900 [INFO] (main): Gem's home and path are set by default: "/Users/hsato/.embulk/lib/gems"
2023-02-04 12:43:13.258 +0900 [INFO] (main): Started Embulk v0.9.24
2023-02-04 12:43:13.306 +0900 [INFO] (0001:transaction): Listing local files at directory '/private/tmp/hoge/csv' filtering filename by prefix 'sample_'
2023-02-04 12:43:13.307 +0900 [INFO] (0001:transaction): "follow_symlinks" is set false. Note that symbolic links to directories are skipped.
2023-02-04 12:43:13.307 +0900 [INFO] (0001:transaction): Loading files [/private/tmp/hoge/csv/sample_01.csv.gz]
2023-02-04 12:43:13.329 +0900 [INFO] (0001:transaction): Using local thread executor with max_threads=16 / output tasks 8 = input tasks 1 * 8
2023-02-04 12:43:13.332 +0900 [INFO] (0001:transaction): {done:  0 / 1, running: 0}
1,32864,2015-01-27 19:23:49,20150127,embulk
2,14824,2015-01-27 19:01:23,20150127,embulk jruby
3,27559,2015-01-28 02:20:02,20150128,Embulk "csv" parser plugin
4,11270,2015-01-29 11:54:36,20150129,
```

**Comment by p-linnane** [comment]
Thank you.
