### ISSUE TITLE
Field 'BufferAllocator' is required but not set

### ISSUE THREAD

**Issue by euchul95** [embulk/embulk#1632]
I have encountered an issue where the environment consists of 
Windows 10 OS, 
Java 8, 
Embulk version 0.11.0, 
JRuby 9.4.3.0,
embulk-input-sqlserver (version 0.13.2), 
and embulk-output-s3 (version 1.7.1). 

The problem is related to the absence of proper configuration for the buffer allocator, resulting in an error. 

I have included the error log and a list of installed gem plugins below. 

I would appreciate it if you could help me with this matter. 

Thank you.

Plugin List
------------------------------------------------------------
abbrev (default: 0.1.0)
addressable (2.8.5)
base64 (default: 0.1.1)
benchmark (default: 0.2.0)
bundler (2.4.19, default: 2.3.26)
cgi (default: 0.3.6 java)
csv (default: 3.2.5)
date (default: 3.3.3 java)
debug (default: 0.2.1)
delegate (default: 0.2.0)
did_you_mean (default: 1.6.1)
digest (default: 3.1.0 java)
drb (default: 2.1.0)
embulk (0.11.0 java)
embulk-decoder-commons-compress (0.5.0)
embulk-encoder-commons-compress (0.1.1)
embulk-input-filesplit (0.1.4)
embulk-input-jdbc (0.13.2 java)
embulk-input-sqlserver (0.13.2 java)
embulk-output-jdbc (0.10.2 java)
embulk-output-s3 (1.7.1 java)
embulk-output-s3_parquet (0.5.2 java)
embulk-output-s3_per_record (0.4.0)
embulk-parser-jsonpath (0.4.0 java)
embulk-parser-xml (0.13.0)
english (default: 0.7.1)
environs (1.1.0)
erb (default: 2.2.3)
error_highlight (default: 0.3.0)
faraday (1.10.3)
faraday-em_http (1.0.0)
faraday-em_synchrony (1.0.0)
faraday-excon (1.1.0)
faraday-httpclient (1.0.1)
faraday-multipart (1.0.4)
faraday-net_http (1.0.1)
faraday-net_http_persistent (1.2.0)
faraday-patron (1.0.0)
faraday-rack (1.0.0)
faraday-retry (1.0.3)
faraday_middleware (1.2.0)
ffi (default: 1.15.5 java)
ffi-binary-libfixposix (default: 0.5.1.1 java)
ffi-bindings-libfixposix (default: 0.5.1.0)
fileutils (default: 1.6.0)
find (default: 0.1.1)
forwardable (default: 1.3.2)
getoptlong (default: 0.1.1)
hashie (5.0.0)
io-console (default: 0.5.11 java)
io-wait (default: 0.3.0 java)
ipaddr (default: 1.2.4)
irb (default: 1.4.2)
jar-dependencies (default: 0.4.1)
jruby-openssl (0.14.2 java, default: 0.14.1 java)
jruby-readline (default: 1.3.7 java)
json (2.6.3 java, default: 2.6.1 java)
jsonpath (0.9.9)
liquid (5.4.0)
logger (default: 1.5.1)
minitest (5.19.0)
msgpack (1.7.2 java)
multi_json (1.15.0)
multipart-post (2.3.0)
mutex_m (default: 0.1.1)
net-http (default: 0.3.0)
net-protocol (default: 0.1.2)
net-telnet (0.2.0)
nokogiri (1.10.10 java)
observer (default: 0.1.1)
open-uri (default: 0.3.0)
open3 (default: 0.1.2)
optparse (default: 0.2.0)
ostruct (default: 0.5.5)
power_assert (2.0.3)
pp (default: 0.3.0)
prettyprint (default: 0.1.1)
proxies (0.2.3)
pstore (default: 0.1.1)
psych (default: 5.1.0 java)
public_suffix (5.0.3)
racc (default: 1.6.0 java)
rake (13.0.6)
rake-ant (default: 1.0.6)
rdoc (default: 6.4.0)
reline (default: 0.3.5)
resolv-replace (default: 0.1.0)
rinda (default: 0.1.1)
ruby2_keywords (default: 0.0.5)
rubygems-update (default: 3.3.26)
s3 (0.3.29)
securerandom (default: 0.2.0)
shellwords (default: 0.1.0)
singleton (default: 0.1.1)
stringio (default: 3.0.5 java)
strscan (default: 3.0.6 java)
subspawn (default: 0.1.1)
subspawn-posix (default: 0.1.1)
time (default: 0.2.2)
timeout (default: 0.3.2)
to_regexp (0.2.1)
tsort (default: 0.1.0)
un (default: 0.2.0)
uri (default: 0.12.1)
weakref (default: 0.1.1)
yaml (default: 0.2.0)
------------------------------------------------------------
log
------------------------------------------------------------
[0;39morg.embulk.exec.PartialExecutionException: java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Field 'BufferAllocator' is required but not set
 at [Source: N/A; line: -1, column: -1]
        at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(BulkLoader.java:340)
        at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:580)
        at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:36)
        at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:353)
        at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:350)
        at org.embulk.spi.ExecInternal.doWith(ExecInternal.java:26)
        at org.embulk.exec.BulkLoader.run(BulkLoader.java:350)
        at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:278)
        at org.embulk.EmbulkRunner.runInternal(EmbulkRunner.java:288)
        at org.embulk.EmbulkRunner.run(EmbulkRunner.java:153)
        at org.embulk.cli.EmbulkRun.runInternal(EmbulkRun.java:108)
        at org.embulk.cli.EmbulkRun.run(EmbulkRun.java:24)
        at org.embulk.cli.Main.main(Main.java:53)
Caused by: java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Field 'BufferAllocator' is required but not set
 at [Source: N/A; line: -1, column: -1]
        at org.embulk.deps.config.ModelManagerDelegateImpl.readObject(ModelManagerDelegateImpl.java:71)
        at org.embulk.deps.config.DataSourceImpl.loadTask(DataSourceImpl.java:329)
        at org.embulk.encoder.CommonsCompressEncoderPlugin.open(CommonsCompressEncoderPlugin.java:37)
        at org.embulk.spi.util.EncodersInternal.open(EncodersInternal.java:38)
        at org.embulk.spi.FileOutputRunner.open(FileOutputRunner.java:122)
        at org.embulk.exec.LocalExecutorPlugin$ScatterTransactionalPageOutput.openOutputs(LocalExecutorPlugin.java:417)
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.runInputTask(LocalExecutorPlugin.java:272)
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.access$200(LocalExecutorPlugin.java:218)
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor$1.call(LocalExecutorPlugin.java:249)
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor$1.call(LocalExecutorPlugin.java:246)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Field 'BufferAllocator' is required but not set
 at [Source: N/A; line: -1, column: -1]
        at org.embulk.deps.config.TaskSerDe$TaskDeserializer.deserialize(TaskSerDe.java:183)
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3708)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2005)
        at org.embulk.deps.config.ModelManagerDelegateImpl.readObject(ModelManagerDelegateImpl.java:66)
        ... 13 more

Error: java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Field 'BufferAllocator' is required but not set

**Comment by hiroyuki-sato** [comment]
Hello, @euchul95 

You need to follow the issue template.
What kind of encoder / formatter are you use?
It suspect that a plugin does not support v0.11 yet.
(Ex, embulk-encoder-commons-compress doesn't support v0.11 yet)

```
Issue Type: Questions
----------------------
Post your question in User forum at GitHub Discussions, instead of submitting an Issue here.

https://github.com/orgs/embulk/discussions

Issue Type: Bug Report
-----------------------

* Write the following environmental information.
  * OS version
  * Java version
  * Embulk version
  * Your Embulk configuration (YAML)
  * Plugin versions
* Write all what you did, e.g. your commands executed
* Write what you expected and observed actually
```

**Comment by hiroyuki-sato** [comment]
I reproduced the same error with the following configuration.

This is because `embulk-encoder-commons-compress` doesn't support v0.11 yet.

The input data used that generated by `embulk example`.

* embulk: v0.11.0

```yaml
in:
  type: file
  path_prefix: hoge/csv/sample_
  parser:
    charset: UTF-8
    newline: LF
    type: csv
    delimiter: ','
    quote: '"'
    escape: '"'
    null_string: 'NULL'
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: id, type: boolean}
    - {name: account, type: long}
    - {name: time, type: timestamp, format: '%Y-%m-%d %H:%M:%S'}
    - {name: purchase, type: timestamp, format: '%Y%m%d'}
    - {name: comment, type: string}
#out: {type: stdout}
out:
  type: file
  path_prefix: /tmp/fff/out
  file_ext: csv
  formatter:
    type: csv
  encoders:
    - type: commons-compress
      format: gzip
```

```
org.embulk.exec.PartialExecutionException: java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Field 'BufferAllocator' is required but not set
 at [Source: N/A; line: -1, column: -1]
	at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(BulkLoader.java:340)
	at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:580)
	at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:36)
	at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:353)
	at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:350)
	at org.embulk.spi.ExecInternal.doWith(ExecInternal.java:26)
	at org.embulk.exec.BulkLoader.run(BulkLoader.java:350)
	at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:278)
	at org.embulk.EmbulkRunner.runInternal(EmbulkRunner.java:288)
	at org.embulk.EmbulkRunner.run(EmbulkRunner.java:153)
	at org.embulk.cli.EmbulkRun.runInternal(EmbulkRun.java:108)
	at org.embulk.cli.EmbulkRun.run(EmbulkRun.java:24)
	at org.embulk.cli.Main.main(Main.java:53)
Caused by: java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Field 'BufferAllocator' is required but not set
 at [Source: N/A; line: -1, column: -1]
	at org.embulk.deps.config.ModelManagerDelegateImpl.readObject(ModelManagerDelegateImpl.java:71)
	at org.embulk.deps.config.DataSourceImpl.loadTask(DataSourceImpl.java:329)
	at org.embulk.encoder.CommonsCompressEncoderPlugin.open(CommonsCompressEncoderPlugin.java:37)
	at org.embulk.spi.util.EncodersInternal.open(EncodersInternal.java:38)
	at org.embulk.spi.FileOutputRunner.open(FileOutputRunner.java:122)
	at org.embulk.exec.LocalExecutorPlugin$ScatterTransactionalPageOutput.openOutputs(LocalExecutorPlugin.java:417)
	at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.runInputTask(LocalExecutorPlugin.java:272)
	at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.access$200(LocalExecutorPlugin.java:218)
	at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor$1.call(LocalExecutorPlugin.java:249)
	at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor$1.call(LocalExecutorPlugin.java:246)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Field 'BufferAllocator' is required but not set
 at [Source: N/A; line: -1, column: -1]
	at org.embulk.deps.config.TaskSerDe$TaskDeserializer.deserialize(TaskSerDe.java:183)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3708)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2005)
	at org.embulk.deps.config.ModelManagerDelegateImpl.readObject(ModelManagerDelegateImpl.java:66)
	... 13 more

Error: java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Field 'BufferAllocator' is required but not set
 at [Source: N/A; line: -1, column: -1]
```
