### ISSUE TITLE
org.embulk.config.ConfigException: OutputPlugin 'bigquery' is not found. org.jruby.exceptions.LoadError: (LoadError) no such file to load -- google/apis/bigquery_v2

### ISSUE THREAD

**Issue by nitishrjr** [embulk/embulk#1637]
I am trying to load the data in bigquery. I am keep on getting the below error. I have tried uninstall/install mutliple times.

org.embulk.config.ConfigException: OutputPlugin 'bigquery' is not found.
org.jruby.exceptions.LoadError: (LoadError) no such file to load -- google/apis/bigquery_v2
	at org.embulk.plugin.PluginManager.buildPluginNotFoundException(PluginManager.java:155)
	at org.embulk.plugin.PluginManager.newPlugin(PluginManager.java:99)
	at org.embulk.spi.ExecSessionInternal.newPlugin(ExecSessionInternal.java:358)
	at org.embulk.spi.ExecInternal.newPlugin(ExecInternal.java:50)
	at org.embulk.exec.BulkLoader$ProcessPluginSet.<init>(BulkLoader.java:442)
	at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:516)
	at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:36)
	at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:353)
	at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:350)
	at org.embulk.spi.ExecInternal.doWith(ExecInternal.java:26)
	at org.embulk.exec.BulkLoader.run(BulkLoader.java:350)
	at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:278)
	at org.embulk.EmbulkRunner.runInternal(EmbulkRunner.java:288)
	at org.embulk.EmbulkRunner.run(EmbulkRunner.java:153)
	at org.embulk.cli.EmbulkRun.runInternal(EmbulkRun.java:108)
	at org.embulk.cli.EmbulkRun.run(EmbulkRun.java:24)
	at org.embulk.cli.Main.main(Main.java:53)
	Suppressed: org.embulk.plugin.PluginSourceNotMatchException
		at org.embulk.plugin.BuiltinPluginSource.newPlugin(BuiltinPluginSource.java:244)
		at org.embulk.plugin.PluginManager.newPlugin(PluginManager.java:76)
		... 15 more
	Suppressed: org.embulk.plugin.PluginSourceNotMatchException
		at org.embulk.plugin.maven.MavenPluginRegistry.findPluginPaths(MavenPluginRegistry.java:143)
		at org.embulk.plugin.maven.MavenPluginRegistry.lookup(MavenPluginRegistry.java:63)
		at org.embulk.plugin.maven.MavenPluginSource.newPlugin(MavenPluginSource.java:33)
		at org.embulk.plugin.PluginManager.newPlugin(PluginManager.java:82)
		... 15 more
	Suppressed: org.embulk.plugin.PluginSourceNotMatchException
		at org.embulk.plugin.SelfContainedPluginRegistry.search(SelfContainedPluginRegistry.java:77)
		at org.embulk.plugin.SelfContainedPluginRegistry.lookup(SelfContainedPluginRegistry.java:64)
		at org.embulk.plugin.SelfContainedPluginSource.newPlugin(SelfContainedPluginSource.java:44)
		at org.embulk.plugin.PluginManager.newPlugin(PluginManager.java:88)
		... 15 more
	Suppressed: org.embulk.plugin.PluginSourceNotMatchException: Failed to initialize embulk-output-bigquery.
		at org.embulk.jruby.JRubyPluginSource.newPlugin(JRubyPluginSource.java:89)
		at org.embulk.plugin.PluginManager.newPlugin(PluginManager.java:94)
		... 15 more
	Caused by: org.jruby.embed.InvokeFailedException: org.jruby.exceptions.LoadError: (LoadError) no such file to load -- google/apis/bigquery_v2
		at org.jruby.embed.internal.EmbedRubyObjectAdapterImpl.doInvokeMethod(EmbedRubyObjectAdapterImpl.java:251)
		at org.jruby.embed.internal.EmbedRubyObjectAdapterImpl.callMethod(EmbedRubyObjectAdapterImpl.java:156)
		at org.jruby.embed.ScriptingContainer.callMethod(ScriptingContainer.java:1448)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
		at org.embulk.jruby.ScriptingContainerDelegateImpl.callMethod(ScriptingContainerDelegateImpl.java:644)
		at org.embulk.jruby.LazyScriptingContainerDelegate.callMethod(LazyScriptingContainerDelegate.java:230)
		at org.embulk.jruby.JRubyPluginSource.newPlugin(JRubyPluginSource.java:87)
		... 16 more
	Caused by: org.jruby.exceptions.LoadError: (LoadError) no such file to load -- google/apis/bigquery_v2
		at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1071)
		at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.rubygems.core_ext.kernel_require.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:160)
		at RUBY.<main>(/home/azureuser/.embulk/lib/gems/gems/embulk-output-bigquery-0.6.9/lib/embulk/output/bigquery/bigquery_client.rb:1)
		at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1071)
		at org.jruby.RubyKernel.require_relative(org/jruby/RubyKernel.java:1098)
		at RUBY.<main>(/home/azureuser/.embulk/lib/gems/gems/embulk-output-bigquery-0.6.9/lib/embulk/output/bigquery.rb:6)
		at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1071)
		at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.rubygems.core_ext.kernel_require.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:160)
		at RUBY.require_and_show(/home/azureuser/.embulk/lib/gems/gems/embulk-0.11.0-java/lib/embulk/plugin_registry.rb:81)
		at RUBY.search(/home/azureuser/.embulk/lib/gems/gems/embulk-0.11.0-java/lib/embulk/plugin_registry.rb:39)
		at RUBY.lookup(/home/azureuser/.embulk/lib/gems/gems/embulk-0.11.0-java/lib/embulk/plugin_registry.rb:26)
		at RUBY.lookup(/home/azureuser/.embulk/lib/gems/gems/embulk-0.11.0-java/lib/embulk/plugin.rb:197)
		at RUBY.new_java_output(/home/azureuser/.embulk/lib/gems/gems/embulk-0.11.0-java/lib/embulk/plugin.rb:159)
		at RUBY.new_java_output(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/forwardable.rb:238)
	Caused by: org.jruby.exceptions.LoadError: (LoadError) no such file to load -- google/apis/bigquery_v2
		at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1071)
		at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.rubygems.core_ext.kernel_require.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:148)
		... 12 more
	Caused by: org.jruby.exceptions.LoadError: (LoadError) no such file to load -- embulk/output/bigquery
		at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1071)
		at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.rubygems.core_ext.kernel_require.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:85)
		... 6 more

Error: OutputPlugin 'bigquery' is not found.
org.jruby.exceptions.LoadError: (LoadError) no such file to load -- google/apis/bigquery_v2

Could someone help me, I am new here.

**Comment by hiroyuki-sato** [comment]
You need to follow an issue template.

Issue Type: Questions
----------------------
Post your question in User forum at GitHub Discussions, instead of submitting an Issue here.

https://github.com/orgs/embulk/discussions

**Comment by nitishrjr** [comment]
Ok, i will close it here and will write it at user forum. thanks.
