### ISSUE TITLE
v0.6.14 embulk example does not work properly.

### ISSUE THREAD

**Issue by hiroyuki-sato** [embulk/embulk#217]
embulk preview raise exception.

```
embulk example test4
2015-06-29 19:25:02.985 +0900: Embulk v0.6.14
Creating test4 directory...
  Creating test4/
  Creating test4/csv/
  Creating test4/csv/sample_01.csv.gz
  Creating test4/example.yml

Run following subcommands to try embulk:

   1. guess test4/example.yml -o config.yml
   2. preview config.yml
   3. run config.yml
```

exec guess

```
embulk guess test4/example.yml -o config.yml
2015-06-29 19:25:16.341 +0900: Embulk v0.6.14
2015-06-29 19:25:17.648 +0900 [INFO] (guess): Listing local files at directory '/private/tmp/test4/csv' filtering filename by prefix 'sample_'
2015-06-29 19:25:17.655 +0900 [INFO] (guess): Loading files [/private/tmp/test4/csv/sample_01.csv.gz]
2015-06-29 19:25:17.751 +0900 [INFO] (guess): Loaded plugin embulk/guess/gzip from a load path
2015-06-29 19:25:17.763 +0900 [INFO] (guess): Loaded plugin embulk/guess/csv from a load path
in:
  type: file
  path_prefix: /private/tmp/test4/csv/sample_
  decoders:
  - {type: gzip}
  parser:
    charset: UTF-8
    newline: CRLF
    type: csv
    delimiter: ','
    quote: '"'
    escape: ''
    trim_if_not_quoted: false
    skip_header_lines: 1
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: id, type: long}
    - {name: account, type: long}
    - {name: time, type: timestamp, format: '%Y-%m-%d %H:%M:%S'}
    - {name: purchase, type: timestamp, format: '%Y%m%d'}
    - {name: comment, type: string}
exec: {}
out: {type: stdout}

Created 'config.yml' file.
```

and execute preview (and raise exception)

```
% embulk preview config.yml
2015-06-29 19:25:31.425 +0900: Embulk v0.6.14
2015-06-29 19:25:32.767 +0900 [INFO] (preview): Listing local files at directory '/private/tmp/test4/csv' filtering filename by prefix 'sample_'
2015-06-29 19:25:32.775 +0900 [INFO] (preview): Loading files [/private/tmp/test4/csv/sample_01.csv.gz]
org.embulk.config.ConfigException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "format" (class org.embulk.spi.ColumnConfig), not marked as ignorable (3 known properties: "type", "name", "option"])
 at [Source: N/A; line: -1, column: -1] (through reference chain: java.util.ArrayList[2]->org.embulk.spi.ColumnConfig["format"])
	at org.embulk.config.ModelManager.readObjectWithConfigSerDe(org/embulk/config/ModelManager.java:77)
	at org.embulk.config.DataSourceImpl.loadConfig(org/embulk/config/DataSourceImpl.java:205)
	at org.embulk.standards.CsvParserPlugin.transaction(org/embulk/standards/CsvParserPlugin.java:114)
	at org.embulk.spi.FileInputRunner$RunnerControl$1.run(org/embulk/spi/FileInputRunner.java:111)
	at org.embulk.spi.util.Decoders$RecursiveControl.transaction(org/embulk/spi/util/Decoders.java:77)
	at org.embulk.spi.util.Decoders$RecursiveControl$1.run(org/embulk/spi/util/Decoders.java:73)
	at org.embulk.standards.GzipFileDecoderPlugin.transaction(org/embulk/standards/GzipFileDecoderPlugin.java:30)
	at org.embulk.spi.util.Decoders$RecursiveControl.transaction(org/embulk/spi/util/Decoders.java:68)
	at org.embulk.spi.util.Decoders.transaction(org/embulk/spi/util/Decoders.java:33)
	at org.embulk.spi.FileInputRunner$RunnerControl.run(org/embulk/spi/FileInputRunner.java:108)
	at org.embulk.standards.LocalFileInputPlugin.resume(org/embulk/standards/LocalFileInputPlugin.java:80)
	at org.embulk.standards.LocalFileInputPlugin.transaction(org/embulk/standards/LocalFileInputPlugin.java:70)
	at org.embulk.spi.FileInputRunner.transaction(org/embulk/spi/FileInputRunner.java:63)
	at org.embulk.exec.PreviewExecutor.doPreview(org/embulk/exec/PreviewExecutor.java:93)
	at org.embulk.exec.PreviewExecutor.access$000(org/embulk/exec/PreviewExecutor.java:27)
	at org.embulk.exec.PreviewExecutor$1.run(org/embulk/exec/PreviewExecutor.java:67)
	at org.embulk.exec.PreviewExecutor$1.run(org/embulk/exec/PreviewExecutor.java:63)
	at org.embulk.spi.Exec.doWith(org/embulk/spi/Exec.java:24)
	at org.embulk.exec.PreviewExecutor.preview(org/embulk/exec/PreviewExecutor.java:63)
	at org.embulk.command.Runner.preview(org/embulk/command/Runner.java:250)
	at org.embulk.command.Runner.main(org/embulk/command/Runner.java:110)
	at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:483)
	at RUBY.run(file:/Users/hsato/.embulk/bin/embulk!/embulk/command/embulk_run.rb:351)
	at classpath_3a_embulk.command.embulk.(root)(classpath:embulk/command/embulk.rb:47)
	at classpath_3a_embulk.command.embulk.(root)(classpath_3a_embulk/command/classpath:embulk/command/embulk.rb:47)
	at org.embulk.cli.Main.main(org/embulk/cli/Main.java:11)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "format" (class org.embulk.spi.ColumnConfig), not marked as ignorable (3 known properties: "type", "name", "option"])
 at [Source: N/A; line: -1, column: -1] (through reference chain: java.util.ArrayList[2]->org.embulk.spi.ColumnConfig["format"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:51)
	at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:817)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:958)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1324)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperties(BeanDeserializerBase.java:1278)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:452)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1073)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:142)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromArray(BeanDeserializerBase.java:1203)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:165)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:144)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3534)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1894)
	at org.embulk.config.TaskSerDe$TaskDeserializer.deserialize(TaskSerDe.java:157)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3534)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1870)
	at org.embulk.config.ModelManager.readObjectWithConfigSerDe(ModelManager.java:74)
	at org.embulk.config.DataSourceImpl.loadConfig(DataSourceImpl.java:205)
	at org.embulk.standards.CsvParserPlugin.transaction(CsvParserPlugin.java:114)
	at org.embulk.spi.FileInputRunner$RunnerControl$1.run(FileInputRunner.java:111)
	at org.embulk.spi.util.Decoders$RecursiveControl.transaction(Decoders.java:77)
	at org.embulk.spi.util.Decoders$RecursiveControl$1.run(Decoders.java:73)
	at org.embulk.standards.GzipFileDecoderPlugin.transaction(GzipFileDecoderPlugin.java:30)
	at org.embulk.spi.util.Decoders$RecursiveControl.transaction(Decoders.java:68)
	at org.embulk.spi.util.Decoders.transaction(Decoders.java:33)
	at org.embulk.spi.FileInputRunner$RunnerControl.run(FileInputRunner.java:108)
	at org.embulk.standards.LocalFileInputPlugin.resume(LocalFileInputPlugin.java:80)
	at org.embulk.standards.LocalFileInputPlugin.transaction(LocalFileInputPlugin.java:70)
	at org.embulk.spi.FileInputRunner.transaction(FileInputRunner.java:63)
	at org.embulk.exec.PreviewExecutor.doPreview(PreviewExecutor.java:93)
	at org.embulk.exec.PreviewExecutor.access$000(PreviewExecutor.java:27)
	at org.embulk.exec.PreviewExecutor$1.run(PreviewExecutor.java:67)
	at org.embulk.exec.PreviewExecutor$1.run(PreviewExecutor.java:63)
	at org.embulk.spi.Exec.doWith(Exec.java:24)
	at org.embulk.exec.PreviewExecutor.preview(PreviewExecutor.java:63)
	at org.embulk.command.Runner.preview(Runner.java:250)
	at org.embulk.command.Runner.main(Runner.java:110)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:470)
	at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:328)
	at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:71)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:346)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:204)
	at org.jruby.ast.CallTwoArgNode.interpret(CallTwoArgNode.java:59)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.ast.RescueNode.executeBody(RescueNode.java:221)
	at org.jruby.ast.RescueNode.interpret(RescueNode.java:116)
	at org.jruby.ast.BeginNode.interpret(BeginNode.java:83)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.ast.CaseNode.interpret(CaseNode.java:138)
	at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
	at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
	at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
	at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:182)
	at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:203)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
	at classpath_3a_embulk.command.embulk.__file__(classpath:embulk/command/embulk.rb:47)
	at classpath_3a_embulk.command.embulk.load(classpath:embulk/command/embulk.rb)
	at org.jruby.Ruby.runScript(Ruby.java:866)
	at org.jruby.Ruby.runScript(Ruby.java:859)
	at org.jruby.Ruby.runNormally(Ruby.java:728)
	at org.jruby.Ruby.runFromMain(Ruby.java:577)
	at org.jruby.Main.doRunFromMain(Main.java:395)
	at org.jruby.Main.internalRun(Main.java:290)
	at org.jruby.Main.run(Main.java:217)
	at org.jruby.Main.main(Main.java:197)
	at org.embulk.cli.Main.main(Main.java:11)

Error: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "format" (class org.embulk.spi.ColumnConfig), not marked as ignorable (3 known properties: "type", "name", "option"])
 at [Source: N/A; line: -1, column: -1] (through reference chain: java.util.ArrayList[2]->org.embulk.spi.ColumnConfig["format"])
```

**Comment by frsyuki** [comment]
Fixed at 454888045fd7eb8222015405556576df9db731dc. Thank you! I release next version soon.
