### ISSUE TITLE
Can not find plugin when use '-L' option.

### ISSUE THREAD

**Issue by mikoto2000** [embulk/embulk#276]
Embulk version 0.6.24 can not find plugin when use '-L' option,
but version 0.6.21 can find it.

Is there something that is considered to be the cause of that?

Best regards.

### Environment

- OS: Windows8.1 64bit
- Java: 1.8.0.51
- Embulk: 0.6.24

### Steps to reproduce

I try 'Quick Start' and 'Createing plugins'

- [Quick Start](https://github.com/embulk/embulk#quick-start)
- [Createing plugins](http://www.embulk.org/docs/customization.html#creating-plugins)

```cmd
PowerShell -Command "& {Invoke-WebRequest http://dl.embulk.org/embulk-latest.jar -OutFile embulk.bat}"

embulk example ./try1
embulk guess   ./try1/example.yml -o config.yml
embulk preview config.yml
embulk run     config.yml

embulk.bat new java-filter first

cd embulk-filter-first
gradlew package

cd ..
echo filters: [{ type: first, option1: 100 }] >> config.yml

embulk.bat preview -L embulk-filter-first config.yml
```

I get this message when run "embulk.bat preview -L embulk-filter-first config.yml" command.
(If use v0.6.21 binary, can find plugin.)

#### stdout

```
2015-08-17 01:01:17.355 +0900: Embulk v0.6.24
org.embulk.config.ConfigException: FilterPlugin 'first' is not found.
(PluginLoadError) Unknown filter plugin 'first'. embulk/filter/first.rb is not installed. Run 'embulk gem search -rd embulk-filter' command to find plugins.
	at org.embulk.plugin.PluginManager.buildPluginNotFoundException(org/embulk/plugin/PluginManager.java:59)
	at org.embulk.plugin.PluginManager.newPlugin(org/embulk/plugin/PluginManager.java:44)
	at org.embulk.spi.ExecSession.newPlugin(org/embulk/spi/ExecSession.java:166)
	at org.embulk.spi.util.Filters.newFilterPlugins(org/embulk/spi/util/Filters.java:37)
	at org.embulk.spi.util.Filters.newFilterPluginsFromConfigSources(org/embulk/spi/util/Filters.java:30)
	at org.embulk.exec.PreviewExecutor.newFilterPlugins(org/embulk/exec/PreviewExecutor.java:83)
	at org.embulk.exec.PreviewExecutor.doPreview(org/embulk/exec/PreviewExecutor.java:90)
	at org.embulk.exec.PreviewExecutor.access$000(org/embulk/exec/PreviewExecutor.java:27)
	at org.embulk.exec.PreviewExecutor$1.run(org/embulk/exec/PreviewExecutor.java:67)
	at org.embulk.exec.PreviewExecutor$1.run(org/embulk/exec/PreviewExecutor.java:63)
	at org.embulk.spi.Exec.doWith(org/embulk/spi/Exec.java:25)
	at org.embulk.exec.PreviewExecutor.preview(org/embulk/exec/PreviewExecutor.java:63)
	at org.embulk.command.Runner.preview(org/embulk/command/Runner.java:283)
	at org.embulk.command.Runner.main(org/embulk/command/Runner.java:126)
	at RUBY.run(file:/C:/Users/mikoto/tmp/embulk/embulk.bat!/embulk/command/embulk_run.rb:370)
	at classpath_3a_embulk.command.embulk.(root)(classpath:embulk/command/embulk.rb:47)
	at classpath_3a_embulk.command.embulk.(root)(classpath_3a_embulk/command/classpath:embulk/command/embulk.rb:47)
	at org.embulk.cli.Main.main(org/embulk/cli/Main.java:11)
	Suppressed: org.embulk.plugin.PluginSourceNotMatchException
		at org.embulk.plugin.InjectedPluginSource.newPlugin(InjectedPluginSource.java:54)
		at org.embulk.plugin.PluginManager.newPlugin(PluginManager.java:38)
		at org.embulk.spi.ExecSession.newPlugin(ExecSession.java:166)
		at org.embulk.spi.util.Filters.newFilterPlugins(Filters.java:37)
		at org.embulk.spi.util.Filters.newFilterPluginsFromConfigSources(Filters.java:30)
		at org.embulk.exec.PreviewExecutor.newFilterPlugins(PreviewExecutor.java:83)
		at org.embulk.exec.PreviewExecutor.doPreview(PreviewExecutor.java:90)
		at org.embulk.exec.PreviewExecutor.access$000(PreviewExecutor.java:27)
		at org.embulk.exec.PreviewExecutor$1.run(PreviewExecutor.java:67)
		at org.embulk.exec.PreviewExecutor$1.run(PreviewExecutor.java:63)
		at org.embulk.spi.Exec.doWith(Exec.java:25)
		at org.embulk.exec.PreviewExecutor.preview(PreviewExecutor.java:63)
		at org.embulk.command.Runner.preview(Runner.java:283)
		at org.embulk.command.Runner.main(Runner.java:126)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
		at java.lang.reflect.Method.invoke(Unknown Source)
		at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:471)
		at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:329)
		at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:56)
		at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:346)
		at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:204)
		at org.jruby.ast.CallTwoArgNode.interpret(CallTwoArgNode.java:59)
		at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
		at org.jruby.ast.RescueNode.executeBody(RescueNode.java:221)
		at org.jruby.ast.RescueNode.interpret(RescueNode.java:116)
		at org.jruby.ast.BeginNode.interpret(BeginNode.java:83)
		at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
		at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
		at org.jruby.ast.CaseNode.interpret(CaseNode.java:138)
		at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
		at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
		at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
		at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:182)
		at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:203)
		at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)
		at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
		at classpath_3a_embulk.command.embulk.__file__(classpath:embulk/command/embulk.rb:47)
		at classpath_3a_embulk.command.embulk.load(classpath:embulk/command/embulk.rb)
		at org.jruby.Ruby.runScript(Ruby.java:867)
		at org.jruby.Ruby.runScript(Ruby.java:860)
		at org.jruby.Ruby.runNormally(Ruby.java:729)
		at org.jruby.Ruby.runFromMain(Ruby.java:578)
		at org.jruby.Main.doRunFromMain(Main.java:395)
		at org.jruby.Main.internalRun(Main.java:290)
		at org.jruby.Main.run(Main.java:217)
		at org.jruby.Main.main(Main.java:197)
		at org.embulk.cli.Main.main(Main.java:11)
	Suppressed: org.embulk.plugin.PluginSourceNotMatchException: org.jruby.exceptions.RaiseException: (PluginLoadError) Unknown filter plugin 'first'. embulk/filter/first.rb is not installed. Run 'embulk gem search -rd embulk-filter' command to find plugins.
		at org.embulk.jruby.JRubyPluginSource.newPlugin(JRubyPluginSource.java:69)
		at org.embulk.plugin.PluginManager.newPlugin(PluginManager.java:38)
		at org.embulk.spi.ExecSession.newPlugin(ExecSession.java:166)
		at org.embulk.spi.util.Filters.newFilterPlugins(Filters.java:37)
		at org.embulk.spi.util.Filters.newFilterPluginsFromConfigSources(Filters.java:30)
		at org.embulk.exec.PreviewExecutor.newFilterPlugins(PreviewExecutor.java:83)
		at org.embulk.exec.PreviewExecutor.doPreview(PreviewExecutor.java:90)
		at org.embulk.exec.PreviewExecutor.access$000(PreviewExecutor.java:27)
		at org.embulk.exec.PreviewExecutor$1.run(PreviewExecutor.java:67)
		at org.embulk.exec.PreviewExecutor$1.run(PreviewExecutor.java:63)
		at org.embulk.spi.Exec.doWith(Exec.java:25)
		at org.embulk.exec.PreviewExecutor.preview(PreviewExecutor.java:63)
		at org.embulk.command.Runner.preview(Runner.java:283)
		at org.embulk.command.Runner.main(Runner.java:126)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
		at java.lang.reflect.Method.invoke(Unknown Source)
		at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:471)
		at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:329)
		at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:56)
		at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:346)
		at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:204)
		at org.jruby.ast.CallTwoArgNode.interpret(CallTwoArgNode.java:59)
		at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
		at org.jruby.ast.RescueNode.executeBody(RescueNode.java:221)
		at org.jruby.ast.RescueNode.interpret(RescueNode.java:116)
		at org.jruby.ast.BeginNode.interpret(BeginNode.java:83)
		at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
		at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
		at org.jruby.ast.CaseNode.interpret(CaseNode.java:138)
		at org.jruby.ast.NewlineNode.interpret(NewlineNode.java:105)
		at org.jruby.ast.BlockNode.interpret(BlockNode.java:71)
		at org.jruby.evaluator.ASTInterpreter.INTERPRET_METHOD(ASTInterpreter.java:74)
		at org.jruby.internal.runtime.methods.InterpretedMethod.call(InterpretedMethod.java:182)
		at org.jruby.internal.runtime.methods.DefaultMethod.call(DefaultMethod.java:203)
		at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:326)
		at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:170)
		at classpath_3a_embulk.command.embulk.__file__(classpath:embulk/command/embulk.rb:47)
		at classpath_3a_embulk.command.embulk.load(classpath:embulk/command/embulk.rb)
		at org.jruby.Ruby.runScript(Ruby.java:867)
		at org.jruby.Ruby.runScript(Ruby.java:860)
		at org.jruby.Ruby.runNormally(Ruby.java:729)
		at org.jruby.Ruby.runFromMain(Ruby.java:578)
		at org.jruby.Main.doRunFromMain(Main.java:395)
		at org.jruby.Main.internalRun(Main.java:290)
		at org.jruby.Main.run(Main.java:217)
		at org.jruby.Main.main(Main.java:197)
		at org.embulk.cli.Main.main(Main.java:11)
	Caused by: org.jruby.exceptions.RaiseException: (PluginLoadError) Unknown filter plugin 'first'. embulk/filter/first.rb is not installed. Run 'embulk gem search -rd embulk-filter' command to find plugins.
		at RUBY.lookup(file:/C:/Users/mikoto/tmp/embulk/embulk.bat!/embulk/plugin_registry.rb:32)
		at RUBY.lookup(file:/C:/Users/mikoto/tmp/embulk/embulk.bat!/embulk/plugin.rb:196)
		at RUBY.new_java_filter(file:/C:/Users/mikoto/tmp/embulk/embulk.bat!/embulk/plugin.rb:162)
		at RUBY.new_java_filter(/C:/Users/mikoto/tmp/embulk/embulk.bat!/META-INF/jruby.home/lib/ruby/1.9/forwardable.rb:201)
		at RUBY.run(file:/C:/Users/mikoto/tmp/embulk/embulk.bat!/embulk/command/embulk_run.rb:370)
		at classpath_3a_embulk.command.embulk.(root)(classpath:embulk/command/embulk.rb:47)

Error: FilterPlugin 'first' is not found.
(PluginLoadError) Unknown filter plugin 'first'. embulk/filter/first.rb is not installed. Run 'embulk gem search -rd embulk-filter' command to find plugins.
```

#### stderr

```
io/console not supported; tty will not be manipulated
fatal: Not a git repository (or any of the parent directories): .git
Embulk::PluginLoadError: Unknown filter plugin 'first'. embulk/filter/first.rb is not installed. Run 'embulk gem search -rd embulk-filter' command to find plugins.
           lookup at file:/C:/Users/mikoto/tmp/embulk/embulk.bat!/embulk/plugin_registry.rb:32
           lookup at file:/C:/Users/mikoto/tmp/embulk/embulk.bat!/embulk/plugin.rb:196
  new_java_filter at file:/C:/Users/mikoto/tmp/embulk/embulk.bat!/embulk/plugin.rb:162
  new_java_filter at /C:/Users/mikoto/tmp/embulk/embulk.bat!/META-INF/jruby.home/lib/ruby/1.9/forwardable.rb:201
              run at file:/C:/Users/mikoto/tmp/embulk/embulk.bat!/embulk/command/embulk_run.rb:370
           (root) at classpath:embulk/command/embulk.rb:47
```

**Comment by frsyuki** [comment]
Thank you for the detailed report. Fixed at https://github.com/embulk/embulk/commit/0f356566877426f38ac2033fa358a0efe836eb58
