### ISSUE TITLE
Csv-parser-plugin does not skip a broken line 

### ISSUE THREAD

**Issue by nyangu** [embulk/embulk#277]
According to the document,
* [max_quoted_size_limit](http://www.embulk.org/docs/built-in.html#id3)

> Maximum number of bytes of a quoted value. 
> If a value exceeds the limit, the row **will be skipped**

But, csv-parser-plugin does not skip a broken line and it raises error(stopped bulk load).
How can I skip a broken line?

# Details
## Settings
```
in:
  type: file
  path_prefix: ./sample.csv
  parser:
    charset: UTF-8
    newline: CRLF
    type: csv
    delimiter: ','
    quote: '"'
    escape: ''
    header_line: false
    max_quoted_size_limit: 6
    columns:
    - {name: c0, type: string}
    - {name: c1, type: string}
    - {name: c2, type: string}
    - {name: c3, type: string}
    - {name: c4, type: string}
exec: {}
out: {type: stdout}
```

## Data
```
1,b,c,d,e
2,",123456",b,c,error line
3,",12345",b,c,safe line
```

## Log
```
2015-08-17 19:24:13.236 +0900: Embulk v0.6.25
2015-08-17 19:24:14.858 +0900 [INFO] (transaction): Listing local files at directory '.' filtering filename by prefix 'sample.csv'
2015-08-17 19:24:14.863 +0900 [INFO] (transaction): Loading files [sample.csv]
2015-08-17 19:24:14.888 +0900 [WARN] (transaction): Setting '' (empty string) to "escape" option is obsoleted. Currently it becomes null automatically but this behavior will be removed. Please set "escape: null" explicitly.
2015-08-17 19:24:14.916 +0900 [INFO] (transaction): {done:  0 / 1, running: 0}
2015-08-17 19:24:14.992 +0900 [INFO] (transaction): {done:  1 / 1, running: 0}
2015-08-17 19:24:14.994 +0900 [INFO] (main): Transaction partially failed. Cleaning up the intermediate data. Use -r option to make it resumable.
org.embulk.exec.PartialExecutionException: org.embulk.standards.CsvTokenizer$QuotedSizeLimitExceededException: The size of the quoted value exceeds the limit size (6)
        at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(org/embulk/exec/BulkLoader.java:331)
        at org.embulk.exec.BulkLoader.doRun(org/embulk/exec/BulkLoader.java:529)
        at org.embulk.exec.BulkLoader.access$100(org/embulk/exec/BulkLoader.java:36)
        at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:342)
        at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:338)
        at org.embulk.spi.Exec.doWith(org/embulk/spi/Exec.java:25)
        at org.embulk.exec.BulkLoader.run(org/embulk/exec/BulkLoader.java:338)
        at org.embulk.command.Runner.run(org/embulk/command/Runner.java:166)
        at org.embulk.command.Runner.main(org/embulk/command/Runner.java:117)
        at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:497)
        at RUBY.run(file:/home/$USER/bin/embulk!/embulk/command/embulk_run.rb:370)
        at classpath_3a_embulk.command.embulk.(root)(classpath:embulk/command/embulk.rb:47)
        at classpath_3a_embulk.command.embulk.(root)(classpath_3a_embulk/command/classpath:embulk/command/embulk.rb:47)
        at org.embulk.cli.Main.main(org/embulk/cli/Main.java:11)
Caused by: org.embulk.standards.CsvTokenizer$QuotedSizeLimitExceededException: The size of the quoted value exceeds the limit size (6)
        at org.embulk.standards.CsvTokenizer.nextColumn(CsvTokenizer.java:289)
        at org.embulk.standards.CsvParserPlugin$1.nextColumn(CsvParserPlugin.java:326)
        at org.embulk.standards.CsvParserPlugin$1.stringColumn(CsvParserPlugin.java:297)
        at org.embulk.spi.Column.visit(Column.java:57)
        at org.embulk.spi.Schema.visitColumns(Schema.java:76)
        at org.embulk.standards.CsvParserPlugin.run(CsvParserPlugin.java:254)
        at org.embulk.spi.FileInputRunner.run(FileInputRunner.java:145)
        at org.embulk.spi.util.Executors.process(Executors.java:59)
        at org.embulk.spi.util.Executors.process(Executors.java:39)
        at org.embulk.exec.LocalExecutorPlugin$2.call(LocalExecutorPlugin.java:105)
        at org.embulk.exec.LocalExecutorPlugin$2.call(LocalExecutorPlugin.java:101)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Error: org.embulk.standards.CsvTokenizer$QuotedSizeLimitExceededException: The size of the quoted value exceeds the limit size (6)
```

## Environment
OS: CentOS 6.6 x86_64
Embulk version: v0.6.25
Java version: 1.8.0_51-b16

Best regards.

**Comment by frsyuki** [comment]
Fixed at https://github.com/embulk/embulk/commit/153748a13e5328782ade3d05047b68440663980b.
Thank you!

**Comment by nyangu** [comment]
Thank you so much for fixing it.
