### ISSUE TITLE
Exception: Self-suppression not permitted

### ISSUE THREAD

**Issue by LanceNorskog** [embulk/embulk#415]
This is the stack trace printed by a Python program that calls Embulk via a custom web service. (This is why the start of each line is not familiar.) From what I can learn on the net, either Embulk or the JDBC driver is tripping over a quirk of the Java 7 try-with-resources syntax.

Does anybody know what to do is this situation?

Thanks,

Lance Norskog

2016-03-28 08:09:08.560 +0000 [INFO] (embulk-output-executor-3): > 0.00 seconds

[2016-03-28 08:09:08,562] {EmbulkWSPlugin.py:82} INFO - 2016-03-28 08:09:08.560 +0000 [INFO] (embulk-output-executor-3): Running COPY from file tmp/fatbird_deliveries/e591af19-0982-4093-8b3b-9b0f9fe74f88

[2016-03-28 08:09:15,428] {EmbulkWSPlugin.py:82} INFO - 2016-03-28 08:09:15.410 +0000 [INFO] (embulk-output-executor-3): Loaded file tmp/fatbird_deliveries/e591af19-0982-4093-8b3b-9b0f9fe74f88 (6.85 seconds for COPY)

[2016-03-28 08:09:15,492] {EmbulkWSPlugin.py:82} INFO - 2016-03-28 08:09:15.486 +0000 [INFO] (embulk-output-executor-1): Uploading file id tmp/fatbird_deliveries/14b18961-5c3f-4bca-86c3-67d899c176f6 to S3 (16,785,349 bytes 98,243 rows)

[2016-03-28 08:09:16,008] {EmbulkWSPlugin.py:82} INFO - 2016-03-28 08:09:16.002 +0000 [INFO] (embulk-output-executor-1): SQL: SET search_path TO "fatbird"

[2016-03-28 08:09:16,008] {EmbulkWSPlugin.py:82} INFO - 2016-03-28 08:09:16.004 +0000 [INFO] (embulk-output-executor-1): > 0.00 seconds

[2016-03-28 08:09:16,008] {EmbulkWSPlugin.py:82} INFO - 2016-03-28 08:09:16.004 +0000 [INFO] (embulk-output-executor-1): Running COPY from file tmp/fatbird_deliveries/14b18961-5c3f-4bca-86c3-67d899c176f6

[2016-03-28 08:09:20,774] {EmbulkWSPlugin.py:82} INFO - 2016-03-28 08:09:20.745 +0000 [INFO] (embulk-output-executor-1): Loaded file tmp/fatbird_deliveries/14b18961-5c3f-4bca-86c3-67d899c176f6 (4.74 seconds for COPY)

[2016-03-28 08:09:26,443] {EmbulkWSPlugin.py:82} INFO - 2016-03-28 08:09:26.394 +0000 [INFO] (0018:task-0000): Fetched 1,024,000 rows.

[2016-03-28 08:09:27,712] {EmbulkWSPlugin.py:82} INFO - 2016-03-28 08:09:27.694 +0000 [INFO] (0001:transaction): {done:  1 / 1, running: 0}

[2016-03-28 08:09:27,712] {EmbulkWSPlugin.py:82} INFO - 2016-03-28 08:09:27.701 +0000 [INFO] (0001:cleanup): Connecting to jdbc:postgresql://redshift-analytics.nodemodo.com:5439/dev options {user=root, loglevel=2, tcpKeepAlive=true, loginTimeout=300, socketTimeout=1800}

[2016-03-28 08:09:27,712] {EmbulkWSPlugin.py:82} INFO - 2016-03-28 08:09:27.706 +0000 [INFO] (0001:cleanup): SQL: SET search_path TO "fatbird"

[2016-03-28 08:09:27,712] {EmbulkWSPlugin.py:82} INFO - 2016-03-28 08:09:27.708 +0000 [INFO] (0001:cleanup): > 0.00 seconds

[2016-03-28 08:09:27,712] {EmbulkWSPlugin.py:82} INFO - 2016-03-28 08:09:27.708 +0000 [INFO] (0001:cleanup): SQL: DROP TABLE IF EXISTS "deliveries_511f0e540_bl_tmp000"

[2016-03-28 08:09:29,230] {EmbulkWSPlugin.py:82} INFO - 2016-03-28 08:09:29.189 +0000 [INFO] (0001:cleanup): > 1.48 seconds

[2016-03-28 08:09:29,230] {EmbulkWSPlugin.py:82} INFO - 2016-03-28 08:09:29.190 +0000 [INFO] (0001:cleanup): SQL: DROP TABLE IF EXISTS "deliveries_511f0e540_bl_tmp001"

[2016-03-28 08:09:31,645] {EmbulkWSPlugin.py:82} INFO - 2016-03-28 08:09:31.612 +0000 [INFO] (0001:cleanup): > 2.42 seconds

[2016-03-28 08:09:31,645] {EmbulkWSPlugin.py:82} INFO - 2016-03-28 08:09:31.613 +0000 [INFO] (0001:cleanup): SQL: DROP TABLE IF EXISTS "deliveries_511f0e540_bl_tmp002"

[2016-03-28 08:09:33,313] {EmbulkWSPlugin.py:82} INFO - 2016-03-28 08:09:33.305 +0000 [INFO] (0001:cleanup): > 1.69 seconds

[2016-03-28 08:09:33,314] {EmbulkWSPlugin.py:82} INFO - 2016-03-28 08:09:33.305 +0000 [INFO] (0001:cleanup): SQL: DROP TABLE IF EXISTS "deliveries_511f0e540_bl_tmp003"

[2016-03-28 08:09:34,581] {EmbulkWSPlugin.py:82} INFO - 2016-03-28 08:09:34.545 +0000 [INFO] (0001:cleanup): > 1.24 seconds

[2016-03-28 08:09:34,581] {EmbulkWSPlugin.py:82} INFO - org.embulk.exec.PartialExecutionException: java.lang.IllegalArgumentException: Self-suppression not permitted

[2016-03-28 08:09:34,581] {EmbulkWSPlugin.py:82} INFO - 	at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(org/embulk/exec/BulkLoader.java:363)

[2016-03-28 08:09:34,581] {EmbulkWSPlugin.py:82} INFO - 	at org.embulk.exec.BulkLoader.doRun(org/embulk/exec/BulkLoader.java:572)

[2016-03-28 08:09:34,582] {EmbulkWSPlugin.py:82} INFO - 	at org.embulk.exec.BulkLoader.access$000(org/embulk/exec/BulkLoader.java:33)

[2016-03-28 08:09:34,582] {EmbulkWSPlugin.py:82} INFO - 	at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:374)

[2016-03-28 08:09:34,582] {EmbulkWSPlugin.py:82} INFO - 	at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:370)

[2016-03-28 08:09:34,582] {EmbulkWSPlugin.py:82} INFO - 	at org.embulk.spi.Exec.doWith(org/embulk/spi/Exec.java:25)

[2016-03-28 08:09:34,582] {EmbulkWSPlugin.py:82} INFO - 	at org.embulk.exec.BulkLoader.run(org/embulk/exec/BulkLoader.java:370)

[2016-03-28 08:09:34,582] {EmbulkWSPlugin.py:82} INFO - 	at org.embulk.EmbulkEmbed.run(org/embulk/EmbulkEmbed.java:180)

[2016-03-28 08:09:34,582] {EmbulkWSPlugin.py:82} INFO - 	at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)

[2016-03-28 08:09:34,582] {EmbulkWSPlugin.py:82} INFO - 	at RUBY.run(/opt/embulk/bin/embulk!/embulk/runner.rb:84)

[2016-03-28 08:09:34,582] {EmbulkWSPlugin.py:82} INFO - 	at RUBY.run(/opt/embulk/bin/embulk!/embulk/command/embulk_run.rb:306)

[2016-03-28 08:09:34,582] {EmbulkWSPlugin.py:82} INFO - 	at RUBY.<top>(/opt/embulk/bin/embulk!/embulk/command/embulk_main.rb:2)

[2016-03-28 08:09:34,582] {EmbulkWSPlugin.py:82} INFO - 	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:937)

[2016-03-28 08:09:34,582] {EmbulkWSPlugin.py:82} INFO - 	at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1)

[2016-03-28 08:09:34,582] {EmbulkWSPlugin.py:82} INFO - 	at opt.embulk.bin.embulk.embulk.command.embulk_bundle.<top>(file:/opt/embulk/bin/embulk!/embulk/command/embulk_bundle.rb:51)

[2016-03-28 08:09:34,583] {EmbulkWSPlugin.py:82} INFO - 	at java.lang.invoke.MethodHandle.invokeWithArguments(java/lang/invoke/MethodHandle.java:627)

[2016-03-28 08:09:34,583] {EmbulkWSPlugin.py:82} INFO - 	at org.embulk.cli.Main.main(org/embulk/cli/Main.java:23)

[2016-03-28 08:09:34,583] {EmbulkWSPlugin.py:82} INFO - Caused by: java.lang.IllegalArgumentException: Self-suppression not permitted

[2016-03-28 08:09:34,583] {EmbulkWSPlugin.py:82} INFO - 	at java.lang.Throwable.addSuppressed(Throwable.java:1043)

[2016-03-28 08:09:34,583] {EmbulkWSPlugin.py:82} INFO - 	at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.runInputTask(LocalExecutorPlugin.java:304)

[2016-03-28 08:09:34,583] {EmbulkWSPlugin.py:82} INFO - 	at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.access$000(LocalExecutorPlugin.java:212)

[2016-03-28 08:09:34,583] {EmbulkWSPlugin.py:82} INFO - 	at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor$1.call(LocalExecutorPlugin.java:257)

[2016-03-28 08:09:34,583] {EmbulkWSPlugin.py:82} INFO - 	at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor$1.call(LocalExecutorPlugin.java:253)

[2016-03-28 08:09:34,583] {EmbulkWSPlugin.py:82} INFO - 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

[2016-03-28 08:09:34,583] {EmbulkWSPlugin.py:82} INFO - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)

[2016-03-28 08:09:34,583] {EmbulkWSPlugin.py:82} INFO - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)

[2016-03-28 08:09:34,583] {EmbulkWSPlugin.py:82} INFO - 	at java.lang.Thread.run(Thread.java:745)

[2016-03-28 08:09:34,583] {EmbulkWSPlugin.py:82} INFO - 	Suppressed: java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: Load into table 'deliveries_511f0e540_bl_tmp002' failed.  Check 'stl_load_errors' system table for details.

[2016-03-28 08:09:34,583] {EmbulkWSPlugin.py:82} INFO - 		at org.embulk.output.jdbc.AbstractJdbcOutputPlugin$PluginPageOutput.add(AbstractJdbcOutputPlugin.java:900)

[2016-03-28 08:09:34,583] {EmbulkWSPlugin.py:82} INFO - 		at org.embulk.exec.LocalExecutorPlugin$ScatterTransactionalPageOutput$OutputWorker.call(LocalExecutorPlugin.java:393)

[2016-03-28 08:09:34,583] {EmbulkWSPlugin.py:82} INFO - 		at org.embulk.exec.LocalExecutorPlugin$ScatterTransactionalPageOutput$OutputWorker.call(LocalExecutorPlugin.java:318)

[2016-03-28 08:09:34,583] {EmbulkWSPlugin.py:82} INFO - 		... 4 more

[2016-03-28 08:09:34,583] {EmbulkWSPlugin.py:82} INFO - 	Caused by: org.postgresql.util.PSQLException: ERROR: Load into table 'deliveries_511f0e540_bl_tmp002' failed.  Check 'stl_load_errors' system table for details.

[2016-03-28 08:09:34,583] {EmbulkWSPlugin.py:82} INFO - 		at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2182)

[2016-03-28 08:09:34,584] {EmbulkWSPlugin.py:82} INFO - 		at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1911)

[2016-03-28 08:09:34,584] {EmbulkWSPlugin.py:82} INFO - 		at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:173)

[2016-03-28 08:09:34,584] {EmbulkWSPlugin.py:82} INFO - 		at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:645)

[2016-03-28 08:09:34,584] {EmbulkWSPlugin.py:82} INFO - 		at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:481)

[2016-03-28 08:09:34,584] {EmbulkWSPlugin.py:82} INFO - 		at org.postgresql.jdbc2.AbstractJdbc2Statement.executeUpdate(AbstractJdbc2Statement.java:409)

[2016-03-28 08:09:34,584] {EmbulkWSPlugin.py:82} INFO - 		at org.embulk.output.redshift.RedshiftOutputConnection.runCopy(RedshiftOutputConnection.java:117)

[2016-03-28 08:09:34,584] {EmbulkWSPlugin.py:82} INFO - 		at org.embulk.output.redshift.RedshiftCopyBatchInsert$UploadAndCopyTask.call(RedshiftCopyBatchInsert.java:178)

[2016-03-28 08:09:34,584] {EmbulkWSPlugin.py:82} INFO - 		at org.embulk.output.redshift.RedshiftCopyBatchInsert.flush(RedshiftCopyBatchInsert.java:92)

[2016-03-28 08:09:34,584] {EmbulkWSPlugin.py:82} INFO - 		at org.embulk.output.jdbc.AbstractJdbcOutputPlugin$PluginPageOutput.add(AbstractJdbcOutputPlugin.java:897)

[2016-03-28 08:09:34,584] {EmbulkWSPlugin.py:82} INFO - 		... 6 more

[2016-03-28 08:09:34,584] {EmbulkWSPlugin.py:82} INFO - 	[CIRCULAR REFERENCE:java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: Load into table 'deliveries_511f0e540_bl_tmp002' failed.  Check 'stl_load_errors' system table for details.]

[2016-03-28 08:09:34,584] {EmbulkWSPlugin.py:82} INFO - 

[2016-03-28 08:09:34,584] {EmbulkWSPlugin.py:82} INFO - Error: java.lang.IllegalArgumentException: Self-suppression not permitted

**Comment by hiroyuki-sato** [comment]
I googled "Check 'stl_load_errors' system table for details".
This text found in your log file.

Are you using Amazon Redshift?
Do you use redshift plugin? (not postgresql)?
Can you show me your configuration file?

It seems this link might be useful. 
http://docs.aws.amazon.com/redshift/latest/dg/r_STL_LOAD_ERRORS.html

Regards.

**Comment by lance-edmodo** [comment]
Hi-

Yes, thanks, writing to Redshift with the Redshift plugin. The problem turned out to be a text field that was longer than 65k.

But, the self-suppression error means that the Embulk code is somewhere tripping over an obscure problem with the Java 7 try-with-resources feature.
