### ISSUE TITLE
org.embulk.spi.TempFileException: java.io.IOException: No such file or directory

### ISSUE THREAD

**Issue by sonots** [embulk/embulk#423]
I got following errors with `json_keyfile`.`content` option of embulk-input-gcs:

```
Caused by: org.embulk.spi.TempFileException: java.io.IOException: No such file or directory
    at org.embulk.spi.TempFileSpace.createTempFile(TempFileSpace.java:42)
    at org.embulk.spi.TempFileSpace.createTempFile(TempFileSpace.java:30)
    at org.embulk.spi.TempFileSpace.createTempFile(TempFileSpace.java:25)
    at org.embulk.spi.unit.LocalFile.getPath(LocalFile.java:76)
    at org.embulk.spi.unit.LocalFile.getPath(LocalFile.java:70)
    at org.embulk.input.gcs.GcsFileInputPlugin$1.apply(GcsFileInputPlugin.java:208)
    at org.embulk.input.gcs.GcsFileInputPlugin$1.apply(GcsFileInputPlugin.java:205)
    at com.google.common.base.Present.transform(Present.java:71)
    at org.embulk.input.gcs.GcsFileInputPlugin.newGcsAuth(GcsFileInputPlugin.java:147)
    at org.embulk.input.gcs.GcsFileInputPlugin.transaction(GcsFileInputPlugin.java:132)
    at org.embulk.spi.FileInputRunner.transaction(FileInputRunner.java:65)
    at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:513)
    at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:33)
    at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:374)
    at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:370)
    at org.embulk.spi.Exec.doWith(Exec.java:25)
```

It looks this error is occurring at this line https://github.com/embulk/embulk/blob/11a9fc26abfb34eca37a6b379d8c87f773b4cfdb/embulk-core/src/main/java/org/embulk/spi/TempFileSpace.java#L40.

It seems that the error is happening because `/tmp/embulk` is already created by somebody else (It was actually me, but I ran embulk as a root before for my experiments, and it was the root cause).

```
# ls -ld /tmp/embulk
drwxr-xr-x 3 root root 4096  4月 27 00:06 2016 /tmp/embulk
```

What I request is:

1. Want to get PermissionError at https://github.com/embulk/embulk/blob/11a9fc26abfb34eca37a6b379d8c87f773b4cfdb/embulk-core/src/main/java/org/embulk/spi/TempFileSpace.java#L37 so that we can find the root cause easily
2. Want to have `tmp` directory for each user to avoid this situations that embulk is ran by two or more users.

**Comment by sutoh** [comment]
👍

**Comment by hiroyuki-sato** [comment]
Might this command help in some situation?. (Temporary workaround)

```
embulk "-J -Djava.io.tmpdir=tmp/" run test.yml
```

Reference: [Qiita](http://qiita.com/toru-takahashi/items/27a46879a2093a3b37a8) (Japanese text).
