### ISSUE TITLE
Embulk rarely raise IOException even if the filename doesn't match ``path_prefix`` file pattern

### ISSUE THREAD

**Issue by hiroyuki-sato** [embulk/embulk#455]
For future discussion, 

An input data write periodically to ``dir A`` by the fluentd out_file plugin.
Embulk read it from that directory. 

If this case,   Embulk  rarely raises the following Exception.
Even if the filename doesn't match ``path_prefix`` file pattern. 

```
Java.lang.RuntimeException: Failed get a list of local files at '/LOG_FILES'
LocalFileInputPlugin.listFiles(http://LocalFileInputPlugin.java:171 )
```

Maybe this is because Embulk uses java.nio.file.Files.
Because It call ``preVisitDirectory(Path path, BasicFileAttributes attrs)`` method.

https://github.com/embulk/embulk/blob/master/embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java#L125

It needs to call multiple systemcalls for getting path and file attribute.

If file moves after the first systemcall, It raises IOException, 

https://github.com/embulk/embulk/blob/master/embulk-standards/src/main/java/org/embulk/standards/LocalFileInputPlugin.java#L170

IMO, I recommend him to move the source file to Embulk source directory after log file create.

But If Embulk handles this case, Embulk become robust bulk loader. 

[Original discussion](https://twitter.com/isoparametric/status/757108745017040899) (Japanese)

**Comment by isoparametric** [comment]
Exception.
```
 java.lang.RuntimeException: Failed get a list of local files at '/LOG_FILES'
	at org.embulk.standards.LocalFileInputPlugin.listFiles(LocalFileInputPlugin.java:171)
	at org.embulk.standards.LocalFileInputPlugin.transaction(LocalFileInputPlugin.java:63)
	at org.embulk.spi.FileInputRunner.transaction(FileInputRunner.java:65)
	at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:513)
	at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:33)
	at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:374)
	at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:370)
	at org.embulk.spi.Exec.doWith(Exec.java:25)
	at org.embulk.exec.BulkLoader.run(BulkLoader.java:370)
	at org.embulk.EmbulkEmbed.runResumable(EmbulkEmbed.java:208)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:452)
	at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:313)
	at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:45)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:313)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:316)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:140)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:126)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:273)
	at org.jruby.runtime.callsite.CachingCallSite.callBlock(CachingCallSite.java:79)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:83)
	at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:414)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:348)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:86)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:210)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:196)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:197)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:313)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:316)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
	at org.jruby.ir.interpreter.Interpreter.INTERPRET_ROOT(Interpreter.java:112)
	at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:99)
	at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:35)
	at org.jruby.ir.IRTranslator.execute(IRTranslator.java:42)
	at org.jruby.Ruby.runInterpreter(Ruby.java:833)
	at org.jruby.Ruby.loadFile(Ruby.java:2905)
	at org.jruby.runtime.load.LibrarySearcher$ResourceLibrary.load(LibrarySearcher.java:235)
	at org.jruby.runtime.load.LibrarySearcher$FoundLibrary.load(LibrarySearcher.java:34)
	at org.jruby.runtime.load.LoadService.tryLoadingLibraryOrScript(LoadService.java:900)
	at org.jruby.runtime.load.LoadService.smartLoadInternal(LoadService.java:541)
	at org.jruby.runtime.load.LoadService.requireCommon(LoadService.java:426)
	at org.jruby.runtime.load.LoadService.require(LoadService.java:392)
	at org.jruby.RubyKernel.requireCommon(RubyKernel.java:944)
	at org.jruby.RubyKernel.require19(RubyKernel.java:937)
	at org.jruby.RubyKernel$INVOKER$s$1$0$require19.call(RubyKernel$INVOKER$s$1$0$require19.gen)
	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodOneOrNBlock.call(JavaMethod.java:380)
	at org.jruby.internal.runtime.methods.AliasMethod.call(AliasMethod.java:61)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:313)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:316)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:77)
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:86)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:210)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:196)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:197)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:313)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
	at usr.bin.embulk.embulk.command.embulk_bundle.invokeOther66:require(file:/usr/bin/embulk!/embulk/command/embulk_bundle.rb)
	at usr.bin.embulk.embulk.command.embulk_bundle.RUBY$script(file:/usr/bin/embulk!/embulk/command/embulk_bundle.rb:51)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.jruby.ir.Compiler$1.load(Compiler.java:111)
	at org.jruby.Ruby.runScript(Ruby.java:817)
	at org.jruby.Ruby.runScript(Ruby.java:809)
	at org.jruby.Ruby.runNormally(Ruby.java:747)
	at org.jruby.Ruby.runFromMain(Ruby.java:569)
	at org.jruby.Main.doRunFromMain(Main.java:415)
	at org.jruby.Main.internalRun(Main.java:310)
	at org.jruby.Main.run(Main.java:239)
	at org.jruby.Main.main(Main.java:201)
	at org.embulk.cli.Main.main(Main.java:23)
Caused by: java.nio.file.NoSuchFileException: /LOG_FILES/Log.20160724_07.b53854ac5cad70e37
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
	at java.nio.file.FileTreeWalker.next(FileTreeWalker.java:372)
	at java.nio.file.Files.walkFileTree(Files.java:2706)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at org.embulk.standards.LocalFileInputPlugin.listFiles(LocalFileInputPlugin.java:123)
	... 76 more
```
