### ISSUE TITLE
[Feature request] guess sample modes for large files.

### ISSUE THREAD

**Issue by hiroyuki-sato** [embulk/embulk#476]
Related: https://github.com/embulk/embulk/pull/444

For a guess, some plugins need all of the data in a file. 
(ex. [embulk-parser-jsonpath](https://github.com/hiroyuki-sato/embulk-parser-jsonpath), Excel plugins..)

If an input file bigger than 32KB. The plugin raises an exception.

Ref: (Japanese text)
[Twitter #1](https://twitter.com/kompiro/status/779890193922789376)
[Twitter #2](https://twitter.com/kompiro/status/780198572188774401)

I think guess needs some modes. For example
- line: number of lines.  (Maybe fix this issue: https://github.com/embulk/embulk/issues/471)
- buffer: Now 32KB fixed size. It needs changeable.
- file: Instead of change buffer size 

It's already TODO in Source code. But an issue has not filed yet. 
https://github.com/embulk/embulk/blob/master/embulk-core/src/main/java/org/embulk/exec/SamplingParserPlugin.java#L93

**Comment by hiroyuki-sato** [comment]
`embulk preview` which uses CSV or Jsonl data sometimes raises the exception.
Because of it can't read the end of the line when the data boundary reached. 

The following cases are the same issue. 
* #471 
* [Twitter](https://twitter.com/yassan168/status/819793357819940866) (Japanese)

**Comment by hiroyuki-sato** [comment]
@muga 
You can reproduce this problem with this data.
https://gist.github.com/kakoni/a1dfaafb1de76f82df938a9ba4ba400e


```
embulk preview config.yml
2017-01-14 00:19:09.553 +0900: Embulk v0.8.15
2017-01-14 00:19:11.702 +0900 [INFO] (0001:preview): Listing local files at directory '.' filtering filename by prefix 'fail.csv'
2017-01-14 00:19:11.710 +0900 [INFO] (0001:preview): Loading files [fail.csv]
org.embulk.spi.DataException: Invalid record at line 39: 0000000,0000000,0000000,0000000,000,00,0,0,0,0,0,0,0,0,000000000000,00000000000000,0,0000,000000000000,00000000000000,0,0,0,0,0,00000000000,0000000000000000000000000000000000000000,0000,000000,00000000,00,00000,0000,0,00000,0000,0,00,0000000000,000000,0000,000000,0000,000000,0000,000000,0000,000000000000000000000000000000000000000000000000000000000000,0,00000,00000,0000000000,0000,0000000000,0,000000,0000,0000,0000,0000,000000,0000,00000,0000,0,00000,000000000000000000000000000000000000000000000000000,00,00,00,00,00000000000000000000000000000000000,00,000,0,000,000,000,000,000,000,000,00,00,0,00000000,00000000,00,000,0,00000,0,0000000,0000000,0,0,0,0,00000000000000,00000000000000,00000000000000,00000,0000,00000,0000,000,0000000,0000,0,0,0,0,0,0,0,0,000,0000,0000000,0000000,00000,0000000,00000000,00000,00000000,0000,0000000
	at org.embulk.standards.CsvParserPlugin.run(org/embulk/standards/CsvParserPlugin.java:368)
	at org.embulk.spi.FileInputRunner.run(org/embulk/spi/FileInputRunner.java:153)
	at org.embulk.exec.PreviewExecutor$2$1.run(org/embulk/exec/PreviewExecutor.java:122)
	at org.embulk.spi.util.Filters$RecursiveControl.transaction(org/embulk/spi/util/Filters.java:96)
	at org.embulk.spi.util.Filters.transaction(org/embulk/spi/util/Filters.java:49)
	at org.embulk.exec.PreviewExecutor$2.run(org/embulk/exec/PreviewExecutor.java:111)
	at org.embulk.spi.FileInputRunner$RunnerControl$1$1.run(org/embulk/spi/FileInputRunner.java:123)
	at org.embulk.standards.CsvParserPlugin.transaction(org/embulk/standards/CsvParserPlugin.java:225)
	at org.embulk.spi.FileInputRunner$RunnerControl$1.run(org/embulk/spi/FileInputRunner.java:117)
	at org.embulk.spi.util.Decoders$RecursiveControl.transaction(org/embulk/spi/util/Decoders.java:77)
	at org.embulk.spi.util.Decoders.transaction(org/embulk/spi/util/Decoders.java:33)
	at org.embulk.spi.FileInputRunner$RunnerControl.run(org/embulk/spi/FileInputRunner.java:114)
	at org.embulk.exec.BufferFileInputPlugin.transaction(org/embulk/exec/BufferFileInputPlugin.java:26)
	at org.embulk.spi.FileInputRunner.transaction(org/embulk/spi/FileInputRunner.java:65)
	at org.embulk.exec.PreviewExecutor.doPreview(org/embulk/exec/PreviewExecutor.java:108)
	at org.embulk.exec.PreviewExecutor.doPreview(org/embulk/exec/PreviewExecutor.java:98)
	at org.embulk.exec.PreviewExecutor.access$000(org/embulk/exec/PreviewExecutor.java:30)
	at org.embulk.exec.PreviewExecutor$1.run(org/embulk/exec/PreviewExecutor.java:70)
	at org.embulk.exec.PreviewExecutor$1.run(org/embulk/exec/PreviewExecutor.java:66)
	at org.embulk.spi.Exec.doWith(org/embulk/spi/Exec.java:25)
	at org.embulk.exec.PreviewExecutor.preview(org/embulk/exec/PreviewExecutor.java:66)
	at org.embulk.EmbulkEmbed.preview(org/embulk/EmbulkEmbed.java:169)
	at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:453)
	at org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:314)
	at RUBY.preview(/Users/hsato/.embulk/bin/embulk!/embulk/runner.rb:35)
	at RUBY.run(/Users/hsato/.embulk/bin/embulk!/embulk/command/embulk_run.rb:305)
	at RUBY.<main>(/Users/hsato/.embulk/bin/embulk!/embulk/command/embulk_main.rb:2)
	at org.jruby.Ruby.runInterpreter(org/jruby/Ruby.java:850)
	at org.jruby.Ruby.loadFile(org/jruby/Ruby.java:2976)
	at org.jruby.RubyKernel.requireCommon(org/jruby/RubyKernel.java:963)
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:956)
	at org.jruby.RubyKernel$INVOKER$s$1$0$require19.call(org/jruby/RubyKernel$INVOKER$s$1$0$require19.gen)
	at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1)
	at Users.hsato.$_dot_embulk.bin.embulk.embulk.command.embulk_bundle.invokeOther66:require(Users/hsato/$_dot_embulk/bin/embulk/embulk/command/file:/Users/hsato/.embulk/bin/embulk!/embulk/command/embulk_bundle.rb:51)
	at Users.hsato.$_dot_embulk.bin.embulk.embulk.command.embulk_bundle.<main>(file:/Users/hsato/.embulk/bin/embulk!/embulk/command/embulk_bundle.rb:51)
	at java.lang.invoke.MethodHandle.invokeWithArguments(java/lang/invoke/MethodHandle.java:627)
	at org.jruby.Ruby.runScript(org/jruby/Ruby.java:834)
	at org.jruby.Ruby.runNormally(org/jruby/Ruby.java:749)
	at org.jruby.Ruby.runNormally(org/jruby/Ruby.java:767)
	at org.jruby.Ruby.runFromMain(org/jruby/Ruby.java:580)
	at org.jruby.Main.doRunFromMain(org/jruby/Main.java:425)
	at org.jruby.Main.internalRun(org/jruby/Main.java:313)
	at org.jruby.Main.run(org/jruby/Main.java:242)
	at org.jruby.Main.main(org/jruby/Main.java:204)
	at org.embulk.cli.Main.main(org/embulk/cli/Main.java:23)
Caused by: org.embulk.standards.CsvTokenizer$TooFewColumnsException: Too few columns
	at org.embulk.standards.CsvTokenizer.nextColumn(CsvTokenizer.java:168)
	at org.embulk.standards.CsvTokenizer.nextColumnOrNull(CsvTokenizer.java:379)
	at org.embulk.standards.CsvParserPlugin$1.nextColumn(CsvParserPlugin.java:346)
	at org.embulk.standards.CsvParserPlugin$1.stringColumn(CsvParserPlugin.java:302)
	at org.embulk.spi.Column.visit(Column.java:58)
	at org.embulk.spi.Schema.visitColumns(Schema.java:81)
	at org.embulk.standards.CsvParserPlugin.run(CsvParserPlugin.java:259)
	at org.embulk.spi.FileInputRunner.run(FileInputRunner.java:153)
	at org.embulk.exec.PreviewExecutor$2$1.run(PreviewExecutor.java:122)
	at org.embulk.spi.util.Filters$RecursiveControl.transaction(Filters.java:96)
	at org.embulk.spi.util.Filters.transaction(Filters.java:49)
	at org.embulk.exec.PreviewExecutor$2.run(PreviewExecutor.java:111)
	at org.embulk.spi.FileInputRunner$RunnerControl$1$1.run(FileInputRunner.java:123)
	at org.embulk.standards.CsvParserPlugin.transaction(CsvParserPlugin.java:225)
	at org.embulk.spi.FileInputRunner$RunnerControl$1.run(FileInputRunner.java:117)
	at org.embulk.spi.util.Decoders$RecursiveControl.transaction(Decoders.java:77)
	at org.embulk.spi.util.Decoders.transaction(Decoders.java:33)
	at org.embulk.spi.FileInputRunner$RunnerControl.run(FileInputRunner.java:114)
	at org.embulk.exec.BufferFileInputPlugin.transaction(BufferFileInputPlugin.java:26)
	at org.embulk.spi.FileInputRunner.transaction(FileInputRunner.java:65)
	at org.embulk.exec.PreviewExecutor.doPreview(PreviewExecutor.java:108)
	at org.embulk.exec.PreviewExecutor.doPreview(PreviewExecutor.java:98)
	at org.embulk.exec.PreviewExecutor.access$000(PreviewExecutor.java:30)
	at org.embulk.exec.PreviewExecutor$1.run(PreviewExecutor.java:70)
	at org.embulk.exec.PreviewExecutor$1.run(PreviewExecutor.java:66)
	at org.embulk.spi.Exec.doWith(Exec.java:25)
	at org.embulk.exec.PreviewExecutor.preview(PreviewExecutor.java:66)
	at org.embulk.EmbulkEmbed.preview(EmbulkEmbed.java:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:453)
	at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:314)
	at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:46)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:90)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:214)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:200)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:205)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:358)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:195)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:324)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:197)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
	at org.jruby.ir.interpreter.Interpreter.INTERPRET_ROOT(Interpreter.java:112)
	at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:99)
	at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:35)
	at org.jruby.ir.IRTranslator.execute(IRTranslator.java:42)
	at org.jruby.Ruby.runInterpreter(Ruby.java:850)
	at org.jruby.Ruby.loadFile(Ruby.java:2976)
	at org.jruby.runtime.load.LibrarySearcher$ResourceLibrary.load(LibrarySearcher.java:243)
	at org.jruby.runtime.load.LibrarySearcher$FoundLibrary.load(LibrarySearcher.java:34)
	at org.jruby.runtime.load.LoadService.tryLoadingLibraryOrScript(LoadService.java:885)
	at org.jruby.runtime.load.LoadService.smartLoadInternal(LoadService.java:525)
	at org.jruby.runtime.load.LoadService.require(LoadService.java:396)
	at org.jruby.RubyKernel.requireCommon(RubyKernel.java:963)
	at org.jruby.RubyKernel.require19(RubyKernel.java:956)
	at org.jruby.RubyKernel$INVOKER$s$1$0$require19.call(RubyKernel$INVOKER$s$1$0$require19.gen)
	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodOneOrNBlock.call(JavaMethod.java:383)
	at org.jruby.internal.runtime.methods.AliasMethod.call(AliasMethod.java:61)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:161)
	at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
	at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
	at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)
	at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)
	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:197)
	at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)
	at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
	at Users.hsato.$_dot_embulk.bin.embulk.embulk.command.embulk_bundle.invokeOther66:require(file:/Users/hsato/.embulk/bin/embulk!/embulk/command/embulk_bundle.rb:51)
	at Users.hsato.$_dot_embulk.bin.embulk.embulk.command.embulk_bundle.RUBY$script(file:/Users/hsato/.embulk/bin/embulk!/embulk/command/embulk_bundle.rb:51)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.jruby.ir.Compiler$1.load(Compiler.java:111)
	at org.jruby.Ruby.runScript(Ruby.java:834)
	at org.jruby.Ruby.runNormally(Ruby.java:749)
	at org.jruby.Ruby.runNormally(Ruby.java:767)
	at org.jruby.Ruby.runFromMain(Ruby.java:580)
	at org.jruby.Main.doRunFromMain(Main.java:425)
	at org.jruby.Main.internalRun(Main.java:313)
	at org.jruby.Main.run(Main.java:242)
	at org.jruby.Main.main(Main.java:204)
	at org.embulk.cli.Main.main(Main.java:23)

Error: Invalid record at line 39: 0000000,0000000,0000000,0000000,000,00,0,0,0,0,0,0,0,0,000000000000,00000000000000,0,0000,000000000000,00000000000000,0,0,0,0,0,00000000000,0000000000000000000000000000000000000000,0000,000000,00000000,00,00000,0000,0,00000,0000,0,00,0000000000,000000,0000,000000,0000,000000,0000,000000,0000,000000000000000000000000000000000000000000000000000000000000,0,00000,00000,0000000000,0000,0000000000,0,000000,0000,0000,0000,0000,000000,0000,00000,0000,0,00000,000000000000000000000000000000000000000000000000000,00,00,00,00,00000000000000000000000000000000000,00,000,0,000,000,000,000,000,000,000,00,00,0,00000000,00000000,00,000,0,00000,0,0000000,0000000,0,0,0,0,00000000000000,00000000000000,00000000000000,00000,0000,00000,0000,000,0000000,0000,0,0,0,0,0,0,0,0,000,0000,0000000,0000000,00000,0000000,00000000,00000,00000000,0000,0000000
```

**Comment by knu** [comment]
I got hit by this too, scratching my head, double-checked the input file and my parser settings for a good fifteen minutes before figuring out what was actually going on.

It would be the best to improve the sampler, but for the moment I believe adding a message that goes like `Sampling the first <sampleSize> bytes for preview...` would greatly help users understand any error they might see.

**Comment by hiroyuki-sato** [comment]
Guess and Preview sample buffer size now configurable. 
http://www.embulk.org/docs/release/release-0.8.19.html
http://www.embulk.org/docs/built-in.html#id34

Thanks! @muga
