### ISSUE TITLE
Easy way to extract data from multiple data sources

### ISSUE THREAD

**Issue by Olaktal** [embulk/embulk#497]
Hello everyone,

I have an Excel file and I have to join data in this excel file to data stored in a MySQL db in order to store the result in an other excel file. 
Is there an easy and fast way to do that with embulk (= 1 yml file) ?
Or do I have to first import both data to 2 db tables and then extract the data crossed by a query to an excel file ? (3 YML files + one SQL statement to delete the 2 tables)

Thanks
Vincent

**Comment by hiroyuki-sato** [comment]
As far as I know, you can't load it with 1 yml file. 
The following plugins might help.

[embulk-filter-mysql](https://github.com/toyama0919/embulk-filter-mysql)
[embulk-filter-join_file](https://github.com/civitaspo/embulk-filter-join_file)

Best regards.

**Comment by frsyuki** [comment]
Related: #167 #206

**Comment by Olaktal** [comment]
Hi,

Thanks a lot for these links. I managed otherwise but these can be usefull :)

Best regards,
Vincent

**Comment by Olaktal** [comment]
Hi @frsyuki,

I'm trying to use embulk-filter-mysql but it doesn't work for me:

```
exec:
  min_output_tasks: 1
in:
  type: mysql
  host: ***
  user: ***
  password: ***
  database: ***
  port: ***
  query: |
    Select count(*) AS categoryid
    FROM vendeur
  filters:
    - type: mysql
      host: ***
      user: ***
      password: ***
      database: ***
      keep_input: true
      query: |
        SELECT *
        FROM table
        WHERE nb = ?I don't know i
      params:
        - categoryid
out:
  type: file
  path_prefix: ./export_data
  file_ext: csv
  formatter:
    type: csv
    delimiter: ";"
```

I should have 2 queries to be launched but I only have the first one as if the 'filters' part didn't exist.

The plugin example is made with an excel file as input so I don't know if it change anything ...
Any ideas ? @toyama0919 

Thanks

**Comment by hiroyuki-sato** [comment]
@Olaktal 

You have to write `filters` config on the same level `out`, `in` and `exec`.

Please try it. 

```yaml
in:
# ...
filters:
  - type: mysql
    host: ***
    user: ***
    password: ***
    database: ***
    keep_input: true
    query: |
      SELECT *
      FROM table
      WHERE nb = ?I don't know i
    params:
      - categoryid

```

**Comment by Olaktal** [comment]
Thx ! But now I have another issue:

```
org.embulk.exec.PartialExecutionException: org.jruby.exceptions.RaiseException: (RuntimeError)
        at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(org/embulk/exec/BulkLoader.java:373)
        at org.embulk.exec.BulkLoader.doRun(org/embulk/exec/BulkLoader.java:591)
        at org.embulk.exec.BulkLoader.access$000(org/embulk/exec/BulkLoader.java:33)
        at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:389)
        at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:385)
        at org.embulk.spi.Exec.doWith(org/embulk/spi/Exec.java:25)
        at org.embulk.exec.BulkLoader.run(org/embulk/exec/BulkLoader.java:385)
        at org.embulk.EmbulkEmbed.run(org/embulk/EmbulkEmbed.java:180)
        at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:606)
        at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:453)
        at org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:314)
        at RUBY.run(/home/ubuntu/.embulk/bin/embulk!/embulk/runner.rb:84)
        at RUBY.run(/home/ubuntu/.embulk/bin/embulk!/embulk/command/embulk_run.rb:307)
        at RUBY.<main>(/home/ubuntu/.embulk/bin/embulk!/embulk/command/embulk_main.rb:2)
        at org.jruby.Ruby.runInterpreter(org/jruby/Ruby.java:850)
        at org.jruby.Ruby.loadFile(org/jruby/Ruby.java:2976)
        at org.jruby.RubyKernel.requireCommon(org/jruby/RubyKernel.java:963)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:956)
        at org.jruby.RubyKernel$INVOKER$s$1$0$require19.call(org/jruby/RubyKernel$INVOKER$s$1$0$require19.gen)
        at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1)
        at home.ubuntu.$_dot_embulk.bin.embulk.embulk.command.embulk_bundle.invokeOther66:require(home/ubuntu/$_dot_embulk/bin/embulk/embulk/command/file:/home/ubuntu/.embulk/bin/embulk!/embulk/command/embulk_bundle.rb:51)
        at home.ubuntu.$_dot_embulk.bin.embulk.embulk.command.embulk_bundle.<main>(file:/home/ubuntu/.embulk/bin/embulk!/embulk/command/embulk_bundle.rb:51)
        at java.lang.invoke.MethodHandle.invokeWithArguments(java/lang/invoke/MethodHandle.java:599)
        at org.jruby.Ruby.runScript(org/jruby/Ruby.java:834)
        at org.jruby.Ruby.runNormally(org/jruby/Ruby.java:749)
        at org.jruby.Ruby.runNormally(org/jruby/Ruby.java:767)
        at org.jruby.Ruby.runFromMain(org/jruby/Ruby.java:580)
        at org.jruby.Main.doRunFromMain(org/jruby/Main.java:425)
        at org.jruby.Main.internalRun(org/jruby/Main.java:313)
        at org.jruby.Main.run(org/jruby/Main.java:242)
        at org.jruby.Main.main(org/jruby/Main.java:204)
        at org.embulk.cli.Main.main(org/embulk/cli/Main.java:23)
        Suppressed: java.lang.NullPointerException
                at org.embulk.exec.BulkLoader.doCleanup(BulkLoader.java:494)
                at org.embulk.exec.BulkLoader$3.run(BulkLoader.java:425)
                at org.embulk.exec.BulkLoader$3.run(BulkLoader.java:421)
                at org.embulk.spi.Exec.doWith(Exec.java:25)
                at org.embulk.exec.BulkLoader.cleanup(BulkLoader.java:421)
                at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:184)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:606)
                at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:453)
                at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:314)
                at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:46)
                at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)
                at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
                at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
                at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
                at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:90)
                at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:214)
                at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:200)
                at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:205)
                at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:358)
                at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:195)
                at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:324)
                at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
                at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
                at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)
                at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)
                at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:197)
                at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)
                at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
                at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
                at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
                at org.jruby.ir.interpreter.Interpreter.INTERPRET_ROOT(Interpreter.java:112)
                at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:99)
                at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:35)
                at org.jruby.ir.IRTranslator.execute(IRTranslator.java:42)
                at org.jruby.Ruby.runInterpreter(Ruby.java:850)
                at org.jruby.Ruby.loadFile(Ruby.java:2976)
                at org.jruby.runtime.load.LibrarySearcher$ResourceLibrary.load(LibrarySearcher.java:243)
                at org.jruby.runtime.load.LibrarySearcher$FoundLibrary.load(LibrarySearcher.java:34)
                at org.jruby.runtime.load.LoadService.tryLoadingLibraryOrScript(LoadService.java:885)
                at org.jruby.runtime.load.LoadService.smartLoadInternal(LoadService.java:525)
                at org.jruby.runtime.load.LoadService.require(LoadService.java:396)
                at org.jruby.RubyKernel.requireCommon(RubyKernel.java:963)
                at org.jruby.RubyKernel.require19(RubyKernel.java:956)
                at org.jruby.RubyKernel$INVOKER$s$1$0$require19.call(RubyKernel$INVOKER$s$1$0$require19.gen)
                at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodOneOrNBlock.call(JavaMethod.java:383)
                at org.jruby.internal.runtime.methods.AliasMethod.call(AliasMethod.java:61)
                at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:161)
                at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
                at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73)
                at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
                at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179)
                at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165)
                at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:197)
                at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338)
                at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163)
                at home.ubuntu.$_dot_embulk.bin.embulk.embulk.command.embulk_bundle.invokeOther66:require(file:/home/ubuntu/.embulk/bin/embulk!/embulk/command/embulk_bundle.rb:51)
                at home.ubuntu.$_dot_embulk.bin.embulk.embulk.command.embulk_bundle.RUBY$script(file:/home/ubuntu/.embulk/bin/embulk!/embulk/command/embulk_bundle.rb:51)
                at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:599)
                at org.jruby.ir.Compiler$1.load(Compiler.java:111)
                at org.jruby.Ruby.runScript(Ruby.java:834)
                at org.jruby.Ruby.runNormally(Ruby.java:749)
                at org.jruby.Ruby.runNormally(Ruby.java:767)
                at org.jruby.Ruby.runFromMain(Ruby.java:580)
                at org.jruby.Main.doRunFromMain(Main.java:425)
                at org.jruby.Main.internalRun(Main.java:313)
                at org.jruby.Main.run(Main.java:242)
                at org.jruby.Main.main(Main.java:204)
                at org.embulk.cli.Main.main(Main.java:23)
Caused by: org.jruby.exceptions.RaiseException: (RuntimeError)
        at RUBY.get_type(/home/ubuntu/.embulk/jruby/2.3.0/gems/embulk-filter-mysql-0.1.1/lib/embulk/filter/mysql.rb:79)
        at RUBY.block in transaction(/home/ubuntu/.embulk/jruby/2.3.0/gems/embulk-filter-mysql-0.1.1/lib/embulk/filter/mysql.rb:27)
        at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1734)
        at RUBY.transaction(/home/ubuntu/.embulk/jruby/2.3.0/gems/embulk-filter-mysql-0.1.1/lib/embulk/filter/mysql.rb:26)
        at RUBY.transaction(/home/ubuntu/.embulk/bin/embulk!/embulk/filter_plugin.rb:51)
        at RUBY.run(/home/ubuntu/.embulk/bin/embulk!/embulk/runner.rb:84)
        at RUBY.run(/home/ubuntu/.embulk/bin/embulk!/embulk/command/embulk_run.rb:307)
        at RUBY.<main>(/home/ubuntu/.embulk/bin/embulk!/embulk/command/embulk_main.rb:2)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:956)
        at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1)
        at home.ubuntu.$_dot_embulk.bin.embulk.embulk.command.embulk_bundle.<main>(file:/home/ubuntu/.embulk/bin/embulk!/embulk/command/embulk_bundle.rb:51)

Error: org.jruby.exceptions.RaiseException: (RuntimeError)
```

Nb: Now it only execute the query in the filter part
I tried to remove the exec part but I still have this issue :(

**Comment by hiroyuki-sato** [comment]
@Olaktal 

I'm not familiar about embulk-filter-mysql. 
**Maybe** you can't use `select *`. 
You need to specify a column explicitly. 

Note exception raise here. 
https://github.com/toyama0919/embulk-filter-mysql/blob/master/lib/embulk/filter/mysql.rb#L79

**Comment by hiroyuki-sato** [comment]
I tested on my environment.
It worked fine. 

```
MariaDB [embulk_test]> select * from user;
+----+-------+-----------+------------+
| id | name  | last_name | first_name |
+----+-------+-----------+------------+
|  1 | hsato | Hiroyuki  | Sato       |
+----+-------+-----------+------------+
```

test.txt

```
1
1
1
1
1
1
1
1
1
1
1
1
1
1
```

```yaml
in:
  type: file
  path_prefix: test
  parser:
    type: csv
    columns:
      - { name: id, type: long }
filters:
  - type: mysql
    host: localhost
    user: xxxxx
    password: xxxxx
    database: embulk_test
    keep_input: true
    query: |
      select name,first_name,last_name
        from user
       where id = ?
    params:
      - id

out:
  type: stdout
```



```
+---------+-------------+-------------------+------------------+
| id:long | name:string | first_name:string | last_name:string |
+---------+-------------+-------------------+------------------+
|       1 |       hsato |              Sato |         Hiroyuki |
|       1 |       hsato |              Sato |         Hiroyuki |
|       1 |       hsato |              Sato |         Hiroyuki |
|       1 |       hsato |              Sato |         Hiroyuki |
|       1 |       hsato |              Sato |         Hiroyuki |
|       1 |       hsato |              Sato |         Hiroyuki |
|       1 |       hsato |              Sato |         Hiroyuki |
|       1 |       hsato |              Sato |         Hiroyuki |
|       1 |       hsato |              Sato |         Hiroyuki |
|       1 |       hsato |              Sato |         Hiroyuki |
|       1 |       hsato |              Sato |         Hiroyuki |
|       1 |       hsato |              Sato |         Hiroyuki |
|       1 |       hsato |              Sato |         Hiroyuki |
|       1 |       hsato |              Sato |         Hiroyuki |
|       1 |       hsato |              Sato |         Hiroyuki |
|       1 |       hsato |              Sato |         Hiroyuki |
|       1 |       hsato |              Sato |         Hiroyuki |
|       1 |       hsato |              Sato |         Hiroyuki |
|       1 |       hsato |              Sato |         Hiroyuki |
|       1 |       hsato |              Sato |         Hiroyuki |
|       1 |       hsato |              Sato |         Hiroyuki |
|       1 |       hsato |              Sato |         Hiroyuki |
|       1 |       hsato |              Sato |         Hiroyuki |
|       1 |       hsato |              Sato |         Hiroyuki |
|       1 |       hsato |              Sato |         Hiroyuki |
|       1 |       hsato |              Sato |         Hiroyuki |
|       1 |       hsato |              Sato |         Hiroyuki |
+---------+-------------+-------------------+------------------+
```

**Comment by hiroyuki-sato** [comment]
I can use `select *` too.
Previous my post was wrong.

```
in:
  type: file
  path_prefix: test
  parser:
    type: csv
    columns:
      - { name: id, type: long }
filters:
  - type: mysql
    host: localhost
    user: root
    password: hsato1
    database: embulk_test
    keep_input: true
#      select name,first_name,last_name
    query: |
      select *
        from user
       where code = ?
    params:
      - id

out:
  type: stdout
```

**Comment by hiroyuki-sato** [comment]
embulk-filter-mysql support the following columns. 
Do you use another type column?. ie `geometry`

* TINY
* SHORT
* LONG
* DOUBLE
* FLOAT
* DATE
* DATETIME
* TIMESTAMP
* BLOB
* STRING
* VAR_STRING
* VARCHAR

**Comment by Olaktal** [comment]
Hi @hiroyuki-sato ,

Humm that's strange, I tried the following simple example like you and it failed. I tried without the filters part and I can read perfectly the csv file ...

```
in:
  type: file
  path_prefix: test
  parser:
    type: csv
    columns:
      - { name: id, type: long }
filters:
  - type: mysql
    host: ***
    user: **
    password: **
    database: **
    keep_input: true
    query: |
      select *
      from dim_platform
      where id = ?
    params:
      - id
out:
  type: stdout
```
Error:

```
2016-11-30 10:59:03.668 +0000 [INFO] (0001:transaction): Loaded plugin embulk-filter-mysql (0.1.1)
2016-11-30 10:59:03.696 +0000 [INFO] (0001:transaction): Listing local files at directory '.' filtering filename by prefix 'test'
2016-11-30 10:59:03.700 +0000 [INFO] (0001:transaction): Loading files [test.csv]
2016-11-30 10:59:03.858 +0000 [INFO] (0001:transaction): PREPARE SQL:
select *
from dim_platform
where id = ?

2016-11-30 10:59:03.909 +0000 [INFO] (0001:transaction): Using local thread executor with max_threads=8 / output tasks 4 = input tasks 1 * 4
2016-11-30 10:59:03.916 +0000 [INFO] (0001:transaction): {done:  0 / 1, running: 0}
2016-11-30 10:59:03.981 +0000 [INFO] (0001:transaction): {done:  1 / 1, running: 0}
org.embulk.exec.PartialExecutionException: java.lang.IllegalArgumentException: Multiple entries with same key: id=org.embulk.spi.util.dynamic.LongColumnSetter@7fee5394 and id=org.embulk.spi.util.dynamic.LongColumnSetter@77b15b29
        at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(org/embulk/exec/BulkLoader.java:373)
        at org.embulk.exec.BulkLoader.doRun(org/embulk/exec/BulkLoader.java:591)
        at org.embulk.exec.BulkLoader.access$000(org/embulk/exec/BulkLoader.java:33)
        at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:389)
        at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:385)
        at org.embulk.spi.Exec.doWith(org/embulk/spi/Exec.java:25)
        at org.embulk.exec.BulkLoader.run(org/embulk/exec/BulkLoader.java:385)
        at org.embulk.EmbulkEmbed.run(org/embulk/EmbulkEmbed.java:180)
        at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:606)
        at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:453)
        at org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:314)
        at RUBY.run(/home/ubuntu/.embulk/bin/embulk!/embulk/runner.rb:84)
        at RUBY.run(/home/ubuntu/.embulk/bin/embulk!/embulk/command/embulk_run.rb:307)
        at RUBY.<main>(/home/ubuntu/.embulk/bin/embulk!/embulk/command/embulk_main.rb:2)
        at org.jruby.Ruby.runInterpreter(org/jruby/Ruby.java:850)
        at org.jruby.Ruby.loadFile(org/jruby/Ruby.java:2976)
        at org.jruby.RubyKernel.requireCommon(org/jruby/RubyKernel.java:963)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:956)
        at org.jruby.RubyKernel$INVOKER$s$1$0$require19.call(org/jruby/RubyKernel$INVOKER$s$1$0$require19.gen)
        at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1)
        at home.ubuntu.$_dot_embulk.bin.embulk.embulk.command.embulk_bundle.invokeOther66:require(home/ubuntu/$_dot_embulk/bin/embulk/embulk/command/file:/home/ubuntu/.embulk/bin/embulk!/embulk/command/embulk_bundle.rb:51)
        at home.ubuntu.$_dot_embulk.bin.embulk.embulk.command.embulk_bundle.<main>(file:/home/ubuntu/.embulk/bin/embulk!/embulk/command/embulk_bundle.rb:51)
        at java.lang.invoke.MethodHandle.invokeWithArguments(java/lang/invoke/MethodHandle.java:599)
        at org.jruby.Ruby.runScript(org/jruby/Ruby.java:834)
        at org.jruby.Ruby.runNormally(org/jruby/Ruby.java:749)
        at org.jruby.Ruby.runNormally(org/jruby/Ruby.java:767)
        at org.jruby.Ruby.runFromMain(org/jruby/Ruby.java:580)
        at org.jruby.Main.doRunFromMain(org/jruby/Main.java:425)
        at org.jruby.Main.internalRun(org/jruby/Main.java:313)
        at org.jruby.Main.run(org/jruby/Main.java:242)
        at org.jruby.Main.main(org/jruby/Main.java:204)
        at org.embulk.cli.Main.main(org/embulk/cli/Main.java:23)
Caused by: java.lang.IllegalArgumentException: Multiple entries with same key: id=org.embulk.spi.util.dynamic.LongColumnSetter@7fee5394 and id=org.embulk.spi.util.dynamic.LongColumnSetter@77b15b29
        at com.google.common.collect.ImmutableMap.checkNoConflict(com/google/common/collect/ImmutableMap.java:150)
        at com.google.common.collect.RegularImmutableMap.checkNoConflictInBucket(com/google/common/collect/RegularImmutableMap.java:104)
        at com.google.common.collect.RegularImmutableMap.<init>(com/google/common/collect/RegularImmutableMap.java:70)
        at com.google.common.collect.ImmutableMap$Builder.build(com/google/common/collect/ImmutableMap.java:254)
        at org.embulk.spi.util.DynamicPageBuilder.<init>(org/embulk/spi/util/DynamicPageBuilder.java:79)
        at java.lang.reflect.Constructor.newInstance(java/lang/reflect/Constructor.java:526)
        at org.jruby.javasupport.JavaConstructor.newInstanceDirect(org/jruby/javasupport/JavaConstructor.java:246)
        at org.jruby.RubyClass.newInstance(org/jruby/RubyClass.java:1022)
        at org.jruby.RubyClass$INVOKER$i$newInstance.call(org/jruby/RubyClass$INVOKER$i$newInstance.gen)
        at RUBY.initialize(/home/ubuntu/.embulk/bin/embulk!/embulk/page_builder.rb:12)
        at org.jruby.RubyClass.newInstance(org/jruby/RubyClass.java:1008)
        at org.jruby.RubyClass$INVOKER$i$newInstance.call(org/jruby/RubyClass$INVOKER$i$newInstance.gen)
        at RUBY.open(/home/ubuntu/.embulk/bin/embulk!/embulk/filter_plugin.rb:63)
        at Embulk$$FilterPlugin$$JavaAdapter_1205927682.open(Embulk$$FilterPlugin$$JavaAdapter_1205927682.gen:13)
        at org.embulk.spi.util.Filters.open(org/embulk/spi/util/Filters.java:58)
        at org.embulk.exec.LocalExecutorPlugin$ScatterTransactionalPageOutput.openFilters(org/embulk/exec/LocalExecutorPlugin.java:461)
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.runInputTask(org/embulk/exec/LocalExecutorPlugin.java:284)
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.access$000(org/embulk/exec/LocalExecutorPlugin.java:212)
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor$1.call(org/embulk/exec/LocalExecutorPlugin.java:257)
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor$1.call(org/embulk/exec/LocalExecutorPlugin.java:253)
        at java.util.concurrent.FutureTask.run(java/util/concurrent/FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java/util/concurrent/ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java/util/concurrent/ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(java/lang/Thread.java:745)

Error: java.lang.IllegalArgumentException: Multiple entries with same key: id=org.embulk.spi.util.dynamic.LongColumnSetter@7fee5394 and id=org.embulk.spi.util.dynamic.LongColumnSetter@77b15b29
```

Any idea ?

**Comment by hiroyuki-sato** [comment]
@Olaktal 

You have ``id`` columns in the database table and embulk column.
That's why It raise exceptioin `Multiple entries with same key`
Please try to rename id column like the below.

```yaml
filters:
  - type: mysql
    host: localhost
    user: xxxxx
    password: xxxxx
    database: embulk_test
    keep_input: true
    query: |
      select *
        from user
       where code = ?
    params:
      - id
```

**Comment by Olaktal** [comment]
@hiroyuki-sato 
I tried but it didn't work :(
I don't think it analyze the query, It just replace the '?' by the param.

**Comment by hiroyuki-sato** [comment]
Huumm..

Could you tell me your environment?

* OS
* Embulk version
* MySQL version
* table schema. (create table or show columns info)
* embulk config.
* input data.

```
filters:
  - type: mysql
    host: localhost
    user: xxxxx
    password: xxxxx
    database: embulk_test
    keep_input: true
    query: |
      select *
        from user
       where code = ?
    params:
      - id
```

This config  replace ``select * from user where code = <embulk_id_column_value>`.

**Comment by Olaktal** [comment]
@hiroyuki-sato 

- OS:Ubuntu 14.04.4 LTS
- Embulk version: 0.8.15
- Mysql: version 10.1.19-MariaDB-1~wheezy
- Table schema:
CREATE TABLE dim_platform (id int NOT NULL AUTO_INCREMENT, version int, date_from datetime, date_to datetime, original_id varchar(2), label varchar(50), active int, PRIMARY KEY (id), INDEX idx_dim_platform_lookup (original_id), INDEX idx_dim_platform_label (label)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
- Embulk config ?
- Input data: a CSV file with 1 column and 2 rows with the same value: 1

```
in:
  type: file
  path_prefix: test
  parser:
    type: csv
    columns:
      - { name: id, type: long }
filters:
  - type: mysql
    host: ***
    user: ***
    password: ***
    database: ***
    keep_input: true
#      select name,first_name,last_name
    query: |
      select *
        from dim_platform
       where version = ?
    params:
      - id
out:
  type: stdout
```

**Comment by hiroyuki-sato** [comment]
@Olaktal 

Could you check the following output?

I tested on macOS. almost config is the same. 

* OS:macOS 10.12.1
* Embulk version: 0.8.15
* Mysql: version 10.1.19-MariaDB
* Table schema:
* CREATE TABLE dim_platform (id int NOT NULL AUTO_INCREMENT, version int, date_from datetime, date_to datetime, original_id varchar(2), label varchar(50), active int, PRIMARY KEY (id), INDEX idx_dim_platform_lookup (original_id), INDEX idx_dim_platform_label (label)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
* Embulk config : see below
* Input data: see below.


```
show columns from dim_platform;
+-------------+-------------+------+-----+---------+----------------+
| Field       | Type        | Null | Key | Default | Extra          |
+-------------+-------------+------+-----+---------+----------------+
| id          | int(11)     | NO   | PRI | NULL    | auto_increment |
| version     | int(11)     | YES  |     | NULL    |                |
| date_from   | datetime    | YES  |     | NULL    |                |
| date_to     | datetime    | YES  |     | NULL    |                |
| original_id | varchar(2)  | YES  | MUL | NULL    |                |
| label       | varchar(50) | YES  | MUL | NULL    |                |
| active      | int(11)     | YES  |     | NULL    |                |
+-------------+-------------+------+-----+---------+----------------+
7 rows in set (0.00 sec)
```

```
insert into dim_platform values(1,1,'2016-11-01','2016-11-30','1','label',1);
```

input data test.txt

```
1
1
1
```

embulk config. (with `select *`)

```yaml
in:
  type: file
  path_prefix: test
  parser:
    type: csv
    columns:
      - { name: code, type: long } # <-- change id to code
filters:
  - type: mysql
    host: localhost
    user: xxxxxx
    password: xxxxx
    database: embulk_test
    keep_input: true
    query: |
        select *
        from dim_platform
        where id = ?
    params:
      - code  # <-- change id to code

out:
  type: stdout
```

`embulk run` output.

```
1,1,1,2016-10-31 15:00:00.000000 +0000,2016-11-29 15:00:00.000000 +0000,1,label,1
1,1,1,2016-10-31 15:00:00.000000 +0000,2016-11-29 15:00:00.000000 +0000,1,label,1
1,1,1,2016-10-31 15:00:00.000000 +0000,2016-11-29 15:00:00.000000 +0000,1,label,1
```

preview. 

```
*************************** 1 ***************************
       code (     long) : 1
         id (     long) : 1
    version (     long) : 1
  date_from (timestamp) : 2016-10-31 15:00:00 UTC
    date_to (timestamp) : 2016-11-29 15:00:00 UTC
original_id (   string) : 1
      label (   string) : label
     active (     long) : 1
```

     

without `select *`

```yaml
in:
  type: file
  path_prefix: test
  parser:
    type: csv
    columns:
      - { name: id, type: long } # use column name id
filters:
  - type: mysql
    host: localhost
    user: xxxx
    password: xxxx
    database: embulk_test
    keep_input: true
    query: |
      select version,date_from,date_to,original_id,label,active # query without id
        from dim_platform
        where id = ?
    params:
      - id

out:
  type: stdout
```

```
1,1,2016-10-31 15:00:00.000000 +0000,2016-11-29 15:00:00.000000 +0000,1,label,1
1,1,2016-10-31 15:00:00.000000 +0000,2016-11-29 15:00:00.000000 +0000,1,label,1
1,1,2016-10-31 15:00:00.000000 +0000,2016-11-29 15:00:00.000000 +0000,1,label,1
```

```
*************************** 1 ***************************
         id (     long) : 1
    version (     long) : 1
  date_from (timestamp) : 2016-10-31 15:00:00 UTC
    date_to (timestamp) : 2016-11-29 15:00:00 UTC
original_id (   string) : 1
      label (   string) : label
     active (     long) : 1
```

**Comment by Olaktal** [comment]
Thanks @hiroyuki-sato I finally managed to make it work !
I already can see 2 major enhancement to this plugin:
 - It need to be compatible with other databases (postgres, redshift, ...)
 - Being able to use multiple time the filter in one yml file as follow

```
in:
  type: mysql
  host: ***
  user: ***
  password: ***
  database: ***
  port: 3307
  query: |
    select id_seller, platform_id 
    FROM colibri_sellers 
    LIMIT 10
filters:
  - type: mysql
    host: ***
    user: ***
    password: ***
    database: ***
    keep_input: true
    query: |
      select company_name,
        from dim_provider_v2
       where original_id = ?
    params:
      - id_seller
filters:
  - type: mysql
    host: ***
    user: ***
    password: ***
    database: ***
    keep_input: true
    query: |
      select label
        from dim_platform
       where original_id = ? and company = ?
    params:
      - platform_id
      - company_name
out:
  type: stdout
```
The output should contain the columns values as follow:

id_seller - platform_id - company_name - label

This should make embulk to be able to work like a traditional ELT with dataflow.
Do you how to do it otherwise right now ?
If not, do you know if it is possible to develop it ?

Thanks

**Comment by hiroyuki-sato** [comment]
IMO, Multiple filters aren't better idea.

Probably, load data into a database, replace with SQL command faster than a dbms-filter plugin. 

Anyway, The following is my ideas.

* Use [digdag](https://www.digdag.io) for ETL.
  * This software was originally written Embulk author. It has good integration with Embulk.
* Develop embulk plugin 
  * embulk-filter-postgrsql
  * embulk-filter-presto

**Comment by Olaktal** [comment]
Hi @hiroyuki-sato,

An SQL command is a good idea but I have to first get data from an SQL statement, then use these data to make another SQL query, etc etc
I need an "iterate" function like embulk-filter-mysql so I supose developping embulk filter postgresql plugin is the best choise.
I looked at the code of the filter-mysql plugin and it doesn't look easy for me :(
Thanks for the answer anyway !
Best regards

**Comment by hiroyuki-sato** [comment]
This is the off topic. If you want to know more detail, please contact me 
(hiroysato at gmail.com) or ask on digdag project. 

Digdag has the postgresql operator. You can use variable `${}` like the following. 

```sql
insert into dest_table where condition_name = ${xxx};.
```

[PostgreSQL operation](http://docs.digdag.io/operators.html#pg-postgresql-operations)

It has also `_loop` operator. So you might iterate many things.
