### ISSUE TITLE
Error occure FileNotFoundException File input plugin, if Just under symbolic link file.

### ISSUE THREAD

**Issue by toyama0919** [embulk/embulk#584]
Hello.

Error occure FileNotFoundException file input plugin, Just under symbolic link file.
We use Embulk v0.8.18.

`/apps/embulk-test/current/shared_generated` is symbolic link directory.

## NG
```
in:
  type: file
  path_prefix: /apps/embulk-test/current/shared_generated/test.csv
  parser:
    type: csv
    delimiter: ","
    columns:
      - {name: title, type: string }
      - {name: company_id, type: long }
      - {name: company_name, type: string }
      - {name: url, type: string }

```

But if Not Just under is OK.
This example is under symbolic link has subdirectory.

## OK

```
in:
  type: file
  path_prefix: /apps/embulk-test/current/shared_generated/subdirectory/test.csv
  parser:
    type: csv
    delimiter: ","
    columns:
      - {name: title, type: string }
      - {name: company_id, type: long }
      - {name: company_name, type: string }
      - {name: url, type: string }

```

## stacktrace
```
2017-03-30 11:35:18.013 +0900: Embulk v0.8.18
2017-03-30 11:35:21.258 +0900 [INFO] (0001:transaction): Listing local files at directory '/apps/embulk-test/current/shared_generated' filtering filename by prefix 'test.csv'
2017-03-30 11:35:21.268 +0900 [INFO] (0001:transaction): Loading files [/apps/embulk-test/current/shared_generated]
2017-03-30 11:35:21.385 +0900 [INFO] (0001:transaction): Using local thread executor with max_threads=8 / output tasks 4 = input tasks 1 * 4
2017-03-30 11:35:21.398 +0900 [INFO] (0001:transaction): {done:  0 / 1, running: 0}
2017-03-30 11:35:21.512 +0900 [INFO] (0001:transaction): {done:  1 / 1, running: 0}
org.embulk.exec.PartialExecutionException: java.lang.RuntimeException: java.io.FileNotFoundException: /apps/embulk-test/current/shared_generated (Is a directory)
  at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(org/embulk/exec/BulkLoader.java:373)
  at org.embulk.exec.BulkLoader.doRun(org/embulk/exec/BulkLoader.java:591)
  at org.embulk.exec.BulkLoader.access$000(org/embulk/exec/BulkLoader.java:33)
  at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:389)
  at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:385)
  at org.embulk.spi.Exec.doWith(org/embulk/spi/Exec.java:25)
  at org.embulk.exec.BulkLoader.run(org/embulk/exec/BulkLoader.java:385)
  at org.embulk.EmbulkEmbed.run(org/embulk/EmbulkEmbed.java:180)
  at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
  at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:453)
  at org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:314)
  at RUBY.run(uri:classloader:/embulk/runner.rb:84)
  at RUBY.run(uri:classloader:/embulk/command/embulk_run.rb:307)
  at RUBY.<main>(uri:classloader:/embulk/command/embulk_main.rb:2)
  at org.jruby.Ruby.runInterpreter(org/jruby/Ruby.java:850)
  at org.jruby.Ruby.loadFile(org/jruby/Ruby.java:2976)
  at org.jruby.RubyKernel.requireCommon(org/jruby/RubyKernel.java:963)
  at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:956)
  at org.jruby.RubyKernel$INVOKER$s$1$0$require19.call(org/jruby/RubyKernel$INVOKER$s$1$0$require19.gen)
  at Users.toyama_minus_h.bin.embulk.embulk.command.embulk_bundle.invokeOther35:require(Users/toyama_minus_h/bin/embulk/embulk/command/file:/Users/toyama-h/bin/embulk!/embulk/command/embulk_bundle.rb:30)
  at Users.toyama_minus_h.bin.embulk.embulk.command.embulk_bundle.<main>(file:/Users/toyama-h/bin/embulk!/embulk/command/embulk_bundle.rb:30)
  at java.lang.invoke.MethodHandle.invokeWithArguments(java/lang/invoke/MethodHandle.java:627)
  at org.jruby.Ruby.runScript(org/jruby/Ruby.java:834)
  at org.jruby.Ruby.runNormally(org/jruby/Ruby.java:749)
  at org.jruby.Ruby.runNormally(org/jruby/Ruby.java:767)
  at org.jruby.Ruby.runFromMain(org/jruby/Ruby.java:580)
  at org.jruby.Main.doRunFromMain(org/jruby/Main.java:425)
  at org.jruby.Main.internalRun(org/jruby/Main.java:313)
  at org.jruby.Main.run(org/jruby/Main.java:242)
  at org.jruby.Main.main(org/jruby/Main.java:204)
  at org.embulk.cli.Main.main(org/embulk/cli/Main.java:23)
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: /apps/embulk-test/current/shared_generated (Is a directory)
  at org.embulk.spi.util.InputStreamFileInput.nextFile(InputStreamFileInput.java:170)
  at org.embulk.spi.util.FileInputInputStream.nextFile(FileInputInputStream.java:27)
  at org.embulk.spi.util.LineDecoder.nextFile(LineDecoder.java:52)
  at org.embulk.standards.CsvTokenizer.nextFile(CsvTokenizer.java:108)
  at org.embulk.standards.CsvParserPlugin.run(CsvParserPlugin.java:242)
  at org.embulk.spi.FileInputRunner.run(FileInputRunner.java:153)
  at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.runInputTask(LocalExecutorPlugin.java:294)
  at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.access$000(LocalExecutorPlugin.java:212)
  at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor$1.call(LocalExecutorPlugin.java:257)
  at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor$1.call(LocalExecutorPlugin.java:253)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: /apps/embulk-test/current/shared_generated (Is a directory)
  at java.io.FileInputStream.open0(Native Method)
  at java.io.FileInputStream.open(FileInputStream.java:195)
  at java.io.FileInputStream.<init>(FileInputStream.java:138)
  at org.embulk.standards.LocalFileInputPlugin$2.open(LocalFileInputPlugin.java:188)
  at org.embulk.spi.util.InputStreamFileInput$OpenerProvider.openNext(InputStreamFileInput.java:74)
  at org.embulk.spi.util.InputStreamFileInput.nextFile(InputStreamFileInput.java:167)
  ... 13 more

```

**Comment by hiroyuki-sato** [comment]
@toyama0919 Please take a look #585
