### ISSUE TITLE
Debugging Liquid-4.0.0 Error

### ISSUE THREAD

**Issue by hiroyuki-sato** [embulk/embulk#635]
Now I'm debugging #627. And I found the difference between with `-b` and without `-b` option. 

I'm not sure how to fix this issue yet. 

## Summaries

`token.is_a?(Continue)` raise `const_missing` if `-b` options used. 

https://github.com/Shopify/liquid/blob/ad00998ef8a6722065e1e17476ac26aa715b84ed/lib/liquid/block_body.rb#L83

```ruby
def render(context)

    # ...

    begin
      # If we get an Interrupt that means the block must stop processing. An
      # Interrupt is any command that stops block execution such as {% break %}
      # or {% continue %}
      if token.is_a?(Continue) || token.is_a?(Break)  # <- The variable Continue return const_missing
        context.push_interrupt(token.interrupt)
        break
      end
```

## make debugging embulk package. 

* change branch [liquid_test](https://github.com/hiroyuki-sato/embulk/tree/liquid_test)
    * [diff](https://github.com/hiroyuki-sato/embulk/commit/3b67d2733173f2f01ccd4227bfdfe1aa7dbc9b65)
* change file [./embulk-core/build/gem/gems/liquid-4.0.0/lib/liquid/block_body.rb](https://gist.github.com/hiroyuki-sato/5443c71053fa71a365ee9e3f3b8d7aaf)
    * Just add `pp` method for output debug message.

```
./gradlew cli
./gradlew gemJRuby
```

## Create local gem server (only embulk)

```
% mkdir /tmp/embulk_test
% cd /tmp/embulk_test/
%  mkdir gems
%  cd gems/
```

```
%  cp ~/OpenProjects/embulk/embulk/pkg/embulk-0.8.21-java.gem .
%  cd ../
%  gem generate
Generating Marshal quick index gemspecs for 1 gems
.
Complete
Generated Marshal quick index gemspecs: 0.001s
Generating specs index
Generated specs index: 0.000s
Generating latest specs index
Generated latest specs index: 0.000s
Generating prerelease specs index
Generated prerelease specs index: 0.000s
Compressing indices
Compressed indices: 0.002s
```

```
.
|-- gems
|   `-- embulk-0.8.21-java.gem
|-- latest_specs.4.8
|-- latest_specs.4.8.gz
|-- prerelease_specs.4.8
|-- prerelease_specs.4.8.gz
|-- quick
|   `-- Marshal.4.8
|       `-- embulk-0.8.21-java.gemspec.rz
|-- specs.4.8
`-- specs.4.8.gz
```

```
%  python -m http.server 8000
```

## Prepare reprodude steps.

```
%  embulk mkbundle em2
%  embulk example sample
%  embulk guess sample/seed.yml -o config.yml
%  mv config.yml config.yml.liquid
```

## OK case (without `-b`)

```
~/OpenProjects/embulk/embulk/pkg/embulk-0.8.21.jar preview config.yml.liquid
2017-05-16 11:42:49.777 +0900: Embulk v0.8.21
"in:\n  type: file\n  path_prefix: /private/tmp/example/csv/sample_\n  decoders:\n  - {type: gzip}\n  parser:\n    charset: UTF-8\n    newline: LF\n    type: csv\n    delimiter: ','\n    quote: '\"'\n    escape: '\"'\n    null_string: 'NULL'\n    trim_if_not_quoted: false\n    skip_header_lines: 1\n    allow_extra_columns: false\n    allow_optional_columns: false\n    columns:\n    - {name: id, type: long}\n    - {name: account, type: long}\n    - {name: time, type: timestamp, format: '%Y-%m-%d %H:%M:%S'}\n    - {name: purchase, type: timestamp, format: '%Y%m%d'}\n    - {name: comment, type: string}\nout: {type: stdout}\n"
"Continue"
Liquid::Continue  # <- succeed to get variable Liquid::Continue 
"Break"
Liquid::Break
"bbbb"
"ccc"
"ddd"
"eee"
2017-05-16 11:42:51.376 +0900 [INFO] (0001:preview): Listing local files at directory '/private/tmp/example/csv' filtering filename by prefix 'sample_'
2017-05-16 11:42:51.379 +0900 [INFO] (0001:preview): "follow_symlinks" is set false. Note that symbolic links to directories are skipped.
2017-05-16 11:42:51.382 +0900 [INFO] (0001:preview): Loading files [/private/tmp/example/csv/sample_01.csv.gz]
2017-05-16 11:42:51.399 +0900 [INFO] (0001:preview): Try to read 32,768 bytes from input source
+---------+--------------+-------------------------+-------------------------+----------------------------+
| id:long | account:long |          time:timestamp |      purchase:timestamp |             comment:string |
+---------+--------------+-------------------------+-------------------------+----------------------------+
|       1 |       32,864 | 2015-01-27 19:23:49 UTC | 2015-01-27 00:00:00 UTC |                     embulk |
|       2 |       14,824 | 2015-01-27 19:01:23 UTC | 2015-01-27 00:00:00 UTC |               embulk jruby |
|       3 |       27,559 | 2015-01-28 02:20:02 UTC | 2015-01-28 00:00:00 UTC | Embulk "csv" parser plugin |
|       4 |       11,270 | 2015-01-29 11:54:36 UTC | 2015-01-29 00:00:00 UTC |                            |
+---------+--------------+-------------------------+-------------------------+----------------------------+
```

## NG case (with `-b`)

```
~/OpenProjects/embulk/embulk/pkg/embulk-0.8.21.jar preview -b em2 config.yml.liquid
2017-05-16 11:43:04.330 +0900: Embulk v0.8.21
"in:\n  type: file\n  path_prefix: /private/tmp/example/csv/sample_\n  decoders:\n  - {type: gzip}\n  parser:\n    charset: UTF-8\n    newline: LF\n    type: csv\n    delimiter: ','\n    quote: '\"'\n    escape: '\"'\n    null_string: 'NULL'\n    trim_if_not_quoted: false\n    skip_header_lines: 1\n    allow_extra_columns: false\n    allow_optional_columns: false\n    columns:\n    - {name: id, type: long}\n    - {name: account, type: long}\n    - {name: time, type: timestamp, format: '%Y-%m-%d %H:%M:%S'}\n    - {name: purchase, type: timestamp, format: '%Y%m%d'}\n    - {name: comment, type: string}\nout: {type: stdout}\n"
"Continue"
["org/jruby/RubyModule.java:3346:in `const_missing'",
 "uri:classloader:/liquid/block_body.rb:83:in `block in render'",
 "org/jruby/RubyArray.java:1734:in `each'",
 "uri:classloader:/liquid/block_body.rb:75:in `render'",
 "uri:classloader:/liquid/template.rb:208:in `block in render'",
 "uri:classloader:/liquid/template.rb:242:in `with_profiling'",
 "uri:classloader:/liquid/template.rb:207:in `render'",
 "uri:classloader:/embulk/runner.rb:154:in `run_liquid'",
 "uri:classloader:/embulk/runner.rb:129:in `read_config'",
 "uri:classloader:/embulk/runner.rb:32:in `preview'",
 "uri:classloader:/embulk/command/embulk_run.rb:267:in `run'",
 "uri:classloader:/embulk/command/embulk_main.rb:2:in `<main>'",
 "org/jruby/RubyKernel.java:956:in `require'",
 "file:/Users/hsato/OpenProjects/embulk/embulk/pkg/embulk-0.8.21.jar!/embulk/command/embulk_bundle.rb:30:in `<main>'"]
undefined method `line_number' for #<String:0x5503c7d>
    uri:classloader:/liquid/block_body.rb:113:in `block in render'
    org/jruby/RubyArray.java:1734:in `each'
    uri:classloader:/liquid/block_body.rb:75:in `render'
    uri:classloader:/liquid/template.rb:208:in `block in render'
    uri:classloader:/liquid/template.rb:242:in `with_profiling'
    uri:classloader:/liquid/template.rb:207:in `render'
    uri:classloader:/embulk/runner.rb:154:in `run_liquid'
    uri:classloader:/embulk/runner.rb:129:in `read_config'
    uri:classloader:/embulk/runner.rb:32:in `preview'
    uri:classloader:/embulk/command/embulk_run.rb:267:in `run'
    uri:classloader:/embulk/command/embulk_main.rb:2:in `<main>'
    org/jruby/RubyKernel.java:956:in `require'
    file:/Users/hsato/OpenProjects/embulk/embulk/pkg/embulk-0.8.21.jar!/embulk/command/embulk_bundle.rb:30:in `<main>'

Error: undefined method `line_number' for #<String:0x5503c7d>
```

**Comment by dmikurube** [comment]
@hiroyuki-sato Thanks for your efforts!

Hmmm, looks strange. We need to have a look, but I have no ideas so far. Did you see that only `Continue` is undefined, or others (like `Break`) are undefined as well?

**Comment by hiroyuki-sato** [comment]
@dmikurube 

`Break` is undefined as well. I'll let you know if I find something. 

I checked `Break` at first.
https://gist.github.com/hiroyuki-sato/5443c71053fa71a365ee9e3f3b8d7aaf#file-block_body-rb-L85 like the following

```ruby
require 'pp'
pp token
pp 'Break'
pp Break
pp 'Continue'
pp Continue
```

```
2017-05-16 13:50:30.266 +0900: Embulk v0.8.21
"in:\n  type: file\n  path_prefix: /private/tmp/example/csv/sample_\n  decoders:\n  - {type: gzip}\n  parser:\n    charset: UTF-8\n    newline: LF\n    type: csv\n    delimiter: ','\n    quote: '\"'\n    escape: '\"'\n    null_string: 'NULL'\n    trim_if_not_quoted: false\n    skip_header_lines: 1\n    allow_extra_columns: false\n    allow_optional_columns: false\n    columns:\n    - {name: id, type: long}\n    - {name: account, type: long}\n    - {name: time, type: timestamp, format: '%Y-%m-%d %H:%M:%S'}\n    - {name: purchase, type: timestamp, format: '%Y%m%d'}\n    - {name: comment, type: string}\nout: {type: stdout}\n"
"Break"
["org/jruby/RubyModule.java:3346:in `const_missing'",
 "uri:classloader:/liquid/block_body.rb:83:in `block in render'",
 "org/jruby/RubyArray.java:1734:in `each'",
 "uri:classloader:/liquid/block_body.rb:75:in `render'",
 "uri:classloader:/liquid/template.rb:208:in `block in render'",
 "uri:classloader:/liquid/template.rb:242:in `with_profiling'",
 "uri:classloader:/liquid/template.rb:207:in `render'",
 "uri:classloader:/embulk/runner.rb:154:in `run_liquid'",
 "uri:classloader:/embulk/runner.rb:129:in `read_config'",
 "uri:classloader:/embulk/runner.rb:32:in `preview'",
 "uri:classloader:/embulk/command/embulk_run.rb:267:in `run'",
 "uri:classloader:/embulk/command/embulk_main.rb:2:in `<main>'",
 "org/jruby/RubyKernel.java:956:in `require'",
 "file:/Users/hsato/OpenProjects/embulk/embulk/pkg/embulk-0.8.21.jar!/embulk/command/embulk_bundle.rb:30:in `<main>'"]
undefined method `line_number' for #<String:0x15371de2>
    uri:classloader:/liquid/block_body.rb:113:in `block in render'
    org/jruby/RubyArray.java:1734:in `each'
    uri:classloader:/liquid/block_body.rb:75:in `render'
    uri:classloader:/liquid/template.rb:208:in `block in render'
    uri:classloader:/liquid/template.rb:242:in `with_profiling'
    uri:classloader:/liquid/template.rb:207:in `render'
    uri:classloader:/embulk/runner.rb:154:in `run_liquid'
    uri:classloader:/embulk/runner.rb:129:in `read_config'
    uri:classloader:/embulk/runner.rb:32:in `preview'
    uri:classloader:/embulk/command/embulk_run.rb:267:in `run'
    uri:classloader:/embulk/command/embulk_main.rb:2:in `<main>'
    org/jruby/RubyKernel.java:956:in `require'
    file:/Users/hsato/OpenProjects/embulk/embulk/pkg/embulk-0.8.21.jar!/embulk/command/embulk_bundle.rb:30:in `<main>'

Error: undefined method `line_number' for #<String:0x15371de2>
```

**Comment by hiroyuki-sato** [comment]
@muga  @dmikurube 


I found the root cause. 

The 3.0.6 used `File.dirname(__FILE__)` for load tag classes. 
But, 4.0.0 use `__dir__`. Then it points to another location if `-b` options use. 

Liquid-3.0.6 [lib/liquid.rb](https://github.com/Shopify/liquid/blob/8d19fdde7f48347107632f91efb84526aa4972c4/lib/liquid.rb#L74)

```ruby
Dir[File.dirname(__FILE__) + '/liquid/tags/*.rb'].each { |f| require f }
```

Liquid-4.0.0 [lib/liquid.rb](https://github.com/Shopify/liquid/blob/ad00998ef8a6722065e1e17476ac26aa715b84ed/lib/liquid.rb#L79)

```ruby
Dir["#{__dir__}/liquid/tags/*.rb"].each { |f| require f }
```


### test code

```
require 'pp'
pp '*** __dir__ '
pp __dir__
pp Dir["#{__dir__}/liquid/tags/*.rb"]
Dir["#{__dir__}/liquid/tags/*.rb"].each { |f| require f }
```


## without (-b)

```
"*** __dir__ "
"/path/to/embulk/pkg/embulk-0.8.21.jar!"
["/path/to/embulk/pkg/embulk-0.8.21.jar!/liquid/tags/raw.rb",
 "/path/to/embulk/pkg/embulk-0.8.21.jar!/liquid/tags/unless.rb",
 "/path/to/embulk/pkg/embulk-0.8.21.jar!/liquid/tags/assign.rb",
 "/path/to/embulk/pkg/embulk-0.8.21.jar!/liquid/tags/break.rb",
 "/path/to/embulk/pkg/embulk-0.8.21.jar!/liquid/tags/include.rb",
 "/path/to/embulk/pkg/embulk-0.8.21.jar!/liquid/tags/comment.rb",
 "/path/to/embulk/pkg/embulk-0.8.21.jar!/liquid/tags/ifchanged.rb",
 "/path/to/embulk/pkg/embulk-0.8.21.jar!/liquid/tags/for.rb",
 "/path/to/embulk/pkg/embulk-0.8.21.jar!/liquid/tags/continue.rb",
 "/path/to/embulk/pkg/embulk-0.8.21.jar!/liquid/tags/cycle.rb",
 "/path/to/embulk/pkg/embulk-0.8.21.jar!/liquid/tags/decrement.rb",
 "/path/to/embulk/pkg/embulk-0.8.21.jar!/liquid/tags/table_row.rb",
 "/path/to/embulk/pkg/embulk-0.8.21.jar!/liquid/tags/increment.rb",
 "/path/to/embulk/pkg/embulk-0.8.21.jar!/liquid/tags/if.rb",
 "/path/to/embulk/pkg/embulk-0.8.21.jar!/liquid/tags/case.rb",
 "/path/to/embulk/pkg/embulk-0.8.21.jar!/liquid/tags/capture.rb"]
```


## with -b 

```
"*** __dir__ "
"/private/tmp/uri:classloader:"
[] # <-- empty
```

**Comment by hiroyuki-sato** [comment]
Work on #637.
