### ISSUE TITLE
JsonMappingException is raised when `taskSource.loadTask(PluginTask.class)` is called at `cleanup` method in Java FileOutputPlugin.

### ISSUE THREAD

**Issue by civitaspo** [embulk/embulk#658]
Hi maintainers, I found a big bug. I don't know why, but when `taskSource.loadTask(PluginTask.class)` is called at `cleanup` method in Java FileOutputPlugin, `JsonMappingException` is raised. I verified FileOutputPlugin and OutputPlugin and the error was raised only in FileOutputPlugin.

You can reproduce the error in this repository, see this: https://github.com/civitaspo/embulk-output-error_in_cleanup

The error log is as follows.

```
[embulk-output-error_in_cleanup] embulk run example/config.yml -Ilib
2017-05-31 19:57:19.452 +0900: Embulk v0.8.18
2017-05-31 19:57:20.792 +0900 [INFO] (0001:transaction): Loaded plugin embulk/output/error_in_cleanup from a load path
2017-05-31 19:57:20.816 +0900 [INFO] (0001:transaction): Listing local files at directory 'example' filtering filename by prefix 'data'
2017-05-31 19:57:20.819 +0900 [INFO] (0001:transaction): Loading files [example/data.csv]
2017-05-31 19:57:20.862 +0900 [INFO] (0001:transaction): Using local thread executor with max_threads=16 / output tasks 8 = input tasks 1 * 8
2017-05-31 19:57:20.884 +0900 [INFO] (0001:transaction): {done:  0 / 1, running: 0}
2017-05-31 19:57:21.041 +0900 [INFO] (0001:transaction): {done:  1 / 1, running: 0}
2017-05-31 19:57:21.053 +0900 [WARN] (0001:transaction): Commit succeeded but cleanup failed. Ignoring this exception.
java.lang.RuntimeException: com.fasterxml.jackson.databind.JsonMappingException: Field 'Option3' is required but not set
 at [Source: N/A; line: -1, column: -1]
        at com.google.common.base.Throwables.propagate(Throwables.java:160) ~[embulk:0.8.18]
        at org.embulk.config.ModelManager.readObject(ModelManager.java:51) ~[embulk:0.8.18]
        at org.embulk.config.DataSourceImpl.loadTask(DataSourceImpl.java:214) ~[embulk:0.8.18]
        at org.embulk.output.error_in_cleanup.ErrorInCleanupFileOutputPlugin.cleanup(ErrorInCleanupFileOutputPlugin.java:82) ~[na:na]
        at org.embulk.spi.FileOutputRunner.cleanup(FileOutputRunner.java:120) ~[embulk:0.8.18]
        at org.embulk.exec.BulkLoader.doCleanup(BulkLoader.java:508) [embulk:0.8.18]
        at org.embulk.exec.BulkLoader.cleanupCommittedTransaction(BulkLoader.java:723) [embulk:0.8.18]
        at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:578) [embulk:0.8.18]
        at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:33) [embulk:0.8.18]
        at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:389) [embulk:0.8.18]
        at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:385) [embulk:0.8.18]
        at org.embulk.spi.Exec.doWith(Exec.java:25) [embulk:0.8.18]
        at org.embulk.exec.BulkLoader.run(BulkLoader.java:385) [embulk:0.8.18]
        at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:180) [embulk:0.8.18]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
        at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:453) [embulk:0.8.18]
        at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:314) [embulk:0.8.18]
        at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:46) [embulk:0.8.18]
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338) [embulk:0.8.18]
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163) [embulk:0.8.18]
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315) [embulk:0.8.18]
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73) [embulk:0.8.18]
        at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:90) [embulk:0.8.18]
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:214) [embulk:0.8.18]
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:200) [embulk:0.8.18]
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:205) [embulk:0.8.18]
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:358) [embulk:0.8.18]
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:195) [embulk:0.8.18]
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:324) [embulk:0.8.18]
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73) [embulk:0.8.18]
        at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84) [embulk:0.8.18]
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179) [embulk:0.8.18]
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165) [embulk:0.8.18]
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:197) [embulk:0.8.18]
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338) [embulk:0.8.18]
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163) [embulk:0.8.18]
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315) [embulk:0.8.18]
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73) [embulk:0.8.18]
        at org.jruby.ir.interpreter.Interpreter.INTERPRET_ROOT(Interpreter.java:112) [embulk:0.8.18]
        at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:99) [embulk:0.8.18]
        at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:35) [embulk:0.8.18]
        at org.jruby.ir.IRTranslator.execute(IRTranslator.java:42) [embulk:0.8.18]
        at org.jruby.Ruby.runInterpreter(Ruby.java:850) [embulk:0.8.18]
        at org.jruby.Ruby.loadFile(Ruby.java:2976) [embulk:0.8.18]
        at org.jruby.runtime.load.LibrarySearcher$ResourceLibrary.load(LibrarySearcher.java:243) [embulk:0.8.18]
        at org.jruby.runtime.load.LibrarySearcher$FoundLibrary.load(LibrarySearcher.java:34) [embulk:0.8.18]
        at org.jruby.runtime.load.LoadService.tryLoadingLibraryOrScript(LoadService.java:885) [embulk:0.8.18]
        at org.jruby.runtime.load.LoadService.smartLoadInternal(LoadService.java:525) [embulk:0.8.18]
        at org.jruby.runtime.load.LoadService.require(LoadService.java:396) [embulk:0.8.18]
        at org.jruby.RubyKernel.requireCommon(RubyKernel.java:963) [embulk:0.8.18]
        at org.jruby.RubyKernel.require19(RubyKernel.java:956) [embulk:0.8.18]
        at org.jruby.RubyKernel$INVOKER$s$1$0$require19.call(RubyKernel$INVOKER$s$1$0$require19.gen) [embulk:0.8.18]
        at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodOneOrNBlock.call(JavaMethod.java:383) [embulk:0.8.18]
        at org.jruby.internal.runtime.methods.AliasMethod.call(AliasMethod.java:61) [embulk:0.8.18]
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:161) [embulk:0.8.18]
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315) [embulk:0.8.18]
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73) [embulk:0.8.18]
        at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84) [embulk:0.8.18]
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179) [embulk:0.8.18]
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165) [embulk:0.8.18]
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:197) [embulk:0.8.18]
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338) [embulk:0.8.18]
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163) [embulk:0.8.18]
        at Users.takahiro_dot_nakayama.bin.embulk.embulk.command.embulk_bundle.invokeOther66:require(file:/Users/takahiro.nakayama/bin/embulk!/embulk/command/embulk_bundle.rb:51) [embulk:na]
        at Users.takahiro_dot_nakayama.bin.embulk.embulk.command.embulk_bundle.RUBY$script(file:/Users/takahiro.nakayama/bin/embulk!/embulk/command/embulk_bundle.rb:51) [embulk:na]
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627) [na:1.8.0_131]
        at org.jruby.ir.Compiler$1.load(Compiler.java:111) [embulk:0.8.18]
        at org.jruby.Ruby.runScript(Ruby.java:834) [embulk:0.8.18]
        at org.jruby.Ruby.runNormally(Ruby.java:749) [embulk:0.8.18]
        at org.jruby.Ruby.runNormally(Ruby.java:767) [embulk:0.8.18]
        at org.jruby.Ruby.runFromMain(Ruby.java:580) [embulk:0.8.18]
        at org.jruby.Main.doRunFromMain(Main.java:425) [embulk:0.8.18]
        at org.jruby.Main.internalRun(Main.java:313) [embulk:0.8.18]
        at org.jruby.Main.run(Main.java:242) [embulk:0.8.18]
        at org.jruby.Main.main(Main.java:204) [embulk:0.8.18]
        at org.embulk.cli.Main.main(Main.java:23) [embulk:0.8.18]
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Field 'Option3' is required but not set
 at [Source: N/A; line: -1, column: -1]
        at org.embulk.config.TaskSerDe$TaskDeserializer.deserialize(TaskSerDe.java:181) ~[embulk:0.8.18]
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3534) ~[embulk:0.8.18]
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1870) ~[embulk:0.8.18]
        at org.embulk.config.ModelManager.readObject(ModelManager.java:49) ~[embulk:0.8.18]
        ... 77 common frames omitted
2017-05-31 19:57:21.058 +0900 [INFO] (main): Committed.
2017-05-31 19:57:21.058 +0900 [INFO] (main): Next config diff: {"in":{"last_path":"example/data.csv"},"out":{}}
```

**Comment by civitaspo** [comment]
We found the error also occurs in FileInputPlugin. (thx @hiroyuki-sato https://twitter.com/hiroysato/status/869903800118657024)
I also create a FileInputPlugin case: https://github.com/civitaspo/embulk-input-error_in_cleanup

**Comment by muga** [comment]
@civitaspo Thank you for reporting. I could reproduce this error. It seems that we need special care for `FileOutputPlugin` to deserialize the `taskSource` in `cleanup` method. We will fix it.
