### ISSUE TITLE
Java output plugin returns zero when exception raised in OutputPlugin.cleanup

### ISSUE THREAD

**Issue by noissefnoc** [embulk/embulk#667]
Hi, maintainers.

I'm writing java-output plugin for DOMO (using stream api cf: https://developer.domo.com/docs/data-apis/stream-apis ).

Step to upload data via Stream API is following

1. Authentication
2. Create an Execution ("Execution" means data import session)
3. Upload Data Parts (this can be done asynchronously, in parallel)
4. Commit / Rollback the Execution

Step 1-3 implementation works good. I have a trouble at step 4.

I implement step 4 at OutputPlugin.cleanup because commit / rollback should call once at each Executions (not each data parts).
This process may raise exception. When exception raise in OutputPlugin.cleanup, log stacktrace with "Commit succeeded but cleanup failed. Ignoring this exception." message ( this may be https://github.com/embulk/embulk/blob/master/embulk-core/src/main/java/org/embulk/exec/BulkLoader.java#L720-L727 ).

In this case I expected none zero return value because some process failed. But it actually returns zero.
I'll use this plugin in workflow engine. It expects none zero return value when execution fail.
I intend to take record count difference after embulk execution.

 Are there some solutions or workarounds?

Thanks.

Environment
-------------

* CentOS 6.7 
* Java 1.8
* embulk 0.8.22

Execution Log
--------------

### execute with plugin in development

```
$ embulk run -L <path_to_plugin> <config_yaml>
# omit some ordinary logs
# start stacktrace 
2017-06-05 11:26:00.359 +0900 [WARN] (0001:transaction): Commit succeeded but cleanup failed. Ignoring this exception.
java.lang.RuntimeException: csv bulk upload failed.
        at org.embulk.output.DomoOutputPlugin.cleanup(DomoOutputPlugin.java:279) ~[na:na]
        at org.embulk.exec.BulkLoader.doCleanup(BulkLoader.java:508) [embulk:0.8.22]
        at org.embulk.exec.BulkLoader.cleanupCommittedTransaction(BulkLoader.java:723) [embulk:0.8.22]
        at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:578) [embulk:0.8.22]
        at org.embulk.exec.BulkLoader.access$000(BulkLoader.java:33) [embulk:0.8.22]
        at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:389) [embulk:0.8.22]
        at org.embulk.exec.BulkLoader$1.run(BulkLoader.java:385) [embulk:0.8.22]
        at org.embulk.spi.Exec.doWith(Exec.java:25) [embulk:0.8.22]
        at org.embulk.exec.BulkLoader.run(BulkLoader.java:385) [embulk:0.8.22]
        at org.embulk.EmbulkEmbed.run(EmbulkEmbed.java:180) [embulk:0.8.22]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_112]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_112]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_112]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_112]
        at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(JavaMethod.java:453) [embulk:0.8.22]
        at org.jruby.javasupport.JavaMethod.invokeDirect(JavaMethod.java:314) [embulk:0.8.22]
        at org.jruby.java.invokers.InstanceMethodInvoker.call(InstanceMethodInvoker.java:46) [embulk:0.8.22]
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338) [embulk:0.8.22]
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163) [embulk:0.8.22]
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315) [embulk:0.8.22]
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73) [embulk:0.8.22]
        at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:90) [embulk:0.8.22]
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:214) [embulk:0.8.22]
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:200) [embulk:0.8.22]
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:205) [embulk:0.8.22]
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:358) [embulk:0.8.22]
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:195) [embulk:0.8.22]
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:324) [embulk:0.8.22]
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73) [embulk:0.8.22]
        at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84) [embulk:0.8.22]
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179) [embulk:0.8.22]
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165) [embulk:0.8.22]
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:197) [embulk:0.8.22]
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338) [embulk:0.8.22]
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163) [embulk:0.8.22]
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315) [embulk:0.8.22]
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73) [embulk:0.8.22]
        at org.jruby.ir.interpreter.Interpreter.INTERPRET_ROOT(Interpreter.java:112) [embulk:0.8.22]
        at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:99) [embulk:0.8.22]
        at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:35) [embulk:0.8.22]
        at org.jruby.ir.IRTranslator.execute(IRTranslator.java:42) [embulk:0.8.22]
        at org.jruby.Ruby.runInterpreter(Ruby.java:850) [embulk:0.8.22]
        at org.jruby.Ruby.loadFile(Ruby.java:2976) [embulk:0.8.22]
        at org.jruby.runtime.load.LibrarySearcher$ResourceLibrary.load(LibrarySearcher.java:243) [embulk:0.8.22]
        at org.jruby.runtime.load.LibrarySearcher$FoundLibrary.load(LibrarySearcher.java:34) [embulk:0.8.22]
        at org.jruby.runtime.load.LoadService.tryLoadingLibraryOrScript(LoadService.java:885) [embulk:0.8.22]
        at org.jruby.runtime.load.LoadService.smartLoadInternal(LoadService.java:525) [embulk:0.8.22]
        at org.jruby.runtime.load.LoadService.require(LoadService.java:396) [embulk:0.8.22]
        at org.jruby.RubyKernel.requireCommon(RubyKernel.java:963) [embulk:0.8.22]
        at org.jruby.RubyKernel.require19(RubyKernel.java:956) [embulk:0.8.22]
        at org.jruby.RubyKernel$INVOKER$s$1$0$require19.call(RubyKernel$INVOKER$s$1$0$require19.gen) [embulk:0.8.22]
        at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodOneOrNBlock.call(JavaMethod.java:383) [embulk:0.8.22]
        at org.jruby.internal.runtime.methods.AliasMethod.call(AliasMethod.java:61) [embulk:0.8.22]
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:161) [embulk:0.8.22]
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315) [embulk:0.8.22]
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:73) [embulk:0.8.22]
        at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84) [embulk:0.8.22]
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.INTERPRET_METHOD(MixedModeIRMethod.java:179) [embulk:0.8.22]
        at org.jruby.internal.runtime.methods.MixedModeIRMethod.call(MixedModeIRMethod.java:165) [embulk:0.8.22]
        at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:197) [embulk:0.8.22]
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:338) [embulk:0.8.22]
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:163) [embulk:0.8.22]
        at usr.local.bin.embulk.embulk.command.embulk_bundle.invokeOther66:require(file:/usr/local/bin/embulk!/embulk/command/embulk_bundle.rb:51) [embulk:na]
        at usr.local.bin.embulk.embulk.command.embulk_bundle.RUBY$script(file:/usr/local/bin/embulk!/embulk/command/embulk_bundle.rb:51) [embulk:na]
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627) [na:1.8.0_112]
        at org.jruby.ir.Compiler$1.load(Compiler.java:111) [embulk:0.8.22]
        at org.jruby.Ruby.runScript(Ruby.java:834) [embulk:0.8.22]
        at org.jruby.Ruby.runNormally(Ruby.java:749) [embulk:0.8.22]
        at org.jruby.Ruby.runNormally(Ruby.java:767) [embulk:0.8.22]
        at org.jruby.Ruby.runFromMain(Ruby.java:580) [embulk:0.8.22]
        at org.jruby.Main.doRunFromMain(Main.java:425) [embulk:0.8.22]
        at org.jruby.Main.internalRun(Main.java:313) [embulk:0.8.22]
        at org.jruby.Main.run(Main.java:242) [embulk:0.8.22]
        at org.jruby.Main.main(Main.java:204) [embulk:0.8.22]
        at org.embulk.cli.Main.main(Main.java:23) [embulk:0.8.22]
# end stacktrace
# omit some ordinary log
```

### check return value

```
$ echo $?
0  # want none zero value
```

How to reproduce
------------------

raise exception in your custom java-output-plugin's OutputPlugin.cleanup

**Comment by hiroyuki-sato** [comment]
Hello @noissefnoc 

I think it is better to implement `rollback` in the `transaction` method
like embulk-output-jdbc.

https://github.com/embulk/embulk-output-jdbc/blob/master/embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/AbstractJdbcOutputPlugin.java#L356

And execute `rollback` when transaction failed. 

https://github.com/embulk/embulk-output-jdbc/blob/master/embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/JdbcOutputConnection.java#L87

You can execute `rollback` and get status non-zero.

The following is sample.
https://github.com/hiroyuki-sato/embulk-support/tree/master/core_667_rollback

```
Error: java.lang.RuntimeException: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '2015-01-28 04:23:49' for key 'time'
echo $?
1
```

```
select * from rollback_test;
+------+---------+---------------------+---------------------+----------------------------+
| id   | account | time                | purchase            | comment                    |
+------+---------+---------------------+---------------------+----------------------------+
|    1 |   32864 | 2015-01-28 04:23:49 | 2015-01-27 09:00:00 | embulk                     |
|    2 |   14824 | 2015-01-28 04:01:23 | 2015-01-27 09:00:00 | embulk jruby               |
|    3 |   27559 | 2015-01-28 11:20:02 | 2015-01-28 09:00:00 | Embulk "csv" parser plugin |
|    4 |   11270 | 2015-01-29 20:54:36 | 2015-01-29 09:00:00 | NULL                       |
+------+---------+---------------------+---------------------+----------------------------+
4 rows in set (0.00 sec)
```

```
mysql> alter table rollback_test add unique(time);
Query OK, 0 rows affected (0.04 sec)
Records: 0  Duplicates: 0  Warnings: 0
```


```
2017-06-05 20:22:05.842 +0900 [INFO] (0001:transaction): SQL: INSERT INTO `rollback_test` (`id`, `account`, `time`, `purchase`, `comment`) SELECT `id`, `account`, `time`, `purchase`, `comment` FROM `rollback_test_0000000059353edc3ad46cc0_bl_tmp000` UNION ALL SELECT `id`, `account`, `time`, `purchase`, `comment` FROM `rollback_test_0000000059353edc3ad46cc0_bl_tmp001` UNION ALL SELECT `id`, `account`, `time`, `purchase`, `comment` FROM `rollback_test_0000000059353edc3ad46cc0_bl_tmp002` UNION ALL SELECT `id`, `account`, `time`, `purchase`, `comment` FROM `rollback_test_0000000059353edc3ad46cc0_bl_tmp003`
2017-06-05 20:22:05.853 +0900 [ERROR] (0001:transaction): Operation failed (1062:23000)
2017-06-05 20:22:05.872 +0900 [INFO] (0001:cleanup): Connecting to jdbc:mysql://127.0.0.1:3306/embulk_test options {user=root, tcpKeepAlive=true, useCompression=true, rewriteBatchedStatements=true, connectTimeout=300000, socketTimeout=1800000}
2017-06-05 20:22:05.882 +0900 [INFO] (0001:cleanup): SQL: DROP TABLE IF EXISTS `rollback_test_0000000059353edc3ad46cc0_bl_tmp000`
2017-06-05 20:22:05.885 +0900 [INFO] (0001:cleanup): > 0.00 seconds
2017-06-05 20:22:05.885 +0900 [INFO] (0001:cleanup): SQL: DROP TABLE IF EXISTS `rollback_test_0000000059353edc3ad46cc0_bl_tmp001`
2017-06-05 20:22:05.887 +0900 [INFO] (0001:cleanup): > 0.00 seconds
2017-06-05 20:22:05.888 +0900 [INFO] (0001:cleanup): SQL: DROP TABLE IF EXISTS `rollback_test_0000000059353edc3ad46cc0_bl_tmp002`
2017-06-05 20:22:05.890 +0900 [INFO] (0001:cleanup): > 0.00 seconds
2017-06-05 20:22:05.890 +0900 [INFO] (0001:cleanup): SQL: DROP TABLE IF EXISTS `rollback_test_0000000059353edc3ad46cc0_bl_tmp003`
2017-06-05 20:22:05.893 +0900 [INFO] (0001:cleanup): > 0.00 seconds
```

**Comment by noissefnoc** [comment]
@hiroyuki-sato Thanks for your advice. I'll try it.

I still want care in case all data part upload success but execution commit request fail.
Is there some proper implementation?

**Comment by muga** [comment]
As any exception from `cleanup` is ignored as @hiroyuki-sato mentioned, If the Embulk transaction failed during commit process, we need to rerun Embulk itself. Or, if the plugin supports resume feature, we can use resume.

**Comment by hiroyuki-sato** [comment]
@noissefnoc 

IIUC

* The `OutputPlugin.run` are called the number of task times.
* The `OutputPlugin.transaction` are called just once. 

So you just write `commit/rollback` code in `transaction` method. 
The following is the example of embulk-output-jdbc  `output tasks 4`


If you want to write a `commit/rollback` codes in `cleanup` method. 
Please tell a maintainer more detail your requirement. 


https://github.com/embulk/embulk-output-jdbc/blob/master/embulk-output-jdbc/src/main/java/org/embulk/output/jdbc/AbstractJdbcOutputPlugin.java#L355-L356

```java
control.run(task.dump());  // called number of task times. 4 in this example. 
return commit(task, schema, taskCount); // called just once. 
```

```
2017-06-06 12:43:07.142 +0900 [INFO] (0001:transaction): Using local thread executor with max_threads=8 / output tasks 4 = input tasks 2 * 2
...
// called multiple insert into temporary table.
2017-06-06 12:43:07.618 +0900 [INFO] (0016:task-0000): Prepared SQL: INSERT INTO `rollback_test_00000000593624ca3ad46cc0_bl_tmp000` (`id`, `account`, `time`, `purchase`, `comment`) VALUES (?, ?, ?, ?, ?)
2017-06-06 12:43:07.620 +0900 [INFO] (0017:task-0001): Prepared SQL: INSERT INTO `rollback_test_00000000593624ca3ad46cc0_bl_tmp002` (`id`, `account`, `time`, `purchase`, `comment`) VALUES (?, ?, ?, ?, ?)
2017-06-06 12:43:07.646 +0900 [INFO] (0017:task-0001): Prepared SQL: INSERT INTO `rollback_test_00000000593624ca3ad46cc0_bl_tmp003` (`id`, `account`, `time`, `purchase`, `comment`) VALUES (?, ?, ?, ?, ?)
2017-06-06 12:43:07.647 +0900 [INFO] (0016:task-0000): Prepared SQL: INSERT INTO `rollback_test_00000000593624ca3ad46cc0_bl_tmp001` (`id`, `account`, `time`, `purchase`, `comment`) VALUES (?, ?, ?, ?, ?)
...
// insert into (real table) called just once. 
2017-06-06 12:43:07.828 +0900 [INFO] (0001:transaction): SQL: INSERT INTO `rollback_test` (`id`, `account`, `time`, `purchase`, `comment`) SELECT `id`, `account`, `time`, `purchase`, `comment` FROM `rollback_test_00000000593624ca3ad46cc0_bl_tmp000` UNION ALL SELECT `id`, `account`, `time`, `purchase`, `comment` FROM `rollback_test_00000000593624ca3ad46cc0_bl_tmp001` UNION ALL SELECT `id`, `account`, `time`, `purchase`, `comment` FROM `rollback_test_00000000593624ca3ad46cc0_bl_tmp002` UNION ALL SELECT `id`, `account`, `time`, `purchase`, `comment` FROM `rollback_test_00000000593624ca3ad46cc0_bl_tmp003`
```

**Comment by noissefnoc** [comment]
@hiroyuki-sato @muga Thank you for teaching me so kindly. I completely misunderstood `transaction` method behavior and intended to use `cleanup` method.

I implement commit / rollback code in `transaction` method and test it. It works fine (when process fail then return non-zero value.).

Thank you again!
