### ISSUE TITLE
LinkageError of plug-in's msgpack version conflicting

### ISSUE THREAD

**Issue by smdmts** [embulk/embulk#691]
Plug-in modules which depending `msgpack` would be version conflicting with `embulk-core`. 
This problem continues to occur sharing `msgpack` module between `embulk-core` and `3rd-plugin`. Therefore is it be changed to link core and plugin with serialized binary-array? 

### Example
It could not parse with LinkageError with msgpack break binary compatible 0.8.11 to 0.8.12.
https://github.com/msgpack/msgpack-java/compare/0.8.11...0.8.12

- Embulk(v0.8.25) msgpack(v0.8.11)
- 3rd-plugin msgpack (v0.8.12)

- StackTrace
```
Caused by: java.lang.LinkageError: loader constraint violation: when resolving method "org.embulk.spi.PageReader.getJson(Lorg/embulk/spi/Column;)Lorg/msgpack/value/Value;" the class loader (instance of org/embulk/plugin/PluginClassLoader) of the current class, org/embulk/output/fluentd/ColumnVisitor$$anonfun$jsonColumn$1$$anonfun$apply$6, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for the method's defining class, org/embulk/spi/PageReader, have different Class objects for the type org/msgpack/value/Value used in the signature
	at org.embulk.output.fluentd.ColumnVisitor$$anonfun$jsonColumn$1$$anonfun$apply$6.apply(ColumnVisitor.scala:30)
	at org.embulk.output.fluentd.ColumnVisitor$$anonfun$jsonColumn$1$$anonfun$apply$6.apply(ColumnVisitor.scala:30)
	at org.embulk.output.fluentd.ColumnVisitor.value(ColumnVisitor.scala:36)
	at org.embulk.output.fluentd.ColumnVisitor.jsonColumn(ColumnVisitor.scala:30)
	at org.embulk.spi.Column.visit(Column.java:62)
	at org.embulk.spi.Schema.visitColumns(Schema.java:81)
	at org.embulk.output.fluentd.FluentdTransactionalPageOutput$$anonfun$asIterator$1.apply(FluentdTransactionalPageOutput.scala:23)
	at org.embulk.output.fluentd.FluentdTransactionalPageOutput$$anonfun$asIterator$1.apply(FluentdTransactionalPageOutput.scala:21)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:162)
	at scala.collection.Iterator$$anon$16.hasNext(Iterator.scala:599)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at org.embulk.output.fluentd.Emitter$.apply(Emitter.scala:34)
	at org.embulk.output.fluentd.FluentdTransactionalPageOutput.add(FluentdTransactionalPageOutput.scala:14)
	at org.embulk.exec.LocalExecutorPlugin$ScatterTransactionalPageOutput$OutputWorker.call(LocalExecutorPlugin.java:394)
	at org.embulk.exec.LocalExecutorPlugin$ScatterTransactionalPageOutput$OutputWorker.call(LocalExecutorPlugin.java:319)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
	Suppressed: java.lang.LinkageError: loader constraint violation: when resolving method "org.embulk.spi.PageReader.getJson(Lorg/embulk/spi/Column;)Lorg/msgpack/value/Value;" the class loader (instance of org/embulk/plugin/PluginClassLoader) of the current class, org/embulk/output/fluentd/ColumnVisitor$$anonfun$jsonColumn$1$$anonfun$apply$6, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for the method's defining class, org/embulk/spi/PageReader, have different Class objects for the type org/msgpack/value/Value used in the signature
		... 20 more
	Suppressed: java.lang.LinkageError: loader constraint violation: when resolving method "org.embulk.spi.PageReader.getJson(Lorg/embulk/spi/Column;)Lorg/msgpack/value/Value;" the class loader (instance of org/embulk/plugin/PluginClassLoader) of the current class, org/embulk/output/fluentd/ColumnVisitor$$anonfun$jsonColumn$1$$anonfun$apply$6, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for the method's defining class, org/embulk/spi/PageReader, have different Class objects for the type org/msgpack/value/Value used in the signature
		... 20 more
```

**Comment by civitaspo** [comment]
I wrote reproducing code here https://github.com/civitaspo/embulk-filter-linkage_error

**Comment by muga** [comment]
Thank you for filing a ticket. I saw your stacktrace and noticed that msgpack library is not included in the list of package classes that the plugin classloader delegates to Embulk's classloader. I think that this issue is a bug within Embulk core. Should not conflict version of msgpack.

**Comment by civitaspo** [comment]
Ok, I will try this later. Wait for a while.

**Comment by civitaspo** [comment]
Looks good to me! It works! @muga 

```
[embulk] ghq get git@github.com:muga/embulk.git
     clone ssh://git@github.com/muga/embulk.git -> /Users/takahiro.nakayama/src/github.com/muga/embulk
       git clone ssh://git@github.com/muga/embulk.git /Users/takahiro.nakayama/src/github.com/muga/embulk
Cloning into '/Users/takahiro.nakayama/src/github.com/muga/embulk'...
remote: Counting objects: 20390, done.
remote: Compressing objects: 100% (112/112), done.
remote: Total 20390 (delta 44), reused 137 (delta 26), pack-reused 20219
Receiving objects: 100% (20390/20390), 4.53 MiB | 1.13 MiB/s, done.
Resolving deltas: 100% (9164/9164), done.
[embulk] git chockout fix_properties_of_plugin_class_loader
Branch fix_properties_of_plugin_class_loader set up to track remote branch fix_properties_of_plugin_class_loader from origin by rebasing.
Switched to a new branch 'fix_properties_of_plugin_class_loader'
[embulk] ./gradlew cli
Starting a Gradle Daemon (subsequent builds will be faster)
Publication bintrayMavenRelease not found in project :.
Publication bintrayMavenRelease not found in project :embulk-cli.
Publication bintrayMavenRelease not found in project :embulk-docs.
Download https://repo1.maven.org/maven2/org/eclipse/aether/aether-api/1.1.0/aether-api-1.1.0.pom
Download https://repo1.maven.org/maven2/org/eclipse/aether/aether/1.1.0/aether-1.1.0.pom
Download https://repo1.maven.org/maven2/org/eclipse/aether/aether-spi/1.1.0/aether-spi-1.1.0.pom
Download https://repo1.maven.org/maven2/org/eclipse/aether/aether-util/1.1.0/aether-util-1.1.0.pom
Download https://repo1.maven.org/maven2/org/eclipse/aether/aether-impl/1.1.0/aether-impl-1.1.0.pom
Download https://repo1.maven.org/maven2/org/apache/maven/maven-aether-provider/3.3.9/maven-aether-provider-3.3.9.pom
Download https://repo1.maven.org/maven2/org/apache/maven/maven-model/3.3.9/maven-model-3.3.9.pom
Download https://repo1.maven.org/maven2/org/apache/maven/maven-model-builder/3.3.9/maven-model-builder-3.3.9.pom
Download https://repo1.maven.org/maven2/org/apache/maven/maven-repository-metadata/3.3.9/maven-repository-metadata-3.3.9.pom
Download https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-component-annotations/1.6/plexus-component-annotations-1.6.pom
Download https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-containers/1.6/plexus-containers-1.6.pom
Download https://repo1.maven.org/maven2/org/codehaus/plexus/plexus/3.3.2/plexus-3.3.2.pom
Download https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-interpolation/1.21/plexus-interpolation-1.21.pom
Download https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-components/1.3.1/plexus-components-1.3.1.pom
Download https://repo1.maven.org/maven2/org/apache/maven/maven-builder-support/3.3.9/maven-builder-support-3.3.9.pom
Download https://repo1.maven.org/maven2/org/eclipse/aether/aether-api/1.1.0/aether-api-1.1.0.jar
Download https://repo1.maven.org/maven2/org/eclipse/aether/aether-spi/1.1.0/aether-spi-1.1.0.jar
Download https://repo1.maven.org/maven2/org/eclipse/aether/aether-util/1.1.0/aether-util-1.1.0.jar
Download https://repo1.maven.org/maven2/org/eclipse/aether/aether-impl/1.1.0/aether-impl-1.1.0.jar
Download https://repo1.maven.org/maven2/org/apache/maven/maven-aether-provider/3.3.9/maven-aether-provider-3.3.9.jar
Download https://repo1.maven.org/maven2/org/apache/maven/maven-model/3.3.9/maven-model-3.3.9.jar
Download https://repo1.maven.org/maven2/org/apache/maven/maven-model-builder/3.3.9/maven-model-builder-3.3.9.jar
Download https://repo1.maven.org/maven2/org/apache/maven/maven-repository-metadata/3.3.9/maven-repository-metadata-3.3.9.jar
Download https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-component-annotations/1.6/plexus-component-annotations-1.6.jar
Download https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-interpolation/1.21/plexus-interpolation-1.21.jar
Download https://repo1.maven.org/maven2/org/apache/maven/maven-builder-support/3.3.9/maven-builder-support-3.3.9.jar
:embulk-core:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 warning
:embulk-core:unpackGems
Download http://rubygems.lasagna.io/proxy/maven/releases/rubygems/bundler/1.10.6/bundler-1.10.6.pom
Download http://rubygems.lasagna.io/proxy/maven/releases/rubygems/msgpack/1.1.0/msgpack-1.1.0.pom
Download http://rubygems.lasagna.io/proxy/maven/releases/rubygems/liquid/3.0.6/liquid-3.0.6.pom
Download http://rubygems.lasagna.io/proxy/maven/releases/rubygems/bundler/1.10.6/bundler-1.10.6.gem
Download http://rubygems.lasagna.io/proxy/maven/releases/rubygems/msgpack/1.1.0/msgpack-1.1.0.gem
Download http://rubygems.lasagna.io/proxy/maven/releases/rubygems/liquid/3.0.6/liquid-3.0.6.gem
Successfully installed bundler-1.10.6
Successfully installed msgpack-1.1.0-java
Successfully installed liquid-3.0.6
3 gems installed
:embulk-core:processResources
:embulk-core:classes
:embulk-core:jar
:embulk-standards:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
Note: /Users/takahiro.nakayama/src/github.com/muga/embulk/embulk-standards/src/main/java/org/embulk/standards/StdoutOutputPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 warning
:embulk-standards:processResources
:embulk-standards:classes
:embulk-standards:jar
:embulk-cli:compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
1 warning
:embulk-cli:processResources UP-TO-DATE
:embulk-cli:classes
:embulk-cli:shadowJar
:cli

BUILD SUCCESSFUL

Total time: 49.244 secs
[embulk] pkg/embulk-0.8.25.jar
Embulk v0.8.25
Usage: embulk [-vm-options] <command> [--options]
Commands:
   mkbundle   <directory>                             # create a new plugin bundle environment.
   bundle     [directory]                             # update a plugin bundle environment.
   run        <config.yml>                            # run a bulk load transaction.
   cleanup    <config.yml>                            # cleanup resume state.
   preview    <config.yml>                            # dry-run the bulk load without output and show preview.
   guess      <partial-config.yml> -o <output.yml>    # guess missing parameters to create a complete configuration file.
   gem        <install | list | help>                 # install a plugin or show installed plugins.
                                                      # plugin path is /Users/takahiro.nakayama/.embulk/jruby/2.3.0
   new        <category> <name>                       # generates new plugin template
   migrate    <path>                                  # modify plugin code to use the latest Embulk plugin API
   example    [path]                                  # creates an example config file and csv file to try embulk.
   selfupdate [version]                               # upgrades embulk to the latest released version or to the specified version.

VM options:
   -J-O                             Disable JVM optimizations to speed up startup time (enabled by default if command is 'run')
   -J+O                             Enable JVM optimizations to speed up throughput
   -J...                            Set JVM options (use -J-help to see available options)
   -R...                            Set JRuby options (use -R--help to see available options)

Use `<command> --help` to see description of the commands.
```

```
[embulk-filter-linkage_error] ~/src/github.com/muga/embulk/pkg/embulk-0.8.25.jar run example/config.yml -Ilib
2017-06-24 14:51:01.206 +0900: Embulk v0.8.25
2017-06-24 14:51:02.617 +0900 [INFO] (0001:transaction): Loaded plugin embulk/filter/linkage_error from a load path
2017-06-24 14:51:02.635 +0900 [INFO] (0001:transaction): Listing local files at directory 'example' filtering filename by prefix 'data.csv'
2017-06-24 14:51:02.636 +0900 [INFO] (0001:transaction): "follow_symlinks" is set false. Note that symbolic links to directories are skipped.
2017-06-24 14:51:02.645 +0900 [INFO] (0001:transaction): Loading files [example/data.csv]
2017-06-24 14:51:02.689 +0900 [INFO] (0001:transaction): Using local thread executor with max_threads=16 / output tasks 8 = input tasks 1 * 8
2017-06-24 14:51:02.695 +0900 [INFO] (0001:transaction): {done:  0 / 1, running: 0}
2017-06-24 14:51:02.706 +0900 [INFO] (0001:transaction): {done:  1 / 1, running: 0}
org.embulk.exec.PartialExecutionException: java.lang.UnsupportedOperationException: LinkageErrorFilterPlugin.open method is not implemented yet
        at org.embulk.exec.BulkLoader$LoaderState.buildPartialExecuteException(org/embulk/exec/BulkLoader.java:375)
        at org.embulk.exec.BulkLoader.doRun(org/embulk/exec/BulkLoader.java:607)
        at org.embulk.exec.BulkLoader.access$000(org/embulk/exec/BulkLoader.java:35)
        at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:391)
        at org.embulk.exec.BulkLoader$1.run(org/embulk/exec/BulkLoader.java:387)
        at org.embulk.spi.Exec.doWith(org/embulk/spi/Exec.java:25)
        at org.embulk.exec.BulkLoader.run(org/embulk/exec/BulkLoader.java:387)
        at org.embulk.EmbulkEmbed.run(org/embulk/EmbulkEmbed.java:180)
        at java.lang.reflect.Method.invoke(java/lang/reflect/Method.java:498)
        at org.jruby.javasupport.JavaMethod.invokeDirectWithExceptionHandling(org/jruby/javasupport/JavaMethod.java:453)
        at org.jruby.javasupport.JavaMethod.invokeDirect(org/jruby/javasupport/JavaMethod.java:314)
        at RUBY.run(/Users/takahiro.nakayama/src/github.com/muga/embulk/pkg/embulk-0.8.25.jar!/embulk/runner.rb:84)
        at RUBY.run(/Users/takahiro.nakayama/src/github.com/muga/embulk/pkg/embulk-0.8.25.jar!/embulk/command/embulk_run.rb:269)
        at RUBY.<main>(/Users/takahiro.nakayama/src/github.com/muga/embulk/pkg/embulk-0.8.25.jar!/embulk/command/embulk_main.rb:2)
        at org.jruby.Ruby.runInterpreter(org/jruby/Ruby.java:850)
        at org.jruby.Ruby.loadFile(org/jruby/Ruby.java:2976)
        at org.jruby.RubyKernel.requireCommon(org/jruby/RubyKernel.java:963)
        at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:956)
        at org.jruby.RubyKernel$INVOKER$s$1$0$require19.call(org/jruby/RubyKernel$INVOKER$s$1$0$require19.gen)
        at RUBY.(root)(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:1)
        at Users.takahiro_dot_nakayama.src.github_dot_com.muga.embulk.pkg.embulk_minus_0_dot_8_dot_25_dot_jar.embulk.command.embulk_bundle.invokeOther34:require(Users/takahiro_dot_nakayama/src/github_dot_com/muga/embulk/pkg/embulk_minus_0_dot_8_dot_25_dot_jar/embulk/command/file:/Users/takahiro.nakayama/src/github.com/muga/embulk/pkg/embulk-0.8.25.jar!/embulk/command/embulk_bundle.rb:46)
        at Users.takahiro_dot_nakayama.src.github_dot_com.muga.embulk.pkg.embulk_minus_0_dot_8_dot_25_dot_jar.embulk.command.embulk_bundle.<main>(file:/Users/takahiro.nakayama/src/github.com/muga/embulk/pkg/embulk-0.8.25.jar!/embulk/command/embulk_bundle.rb:46)
        at java.lang.invoke.MethodHandle.invokeWithArguments(java/lang/invoke/MethodHandle.java:627)
        at org.jruby.Ruby.runScript(org/jruby/Ruby.java:834)
        at org.jruby.Ruby.runNormally(org/jruby/Ruby.java:749)
        at org.jruby.Ruby.runNormally(org/jruby/Ruby.java:767)
        at org.jruby.Ruby.runFromMain(org/jruby/Ruby.java:580)
        at org.jruby.Main.doRunFromMain(org/jruby/Main.java:425)
        at org.jruby.Main.internalRun(org/jruby/Main.java:313)
        at org.jruby.Main.run(org/jruby/Main.java:242)
        at org.jruby.Main.main(org/jruby/Main.java:204)
        at org.embulk.cli.Main.main(org/embulk/cli/Main.java:23)
Caused by: java.lang.UnsupportedOperationException: LinkageErrorFilterPlugin.open method is not implemented yet
        at org.embulk.filter.linkage_error.LinkageErrorFilterPlugin.open(LinkageErrorFilterPlugin.java:43)
        at org.embulk.spi.util.Filters.open(Filters.java:58)
        at org.embulk.exec.LocalExecutorPlugin$ScatterTransactionalPageOutput.openFilters(LocalExecutorPlugin.java:461)
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.runInputTask(LocalExecutorPlugin.java:284)
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor.access$000(LocalExecutorPlugin.java:212)
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor$1.call(LocalExecutorPlugin.java:257)
        at org.embulk.exec.LocalExecutorPlugin$ScatterExecutor$1.call(LocalExecutorPlugin.java:253)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)

Error: java.lang.UnsupportedOperationException: LinkageErrorFilterPlugin.open method is not implemented yet
```

**Comment by muga** [comment]
@civitaspo Thank you for confirming-!
