### ISSUE TITLE
TestingEmbulk 0.8.27 doesn't work

### ISSUE THREAD

**Issue by hito4t** [embulk/embulk#734]
When I tested embulk-input-mysql with embulk 0.8.27, it failed.

build.gradle
<pre>
...
subprojects {
    ...
    dependencies {
        compile  'org.embulk:embulk-core:0.8.27'
        provided 'org.embulk:embulk-core:0.8.27'
        testCompile 'org.embulk:embulk-test:0.8.27'
    }
    ...
</pre>

command
<pre>
gradlew clean gem -p embulk-input-mysql
</pre>

error
<pre>
  <testcase name="testLong" classname="org.embulk.input.mysql.BasicTest" time="0.004">
    <failure message="java.lang.InstantiationError: org.embulk.plugin.PluginType" type="java.lang.InstantiationError">java.lang.InstantiationError: org.embulk.plugin.PluginType
	at org.embulk.standards.StandardPluginModule.configure(StandardPluginModule.java:52)
	at org.embulk.exec.ExtensionServiceLoaderModule.configure(ExtensionServiceLoaderModule.java:39)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.util.Modules$OverrideModule.configure(Modules.java:177)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.Guice.createInjector(Guice.java:96)
	at org.embulk.guice.Bootstrap.start(Bootstrap.java:143)
	at org.embulk.guice.Bootstrap.build(Bootstrap.java:110)
	at org.embulk.guice.Bootstrap.initializeCloseable(Bootstrap.java:105)
	at org.embulk.EmbulkEmbed$Bootstrap.build(EmbulkEmbed.java:113)
	at org.embulk.EmbulkEmbed$Bootstrap.initializeCloseable(EmbulkEmbed.java:96)
	at org.embulk.test.TestingEmbulk.reset(TestingEmbulk.java:100)
	at org.embulk.test.TestingEmbulk.&lt;init&gt;(TestingEmbulk.java:93)
	at org.embulk.test.TestingEmbulk$Builder.build(TestingEmbulk.java:76)
	at org.embulk.input.mysql.BasicTest.&lt;init&gt;(BasicTest.java:34)
</pre>

It worked with embulk 0.8.22 .

**Comment by hito4t** [comment]
I'm sorry.
I used different version of embulk-standard.
