### ISSUE TITLE
embulk 0.8.28 is not working on windows

### ISSUE THREAD

**Issue by shiena** [embulk/embulk#748]
**environment**
OS: Windows10
Java: 1.8.0_141

v0.8.27 is working
```
C:\Users\shiena\bin>embulk-0.8.27.bat --version
embulk 0.8.27
```

v0.8.28 is not working
```
C:\Users\shiena\bin>embulk-0.8.28.bat --version
Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/shiena/bin/embulk-0.8.28.bat
        at sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at sun.nio.fs.WindowsPath.parse(Unknown Source)
        at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at java.nio.file.Paths.get(Unknown Source)
        at org.embulk.cli.EmbulkGlobalJRubyScriptingContainer.getEmbulkJRubyLoadPath(EmbulkGlobalJRubyScriptingContainer.java:181)
        at org.embulk.cli.EmbulkGlobalJRubyScriptingContainer.setup(EmbulkGlobalJRubyScriptingContainer.java:107)
        at org.embulk.cli.EmbulkBundle.checkBundleWithEmbulkVersion(EmbulkBundle.java:26)
        at org.embulk.cli.EmbulkBundle.checkBundle(EmbulkBundle.java:15)
        at org.embulk.cli.Main.main(Main.java:26)
```

**Comment by dmikurube** [comment]
Thanks for reporting! To be fixed in #751.
