### ISSUE TITLE
Throws "Embulk::PluginLoadError: Unknown guess plugin 'gzip' " even if i have installed gzip gem.

### ISSUE THREAD

**Issue by yoshi0309** [embulk/embulk#75]
Mac OS X 10.10.1
Oracle Java version "1.7.0_45"

```
Yoshida-no-MacBook-Air:Documents takumi$ java -jar embulk.jar gem list

*** LOCAL GEMS ***

ffi (1.9.3 java)
jar-dependencies (0.1.2)
jruby-openssl (0.9.5 java)
json (1.8.0 java)
krypt (0.0.2)
krypt-core (0.0.2 universal-java)
krypt-provider-jdk (0.0.2)
rake (10.1.0)
rdoc (4.1.2)
Yoshida-no-MacBook-Air:Documents takumi$ java -jar embulk.jar gem install gzip
Fetching: gzip-1.0.gem (100%)
Successfully installed gzip-1.0
1 gem installed
Yoshida-no-MacBook-Air:Documents takumi$ java -jar embulk.jar guess embulk-example/example.yml -o config.yml
2015-02-17 07:09:27,493 [INFO]: main:org.embulk.standards.LocalFileInputPlugin: Listing local files at directory '/Users/takumi/Documents/embulk-example/csv' filtering filename by prefix 'sample_'
2015-02-17 07:09:27,502 [INFO]: main:org.embulk.standards.LocalFileInputPlugin: Loading files [/Users/takumi/Documents/embulk-example/csv/sample_01.csv.gz]
Embulk::PluginLoadError: Unknown guess plugin 'gzip'. embulk/guess/gzip.rb is not installed. Run 'embulk gem search -rd embulk-guess' command to find plugins.
          lookup at file:/Users/takumi/Documents/embulk.jar!/embulk/plugin_registry.rb:30
          lookup at file:/Users/takumi/Documents/embulk.jar!/embulk/plugin.rb:188
  new_java_guess at file:/Users/takumi/Documents/embulk.jar!/embulk/plugin.rb:178
  new_java_guess at /Users/takumi/Documents/embulk.jar!/META-INF/jruby.home/lib/ruby/1.9/forwardable.rb:201
             run at file:/Users/takumi/Documents/embulk.jar!/embulk/command/embulk_run.rb:275
          (root) at classpath:embulk/command/embulk.rb:39
org/embulk/plugin/PluginManager.java:42:in `newPlugin': org.embulk.config.ConfigException: GuessPlugin 'gzip' is not found
	from org/embulk/spi/ExecSession.java:106:in `newPlugin'
	from org/embulk/spi/Exec.java:54:in `newPlugin'
	from org/embulk/exec/GuessExecutor.java:267:in `run'
	from org/embulk/spi/FileInputRunner.java:129:in `run'
	from org/embulk/exec/GuessExecutor.java:118:in `run'
	from org/embulk/spi/FileInputRunner.java:101:in `run'
	from org/embulk/exec/GuessExecutor.java:251:in `transaction'
	from org/embulk/spi/FileInputRunner.java:95:in `run'
	from org/embulk/spi/util/Decoders.java:77:in `transaction'
	from org/embulk/spi/util/Decoders.java:33:in `transaction'
	from org/embulk/spi/FileInputRunner.java:92:in `run'
	from org/embulk/exec/GuessExecutor.java:170:in `transaction'
	from org/embulk/spi/FileInputRunner.java:60:in `transaction'
	from org/embulk/exec/GuessExecutor.java:114:in `runGuessInput'
	from org/embulk/exec/GuessExecutor.java:93:in `doGuess'
	from org/embulk/exec/GuessExecutor.java:34:in `access$000'
	from org/embulk/exec/GuessExecutor.java:73:in `run'
	from org/embulk/exec/GuessExecutor.java:70:in `run'
	from org/embulk/spi/Exec.java:21:in `doWith'
	from org/embulk/exec/GuessExecutor.java:70:in `guess'
	from org/embulk/command/Runner.java:168:in `guess'
	from org/embulk/command/Runner.java:70:in `main'
	from java/lang/reflect/Method.java:606:in `invoke'
	from file:/Users/takumi/Documents/embulk.jar!/embulk/command/embulk_run.rb:275:in `run'
	from classpath:embulk/command/embulk.rb:39:in `(root)'
	from classpath_3a_embulk/command/classpath:embulk/command/embulk.rb:39:in `(root)'
	from org/embulk/cli/Main.java:13:in `main'
Caused by:
file:/Users/takumi/Documents/embulk.jar!/embulk/plugin_registry.rb:30:in `lookup': org.jruby.exceptions.RaiseException: (PluginLoadError) Unknown guess plugin 'gzip'. embulk/guess/gzip.rb is not installed. Run 'embulk gem search -rd embulk-guess' command to find plugins.
	from file:/Users/takumi/Documents/embulk.jar!/embulk/plugin.rb:188:in `lookup'
	from file:/Users/takumi/Documents/embulk.jar!/embulk/plugin.rb:178:in `new_java_guess'
	from /Users/takumi/Documents/embulk.jar!/META-INF/jruby.home/lib/ruby/1.9/forwardable.rb:201:in `new_java_guess'
	from file:/Users/takumi/Documents/embulk.jar!/embulk/command/embulk_run.rb:275:in `run'
	from classpath:embulk/command/embulk.rb:39:in `(root)'
Yoshida-no-MacBook-Air:Documents takumi$ java -jar embulk.jar gem list

*** LOCAL GEMS ***

ffi (1.9.3 java)
gzip (1.0)
jar-dependencies (0.1.2)
jruby-openssl (0.9.5 java)
json (1.8.0 java)
krypt (0.0.2)
krypt-core (0.0.2 universal-java)
krypt-provider-jdk (0.0.2)
rake (10.1.0)
rdoc (4.1.2)
```

**Comment by frsyuki** [comment]
Are you using embulk 0.4.0? Please try 0.4.1 or later.

**Comment by yoshi0309** [comment]
Thank you for response. 
the error reproduced on 0.4.1. but it works well on 0.4.2.
FYI
