### ISSUE TITLE
embulk execution sometimes stops maybe because threads fall into deadlock?

### ISSUE THREAD

**Issue by ysk24ok** [embulk/embulk#756]
I use embulk to load data from Amazon S3 to Google Cloud Storage
with embulk-input-s3 and embulk-output-gcs plugin.
But embulk execution sometimes completely stops
and there is no way to kill the process.
I'll put `jcmd` output in the comment. 
It seems to me that threads fall into deadlock because all threads' state is WAITING.
Is there any way to avoid this?

**Comment by ysk24ok** [comment]
```sh
$ jcmd 64454 Thread.print
64454:
2017-08-02 11:09:31
Full thread dump OpenJDK 64-Bit Server VM (25.101-b13 mixed mode):

"Attach Listener" #56 daemon prio=9 os_prio=0 tid=0x00007f17d0001000 nid=0x637d waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"threadDeathWatcher-1-1" #33 daemon prio=1 os_prio=0 tid=0x00007f1784024000 nid=0xfc3e waiting on condition [0x00007f17974f7000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
        at java.lang.Thread.sleep(Native Method)
        at io.netty.util.ThreadDeathWatcher$Watcher.run(ThreadDeathWatcher.java:152)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
        at java.lang.Thread.run(Thread.java:745)

"embulk-executor-7" #32 daemon prio=5 os_prio=0 tid=0x00007f1865099800 nid=0xfc3d waiting on condition [0x00007f17977f8000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000004081692d8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

"embulk-executor-6" #31 daemon prio=5 os_prio=0 tid=0x00007f1865098000 nid=0xfc3c waiting on condition [0x00007f17978f9000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000004081692d8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

"embulk-executor-5" #30 daemon prio=5 os_prio=0 tid=0x00007f1865096000 nid=0xfc3b waiting on condition [0x00007f17979fa000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000004081692d8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

"embulk-executor-4" #29 daemon prio=5 os_prio=0 tid=0x00007f1865091800 nid=0xfc3a waiting on condition [0x00007f1797afb000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000004081692d8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

"embulk-executor-3" #28 daemon prio=5 os_prio=0 tid=0x00007f186508f800 nid=0xfc39 waiting on condition [0x00007f1797bfc000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000004081692d8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

"0027:task-0002" #27 daemon prio=5 os_prio=0 tid=0x00007f1865094000 nid=0xfc38 in Object.wait() [0x00007f1797cfc000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.io.PipedInputStream.awaitSpace(PipedInputStream.java:273)
        at java.io.PipedInputStream.receive(PipedInputStream.java:231)
        - locked <0x0000000408acf2a0> (a java.io.PipedInputStream)
        at java.io.PipedOutputStream.write(PipedOutputStream.java:149)
        at org.embulk.output.GcsOutputPlugin$TransactionalGcsFileOutput.add(GcsOutputPlugin.java:211)
        at org.embulk.spi.util.FileOutputOutputStream.doFlush(FileOutputOutputStream.java:79)
        at org.embulk.spi.util.FileOutputOutputStream.flush(FileOutputOutputStream.java:90)
        at org.embulk.spi.util.FileOutputOutputStream.write(FileOutputOutputStream.java:63)
        at java.util.zip.DeflaterOutputStream.deflate(DeflaterOutputStream.java:253)
        at java.util.zip.DeflaterOutputStream.write(DeflaterOutputStream.java:211)
        at java.util.zip.GZIPOutputStream.write(GZIPOutputStream.java:145)
        - locked <0x0000000408acf2f0> (a org.embulk.standards.GzipFileEncoderPlugin$1$1)
        at org.embulk.spi.util.OutputStreamFileOutput.add(OutputStreamFileOutput.java:46)
        at org.embulk.spi.util.FileOutputOutputStream.doFlush(FileOutputOutputStream.java:79)
        at org.embulk.spi.util.FileOutputOutputStream.flush(FileOutputOutputStream.java:90)
        at org.embulk.spi.util.FileOutputOutputStream.write(FileOutputOutputStream.java:68)
        at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
        at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282)
        at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
        - locked <0x000000040812c4d0> (a java.io.OutputStreamWriter)
        at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
        at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129)
        - locked <0x000000040812c4d0> (a java.io.OutputStreamWriter)
        at java.io.BufferedWriter.write(BufferedWriter.java:230)
        - locked <0x000000040812c4d0> (a java.io.OutputStreamWriter)
        at java.io.Writer.write(Writer.java:157)
        at java.io.Writer.append(Writer.java:227)
        at org.embulk.spi.util.LineEncoder.addText(LineEncoder.java:78)
        at org.embulk.standards.CsvFormatterPlugin$1$1.addValue(CsvFormatterPlugin.java:203)
        at org.embulk.standards.CsvFormatterPlugin$1$1.stringColumn(CsvFormatterPlugin.java:166)
        at org.embulk.spi.Column.visit(Column.java:58)
        at org.embulk.spi.Schema.visitColumns(Schema.java:81)
        at org.embulk.standards.CsvFormatterPlugin$1.add(CsvFormatterPlugin.java:131)
        at org.embulk.spi.FileOutputRunner$DelegateTransactionalPageOutput.add(FileOutputRunner.java:166)
        at org.embulk.spi.PageBuilder.doFlush(PageBuilder.java:249)
        at org.embulk.spi.PageBuilder.flush(PageBuilder.java:255)
        at org.embulk.spi.PageBuilder.addRecord(PageBuilder.java:232)
        at org.embulk.filter.json_key.FilteredPageOutput.add(FilteredPageOutput.java:42)
        at org.embulk.spi.PageBuilder.doFlush(PageBuilder.java:249)
        at org.embulk.spi.PageBuilder.flush(PageBuilder.java:255)
        at org.embulk.spi.PageBuilder.addRecord(PageBuilder.java:232)
        at org.embulk.filter.json_map2list.JsonMap2listFilterPlugin$PageOutputImpl.add(JsonMap2listFilterPlugin.java:81)
        at org.embulk.spi.PageBuilder.doFlush(PageBuilder.java:249)
        at org.embulk.spi.PageBuilder.flush(PageBuilder.java:255)
        at org.embulk.spi.PageBuilder.addRecord(PageBuilder.java:232)
        at org.embulk.standards.RemoveColumnsFilterPlugin$PageConverter.add(RemoveColumnsFilterPlugin.java:243)
        at org.embulk.spi.PageBuilder.doFlush(PageBuilder.java:249)
        at org.embulk.spi.PageBuilder.flush(PageBuilder.java:255)
        at org.embulk.spi.PageBuilder.addRecord(PageBuilder.java:232)
        at org.embulk.standards.CsvParserPlugin.run(CsvParserPlugin.java:362)
        at org.embulk.spi.FileInputRunner.run(FileInputRunner.java:156)
        at org.embulk.spi.util.Executors.process(Executors.java:67)
        at org.embulk.spi.util.Executors.process(Executors.java:42)
        at org.embulk.exec.LocalExecutorPlugin$DirectExecutor$1.call(LocalExecutorPlugin.java:184)
        at org.embulk.exec.LocalExecutorPlugin$DirectExecutor$1.call(LocalExecutorPlugin.java:180)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

"embulk-executor-1" #26 daemon prio=5 os_prio=0 tid=0x00007f1865085800 nid=0xfc37 waiting on condition [0x00007f1797dfe000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000004081692d8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

"embulk-executor-0" #25 daemon prio=5 os_prio=0 tid=0x00007f1865084800 nid=0xfc36 waiting on condition [0x00007f17dc1ab000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000004081692d8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1067)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

"java-sdk-http-connection-reaper" #24 daemon prio=5 os_prio=0 tid=0x00007f186504a000 nid=0xfc35 waiting on condition [0x00007f17dc4ac000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
        at java.lang.Thread.sleep(Native Method)
        at com.amazonaws.http.IdleConnectionReaper.run(IdleConnectionR...
```

**Comment by dmikurube** [comment]
@ysk24ok Thanks for reporting the issue!

Hmm, I've never seen such deadlock-like behavior so far in Embulk... It looks a little bit hard to trace this problem just with the information, but we'd at least take care of that.

Sharing more information (OS, Embulk and plugin versions, your configurations (with confidential information masked), runtime command line, approximate size of the data, how long did it run properly, etc...) may help investigating.

**Comment by ysk24ok** [comment]
* Amazon Linux (kernel version: 3.14.35-28.38.amzn1.x86_64)
* embulk (0.8.27)
* embulk-input-s3 (0.2.8)
* embulk-output-gcs (0.3.0)
* and some filter plugins (differs depending on the workload)

I have encountered this deadlock-like behaviour several times with several s3-to-gcs workloads.
The data size differs depending on the workload, from dozens to hundreds of GB,
and filter plugin being used also vary by workloads.

We also have some s3-to-local workloads and haven't encounterd this problem yet.
So maybe it is due to the embulk-output-gcs plugin (just my imagination, though).
I'll try upgrading the version of embulk-output-gcs to 0.4.1 and see how it goes.

**Comment by dmikurube** [comment]
@ysk24ok Thanks for your updates. Okay, ping me when you see the results.
