### ISSUE TITLE
Example code breaks because of path string not being escaped in the generated seed.yml

### ISSUE THREAD

**Issue by shabeepk** [embulk/embulk#804]
Getting the following error when running the example generated by embulk example command.

The issue is that the seed.yml file generate doesn't escape the backslashes in the path string.

I am using embulk on Windows through powershell.

Embulk was downloaded using the command:

```
PowerShell -Command "& {Invoke-WebRequest http://dl.embulk.org/embulk-latest.jar -OutFile embulk.bat}"
```

```
PS C:\work> .\embulk guess embulk-example\seed.yml -o config.yml
2017-10-04 16:28:01.337 +0500: Embulk v0.8.35
while scanning a double-quoted scalar
 in 'string', line 3, column 16:
      path_prefix: "C:\work\embulk-example\csv\sample_"
                   ^
found unknown escape character w(119)
 in 'string', line 3, column 20:
      path_prefix: "C:\work\embulk-example\csv\sample_"
                       ^

        at org.yaml.snakeyaml.scanner.ScannerImpl.scanFlowScalarNonSpaces(ScannerImpl.java:1909)
        at org.yaml.snakeyaml.scanner.ScannerImpl.scanFlowScalar(ScannerImpl.java:1845)
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchFlowScalar(ScannerImpl.java:1029)
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchDouble(ScannerImpl.java:1011)
        at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:396)
        at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226)
        at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:585)
        at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157)
        at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:133)
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246)
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154)
        at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246)
        at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237)
        at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225)
        at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154)
        at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
        at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:122)
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:505)
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:424)
        at org.embulk.config.ConfigLoader.fromYamlString(ConfigLoader.java:66)
        at org.embulk.EmbulkRunner.readConfig(EmbulkRunner.java:412)
        at org.embulk.EmbulkRunner.guess(EmbulkRunner.java:59)
        at org.embulk.cli.EmbulkRun.runSubcommand(EmbulkRun.java:461)
        at org.embulk.cli.EmbulkRun.run(EmbulkRun.java:99)
        at org.embulk.cli.Main.main(Main.java:28)

Error: while scanning a double-quoted scalar
 in 'string', line 3, column 16:
      path_prefix: "C:\work\embulk-example\csv\sample_"
                   ^
found unknown escape character w(119)
 in 'string', line 3, column 20:
      path_prefix: "C:\work\embulk-example\csv\sample_"

```

Thanks.

Sharique

**Comment by hiroyuki-sato** [comment]
Hello, @shabeepk 

Thank you for reporting this issue.
I reproduced your issue on my environment.
Can you try to change double quote`"` -> single quote `'` as the workaround?

For example.

```yaml
in:
  type: file
  path_prefix: 'C:\Users\user\Desktop\test\csv\sample_'
out:
  type: stdout
```

**Comment by shabeepk** [comment]
Hi,

As a workaround I simple escaped the backslashes, i.e. replaced \ with \\
and it worked. Your fix probably would also work.

I however felt like reporting it so I did. 🙂

Thanks

**Comment by hiroyuki-sato** [comment]
Hello, @shabeepk 

Thank you for replying. 
I made #805 for fix this issue.
