### ISSUE TITLE
Plug-In could not use msgpack-rpc using msgpack-v0.6 with template.

### ISSUE THREAD

**Issue by smdmts** [embulk/embulk#888]
I'm making embulk output plugin with jubatus which using the msgpack-0.6 template with msgpack-rpc. But msgpack template could not compile under embulk running. 
I think this problem should occurring `embulk msgpack version conflicting` or `javaassist` issue. 
Please let me know some workaround's idea?

Please see the issue in details.
- https://github.com/smdmts/embulk-output-jubatus_nearest_neighbor/issues/2

### Stack Trace
```
Caused by: org.msgpack.MessageTypeException: org.msgpack.template.builder.TemplateBuildException: Cannot compile:
	at org.msgpack.template.TemplateRegistry.buildAndRegister(TemplateRegistry.java:516)
	at org.msgpack.template.TemplateRegistry.lookupAfterBuilding(TemplateRegistry.java:413)
	at org.msgpack.template.TemplateRegistry.lookup(TemplateRegistry.java:246)
	at org.msgpack.template.TemplateRegistry.lookupGenericTypeImpl(TemplateRegistry.java:302)
	at org.msgpack.template.TemplateRegistry.lookupGenericType(TemplateRegistry.java:275)
	at org.msgpack.template.TemplateRegistry.lookup(TemplateRegistry.java:201)
	at org.msgpack.template.builder.JavassistTemplateBuilder.toTemplate(JavassistTemplateBuilder.java:128)
	at org.msgpack.template.builder.JavassistTemplateBuilder.buildTemplate(JavassistTemplateBuilder.java:116)
	at org.msgpack.template.builder.AbstractTemplateBuilder.buildTemplate(AbstractTemplateBuilder.java:61)
	at org.msgpack.template.TemplateRegistry.buildAndRegister(TemplateRegistry.java:503)
	at org.msgpack.template.TemplateRegistry.lookupAfterBuilding(TemplateRegistry.java:413)
	at org.msgpack.template.TemplateRegistry.lookup(TemplateRegistry.java:246)
	at org.msgpack.MessagePack.lookup(MessagePack.java:620)
	at org.msgpack.packer.AbstractPacker.write(AbstractPacker.java:202)
	at org.msgpack.rpc.message.RequestMessage.writeTo(RequestMessage.java:57)
	at org.msgpack.template.MessagePackableTemplate.write(MessagePackableTemplate.java:42)
	at org.msgpack.template.MessagePackableTemplate.write(MessagePackableTemplate.java:26)
	at org.msgpack.template.AbstractTemplate.write(AbstractTemplate.java:27)
	at org.msgpack.MessagePack.write(MessagePack.java:234)
	at org.msgpack.rpc.transport.PooledStreamClientTransport.sendMessage(PooledStreamClientTransport.java:73)
	at org.msgpack.rpc.Session.sendRequest(Session.java:121)
	at org.msgpack.rpc.Session.callAsyncApply(Session.java:106)
	at us.jubat.common.ClientBase.call(ClientBase.java:35)
	at org.embulk.output.jubatus_nearest_neighbor.jubatus.JubatusJava.setRow(JubatusJava.java:23)
	at org.embulk.output.jubatus_nearest_neighbor.JubatusNearestNeighborSetOutputPlugin.transaction(JubatusNearestNeighborSetOutputPlugin.scala:18)
	at org.embulk.exec.BulkLoader$4$1$1.transaction(BulkLoader.java:560)
	at org.embulk.exec.LocalExecutorPlugin.transaction(LocalExecutorPlugin.java:54)
	at org.embulk.exec.BulkLoader$4$1.run(BulkLoader.java:555)
	at org.embulk.spi.util.Filters$RecursiveControl.transaction(Filters.java:96)
	at org.embulk.spi.util.Filters$RecursiveControl$1.run(Filters.java:92)
	at org.embulk.filter.column.ColumnFilterPlugin.transaction(ColumnFilterPlugin.java:81)
	at org.embulk.spi.util.Filters$RecursiveControl.transaction(Filters.java:87)
	at org.embulk.spi.util.Filters.transaction(Filters.java:49)
	at org.embulk.exec.BulkLoader$4.run(BulkLoader.java:549)
	at org.embulk.spi.FileInputRunner$RunnerControl$1$1.run(FileInputRunner.java:126)
	at org.embulk.standards.CsvParserPlugin.transaction(CsvParserPlugin.java:247)
	at org.embulk.spi.FileInputRunner$RunnerControl$1.run(FileInputRunner.java:120)
	at org.embulk.spi.util.Decoders$RecursiveControl.transaction(Decoders.java:77)
	at org.embulk.spi.util.Decoders.transaction(Decoders.java:33)
	at org.embulk.spi.FileInputRunner$RunnerControl.run(FileInputRunner.java:117)
	at org.embulk.standards.LocalFileInputPlugin.resume(LocalFileInputPlugin.java:87)
	at org.embulk.standards.LocalFileInputPlugin.transaction(LocalFileInputPlugin.java:77)
	at org.embulk.spi.FileInputRunner.transaction(FileInputRunner.java:67)
	at org.embulk.exec.BulkLoader.doRun(BulkLoader.java:544)
	... 11 more
Caused by: org.msgpack.template.builder.TemplateBuildException: Cannot compile:
	at org.msgpack.template.builder.BuildContext.build(BuildContext.java:73)
	at org.msgpack.template.builder.DefaultBuildContext.buildTemplate(DefaultBuildContext.java:56)
	at org.msgpack.template.builder.JavassistTemplateBuilder.buildTemplate(JavassistTemplateBuilder.java:118)
	at org.msgpack.template.builder.AbstractTemplateBuilder.buildTemplate(AbstractTemplateBuilder.java:61)
	at org.msgpack.template.TemplateRegistry.buildAndRegister(TemplateRegistry.java:503)
	... 54 more
Caused by: java.lang.NullPointerException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at javassist.ClassPool.toClass2(ClassPool.java:1112)
	at javassist.ClassPool.toClass(ClassPool.java:1093)
	at javassist.CtClass.toClass(CtClass.java:1181)
	at org.msgpack.template.builder.BuildContext.createClass(BuildContext.java:154)
	at org.msgpack.template.builder.BuildContext.build(BuildContext.java:68)
	... 58 more
```

**Comment by dmikurube** [comment]
@smdmts Do you mean msgpack-java-v0.6?

AFAIK, msgpack-java-v0.6 has been obsolete. We have no intention to support the obsolete version... Any reason you need to use v0.6?

**Comment by smdmts** [comment]
@dmikurube Yes. Because of msgpack-java-v0.6 is required Jubatus(as machine learning middleware)  client module.
The msgpack-rpc-java is unmaintained 5 years, and I understood it is difficult to use current embulk version. ;-p

- https://github.com/jubatus/jubatus-java-client/blob/master/pom.xml#L104
- https://github.com/msgpack-rpc/msgpack-rpc-java/blob/master/pom.xml#L108

**Comment by dmikurube** [comment]
@smdmts To be honest, msgpack-java-0.6 and msgpack-java-0.8 do not conflict by themselves. Their Java package names are totally disjoint. They can live together. (We have such an environment internally which msgpack-java-0.6 and msgpack-java-0.8 are together with a method converting from 0.6 to 0.8.)

I'm afraid it MAY not be conflict with Embulk, but another issue unrelated to Embulk. It can be worth tracing. (I'm not perfectly sure, though.)

**Comment by smdmts** [comment]
@dmikurube Understood. Currently, It may not be working msgpack-rpc-java which using any middleware.  
Thank you for the support.
